In [7]:
# Set the CRAN mirror
options(repos = c(CRAN = "https://cran.r-project.org"))

# If not already downloaded in environment, then download DESeq2
if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")
}
BiocManager::install("DESeq2")

'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.r-project.org

Bioconductor version 3.18 (BiocManager 1.30.22), R 4.3.1 (2023-06-16)

Installing package(s) 'BiocVersion', 'DESeq2'

also installing the dependencies ‘bitops’, ‘formatR’, ‘colorspace’, ‘RCurl’, ‘GenomeInfoDbData’, ‘zlibbioc’, ‘abind’, ‘SparseArray’, ‘lambda.r’, ‘futile.options’, ‘nlme’, ‘farver’, ‘labeling’, ‘munsell’, ‘RColorBrewer’, ‘viridisLite’, ‘magrittr’, ‘pkgconfig’, ‘GenomeInfoDb’, ‘XVector’, ‘S4Arrays’, ‘DelayedArray’, ‘futile.logger’, ‘snow’, ‘codetools’, ‘BH’, ‘cpp11’, ‘gtable’, ‘isoband’, ‘MASS’, ‘mgcv’, ‘scales’, ‘tibble’, ‘S4Vectors’, ‘IRanges’, ‘GenomicRanges’, ‘SummarizedExperiment’, ‘BiocGenerics’, ‘Biobase’, ‘BiocParallel’, ‘matrixStats’, ‘locfit’, ‘ggplot2’, ‘MatrixGenerics’, ‘RcppArmadillo’


Old packages: 'cli', 'fansi', 'htmltools', 'jsonlite', 'Matrix', 'rlang',
  'vctrs'

In [16]:
install.packages("anndata")

In [1]:
# Load libraries
library("anndata")
library("DESeq2")
library("reticulate")

Loading required package: S4Vectors

Loading required package: stats4

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min



Attaching package: ‘S4Vectors’


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges

Loading required package: GenomicRanges

Loading required package: GenomeInfoDb

Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats


Attaching package: ‘MatrixGenerics’


The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘Biobase’


The following object is masked from ‘package:MatrixGenerics’:

    rowMedians


The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians

In [5]:
# Use the path to your Python executable in the virtual environment
use_python("/lila/home/forsythb/.virtualenvs/r-reticulate/bin/")

In [6]:
# Look at where Python is located
py_config()

python:         /lila/home/forsythb/.virtualenvs/r-reticulate/bin/python
libpython:      /home/forsythb/anaconda3/lib/libpython3.8.so
pythonhome:     /lila/home/forsythb/.virtualenvs/r-reticulate:/lila/home/forsythb/.virtualenvs/r-reticulate
version:        3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0]
numpy:          /lila/home/forsythb/.virtualenvs/r-reticulate/lib/python3.8/site-packages/numpy
numpy_version:  1.24.4

NOTE: Python version was forced by use_python() function

In [8]:
# Import scanpy
sc <- import("scanpy")

# FOR DESeq Metacell Analysis

## design = ~ Tumor_Site + Culture_Media + Patient + ZFP_Expression

In [9]:
# Read in the adata
adata <- sc$read_h5ad("/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/metacells_noscvi/adata.post.combined.h5ad")

In [10]:
# Extract count matrix from the raw layer
count_matrix <- adata$raw$X
count_matrix <- t(count_matrix)
count_matrix <- round(count_matrix)

In [11]:
# Define the column data
coldata <- adata$obs[,c("Tumor_Site","Culture_Media", "ZFP_Expression", "Batch", "Patient")]

# Convert column data to factors
coldata$Tumor_Site <- factor(coldata$Tumor_Site)
coldata$Culture_Media <- factor(coldata$Culture_Media)
coldata$ZFP_Expression <- factor(coldata$ZFP_Expression)
coldata$Batch <- factor(coldata$Batch)
coldata$Patient <- factor(coldata$Patient)

In [12]:
# Design a DESeqDataSet
dds_1 <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = coldata,
  design = ~ Tumor_Site + Culture_Media + Patient + ZFP_Expression 
)

converting counts to integer mode

In [13]:
# Add a pseudo-count of 1 to all counts
count_matrix <- counts(dds_1) + 1

# Specify the row names as the gene names
rownames(count_matrix) <- adata$raw$var_names

In [14]:
# Set the reference levels
dds_1$Tumor_Site<-relevel(dds_1$Tumor_Site,ref="Primary")
dds_1$Culture_Media<-relevel(dds_1$Culture_Media,ref="BASE")
dds_1$ZFP_Expression<-relevel(dds_1$ZFP_Expression,ref="CTRL")
dds_1$Patient<-relevel(dds_1$Patient,ref="125")

In [15]:
# Design a DESeqDataSet with modified count matrix
dds_1 <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = coldata,
  design = ~ Tumor_Site + Culture_Media + Patient + ZFP_Expression 
)

converting counts to integer mode

In [16]:
# Perform DESeq analysis
dds_1 <- DESeq(dds_1)

estimating size factors

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

-- note: fitType='parametric', but the dispersion trend was not well captured by the
   function: y = a/x + b, and a local regression fit was automatically substituted.
   specify fitType='local' or 'mean' to avoid this message next time.

final dispersion estimates

fitting model and testing

In [17]:
# Extract results
result_names_1 <- resultsNames(dds_1)
result_names_1

# Specify the contrast and extract results
res_1 <- results(dds_1)
res_1

[1] "Intercept"
[2] "Tumor_Site_Primary_vs_Metastatic"
[3] "Culture_Media_Dedifferentiated_vs_BASE"
[4] "Culture_Media_HISC_vs_BASE"
[5] "Patient_146_vs_125"
[6] "ZFP_Expression_ZFPKD_vs_CTRL"

log2 fold change (MLE): ZFP Expression ZFPKD vs CTRL
Wald test p-value: ZFP Expression ZFPKD vs CTRL
DataFrame with 32485 rows and 6 columns
          baseMean log2FoldChange     lfcSE       stat      pvalue        padj
         <numeric>      <numeric> <numeric>  <numeric>   <numeric>   <numeric>
A1BG       1.02231     0.00211305 0.0479774  0.0440427    0.964870          NA
A1BG-AS1   1.01236     0.00216575 0.0482165  0.0449172    0.964173          NA
A1CF       3.33497    -0.01149037 0.0266570 -0.4310456    0.666435    0.906265
A2M        1.02463    -0.03585165 0.0477423 -0.7509409    0.452688          NA
A2M-AS1    1.02563    -0.03043614 0.0477451 -0.6374714    0.523818          NA
...            ...            ...       ...        ...         ...         ...
ZXDC       3.80565     -0.0227616 0.0247967  -0.917929 3.58656e-01 7.20065e-01
ZYG11A     1.04943     -0.0187291 0.0472598  -0.396300 6.91884e-01          NA
ZYG11B     3.71665     -0.0163685 0.0251284  -0.651394 5.14792e-01 8.31422e-01
ZYX        2.62246     -0.1414233 0.0295128  -4.791931 1.65184e-06 6.69534e-05
ZZEF1      3.12789      0.0279146 0.0275063   1.014843 3.10181e-01 6.74684e-01

In [18]:
# Specify the file path where you want to save the results
result_file <- "/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/deseq/metacell_zfpexp_results.csv"

# Write the results table to a CSV file
write.csv(as.data.frame(res_1), file = result_file)

# Save the DESeqDataSet object
saveRDS(dds_1, file = "/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/deseq/metacell_zfpexp_dds.rds")

# Save the DESeq results
saveRDS(results(dds_1), file = "/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/deseq/metacell_zfpexp_results.rds")

Metacells. ZFP Expression. No interaction term.

In [9]:
# Read in the adata
adata <- sc$read_h5ad("/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/metacells_noscvi/adata.post.combined.h5ad")

In [10]:
# Extract count matrix from the raw layer
count_matrix <- adata$raw$X
count_matrix <- t(count_matrix)
count_matrix <- round(count_matrix)

In [11]:
# Define the column data
coldata <- adata$obs[,c("Tumor_Site","Culture_Media", "ZFP_Expression", "Batch", "Patient")]

# Convert column data to factors
coldata$Tumor_Site <- factor(coldata$Tumor_Site)
coldata$Culture_Media <- factor(coldata$Culture_Media)
coldata$ZFP_Expression <- factor(coldata$ZFP_Expression)
coldata$Batch <- factor(coldata$Batch)
coldata$Patient <- factor(coldata$Patient)

In [12]:
# Design a DESeqDataSet
dds_1 <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = coldata,
  design = ~ Tumor_Site + Culture_Media + Patient + ZFP_Expression 
)

converting counts to integer mode

In [13]:
# Add a pseudo-count of 1 to all counts
count_matrix <- counts(dds_1) + 1

# Specify the row names as the gene names
rownames(count_matrix) <- adata$raw$var_names

In [14]:
# Set the reference levels
dds_1$Tumor_Site<-relevel(dds_1$Tumor_Site,ref="Primary")
dds_1$Culture_Media<-relevel(dds_1$Culture_Media,ref="BASE")
dds_1$ZFP_Expression<-relevel(dds_1$ZFP_Expression,ref="CTRL")
dds_1$Patient<-relevel(dds_1$Patient,ref="125")

In [15]:
# Design a DESeqDataSet with modified count matrix
dds_1 <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = coldata,
  design = ~ Tumor_Site + Culture_Media + Patient + ZFP_Expression 
)

converting counts to integer mode

In [ ]:
# Perform DESeq analysis
dds_1 <- DESeq(dds_1)

estimating size factors

estimating dispersions

gene-wise dispersion estimates

In [ ]:
# Extract results
result_names_1 <- resultsNames(dds_1)
result_names_1

# Specify the contrast and extract results
res_1 <- results(dds_1)
res_1

In [ ]:
# Specify the file path where you want to save the results
result_file <- "/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/deseq/metacell_zfpexp_results.csv"

# Write the results table to a CSV file
write.csv(as.data.frame(res_1), file = result_file)

# Save the DESeqDataSet object
saveRDS(dds_1, file = "/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/deseq/metacell_zfpexp_dds.rds")

# Save the DESeq results
saveRDS(results(dds_1), file = "/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/deseq/metacell_zfpexp_results.rds")

In [ ]:
source /lila/home/forsythb/.virtualenvs/r-reticulate/

In [6]:
# Read in the count matrix 
count_matrix <- read.csv("/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/combined/out_post_hvg/metacells_count_matrix.csv")

In [10]:
# Transpose and round count matrix
count_matrix <- t(count_matrix)
count_matrix <- as.matrix(count_matrix)

In [ ]:
# Add a pseudo-count of 1 to all counts
count_matrix <- count_matrix + 1

In [11]:
# Look at the count matrix
count_matrix

            [,1]                           [,2]
X           146_P_BASE_ZFPKD_2_SEACell-139 146_P_BASE_ZFPKD_1_SEACell-90
A1BG        0.0000000                      0.0000000
A1BG.AS1    0.0000000                      0.0000000
A1CF        3.9189490                      4.3330428
A2M         0.0000000                      0.0000000
A2M.AS1     0.0000000                      0.0000000
A2ML1       0.0000000                      0.0000000
A2ML1.AS1   0.0000000                      0.0000000
A2ML1.AS2   0.0000000                      0.0000000
A3GALT2     0.0000000                      0.0000000
A4GALT      0.0000000                      0.0000000
A4GNT       0.000000                       0.000000
AAAS        2.2088860                      1.4615652
AACS        3.3650782                      2.8884529
AADAC       0.0000000                      0.0000000
AADACL2     0.0000000                      0.0000000
AADACL2.AS1 0.0000000                      1.0666336
AADACL3     0.0000000                      0.0000000
AADACL4     0.0000000                      0.0000000
AADAT       0.5468200                      0.8804894
AAGAB       2.5551500                      1.9198866
AAK1        1.9122210                      2.7013537
AAMDC       3.5085434                      2.8488430
AAMP        2.8352743                      3.3315064
AANAT       0.0000000                      0.0000000
AAR2        1.7911654                      1.6720467
AARD        0.0000000                      0.0000000
AARS        1.7278738                      0.0000000
AARS2       1.7238803                      1.4494802
AARSD1      2.4608328                      2.3090126
⋮           ⋮                              ⋮
ZSCAN29     1.6803831                      1.5304456
ZSCAN30     1.3150172                      0.0000000
ZSCAN31     1.5167927                      0.0000000
ZSCAN32     0.0000000                      0.6706933
ZSCAN4      0.0000000                      0.0000000
ZSCAN5A     1.4315071                      0.0000000
ZSCAN5B     0.0000000                      0.0000000
ZSCAN5C     0.0000000                      0.0000000
ZSCAN9      0.7248106                      0.8140171
ZSWIM1      0.6297337                      1.6720467
ZSWIM2      0.0000000                      0.0000000
ZSWIM3      1.0063835                      0.8985089
ZSWIM4      0.6429855                      0.0000000
ZSWIM5      2.5834974                      3.4458467
ZSWIM6      3.5327405                      3.1514530
ZSWIM7      1.5203379                      1.8443257
ZSWIM8      1.4784002                      1.7324577
ZSWIM8.AS1  0.0000000                      0.0000000
ZSWIM9      1.9297613                      1.1704772
ZUP1        1.4536611                      2.0657765
ZW10        1.1559183                      0.9809860
ZWILCH      2.2458036                      0.0000000
ZWINT       4.1663892                      0.0000000
ZXDA        0.0000000                      0.0000000
ZXDB        0.2925713                      1.5174267
ZXDC        2.7237472                      3.0996428
ZYG11A      0.0000000                      0.0000000
ZYG11B      2.6228870                      2.9832100
ZYX         0.9792583                      0.0000000
ZZEF1       1.9387595                      1.9745979
            [,3]                          [,4]
X           146_P_HISC_ZFPKD_2_SEACell-82 125_P_BASE_ZFPKD_2_SEACell-29
A1BG        0.0000000                     0.0000000
A1BG.AS1    0.0000000                     0.0000000
A1CF        3.7144981                     0.0000000
A2M         0.0000000                     0.0000000
A2M.AS1     0.0000000                     0.0000000
A2ML1       0.0000000                     0.0000000
A2ML1.AS1   0.0000000                     0.0000000
A2ML1.AS2   0.0000000                     0.0000000
A3GALT2     0.0000000                     0.0000000
A4GALT      0.0000000                     0.0000000
A4GNT       0.000000                      0.000000
AAAS        1.1470278                     1.9379012
AACS        1.2434982                     2.0244361
AADAC       0.0000000                     0.0000000
AADACL2     0.0000000                     0.0000000
AADACL2.AS1 0.0000000                     0.0000000
AADACL3     0.0000000                     0.0000000
AADACL4     0.0000000                     0.0000000
AADAT       2.0830184                     2.0244361
AAGAB       3.3764410                     2.5886524
AAK1        3.6454381                     3.9013264
AAMDC       3.4524424                     3.6531023
AAMP        2.0928143                     0.0000000
AANAT       0.0000000                     0.0000000
AAR2        1.3376257                     0.0000000
AARD        0.0000000                     0.0000000
AARS        2.7819675                     2.1655675
AARS2       1.6093872                     2.3724412
AARSD1      1.8642794                     3.3066562
⋮           ⋮                             ⋮
ZSCAN29     1.0796408                     0.0000000
ZSCAN30     1.5578319                     2.2381527
ZSCAN31     1.6697726                     0.0000000
ZSCAN32     1.0796408                     0.0000000
ZSCAN4      0.0000000                     0.0000000
ZSCAN5A     1.3006963                     2.3397262
ZSCAN5B     0.0000000                     0.0000000
ZSCAN5C     0.0000000                     0.0000000
ZSCAN9      0.0000000                     0.0000000
ZSWIM1      2.0818058                     0.0000000
ZSWIM2      0.0000000                     0.0000000
ZSWIM3      1.1611831                     0.0000000
ZSWIM4      1.3006963                     1.9379012
ZSWIM5      3.6383629                     4.9196883
ZSWIM6      4.2804188                     5.1530692
ZSWIM7      2.3052220                     1.9379012
ZSWIM8      2.6885348                     0.0000000
ZSWIM8.AS1  0.0000000                     0.0000000
ZSWIM9      0.8723173                     2.1655675
ZUP1        0.0000000                     0.0000000
ZW10        0.9599458                     0.0000000
ZWILCH      0.0000000                     0.0000000
ZWINT       0.0000000                     0.0000000
ZXDA        0.0000000                     0.0000000
ZXDB        0.6669788                     0.0000000
ZXDC        2.5675822                     4.4449000
ZYG11A      0.6669788                     0.0000000
ZYG11B      3.6912427                     2.6684075
ZYX         0.0000000                     0.0000000
ZZEF1       1.9987223                     3.8612627
            [,5]                             [,6]
X           146_M_Dediff_ZFPKD_2_SEACell-109 146_P_HISC_ZFPKD_1_SEACell-63
A1BG        0.0000000                        0.0000000
A1BG.AS1    0.0000000                        0.0000000
A1CF        2.2041534                        3.1639819
A2M         0.0000000                        0.0000000
A2M.AS1     0.0000000                        0.0000000
A2ML1       0.0000000                        0.0000000
A2ML1.AS1   0.0000000                        0.0000000
A2ML1.AS2   0.0000000                        0.0000000
A3GALT2     0.0000000                        0.0000000
A4GALT      0.0000000                        0.0000000
A4GNT       0.000000                         0.000000
AAAS        2.3015302                        2.2140855
AACS        3.6119716                        3.2013172
AADAC       0.0000000                        0.0000000
AADACL2     0.0000000                        0.0000000
AADACL2.AS1 0.0000000                        0.0000000
AADACL3     0.0000000                        0.0000000
AADACL4     0.0000000                        0.0000000
AADAT       0.0000000                        1.2434761
AAGAB       3.3923195                        3.3659360
AAK1        2.6083411                        3.1553526
AAMDC       2.4919203                        1.9510347
AAMP        2.0304893                        2.6752809
AANAT       0.0000000                        0.0000000
AAR2        2.4559596                        1.3619213
AARD        0.0000000                        0.0000000
AARS        3.0248101                        2.7824822
AARS2       1.4536919                        1.2289914
AARSD1      2.1216733                        2.1714982
⋮           ⋮                                ⋮
ZSCAN29     1.1452688                        2.2905500
ZSCAN30     1.0644858                        1.7980205
ZSCAN31     2.1605032                        0.0000000
ZSCAN32     0.0000000                        0.7271186
ZSCAN4      0.0000000                        0.0000000
ZSCAN5A     2.2764426                        2.2864323
ZSCAN5B     0.0000000                        0.0000000
ZSCAN5C     0.0000000                        0.0000000
ZSCAN9      1.8626199                        0.7271186
ZSWIM1      0.0000000                        0.0000000
ZSWIM2      0.0000000                        0.0000000
ZSWIM3      1.2778667                        0.7974534
ZSWIM4      2.3391045                        0.7271186
ZSWIM5      4.1215731                        3.6627355
ZSWIM6      3.9371757                        3.2443251
ZSWIM7      0.0000000                        1.4946842
ZSWIM8      2.6692162                        0.7759806
ZSWIM8.AS1  0.0000000                        0.8936875
ZSWIM9      2.9038340                        1.7131744
ZUP1        2.7709511                        1.2289914
ZW10        1.8094153                        1.4602750
ZWILCH      3.3758574                        1.5881907
ZWINT       3.4663714                        2.4160839
ZXDA        0.0000000                        0.0000000
ZXDB        0.0000000                        0.0000000
ZXDC        2.9004761                        3.0622860
ZYG11A      0.0000000                        0.0000000
ZYG11B      3.3703084                        2.7569235
ZYX         0.0000000                        1.3254275
ZZEF1       3.1723968                        1.8599860
            [,7]                          [,8]
X           125_P_HISC_ZFPKD_2_SEACell-75 146_P_HISC_CTRL_1_SEACell-133
A1BG        0.0000000                     0.0000000
A1BG.AS1    0.0000000                     0.0000000
A1CF        0.8930490                     3.2165162
A2M         0.0000000                     0.0000000
A2M.AS1     0.0000000                     0.0000000
A2ML1       0.0000000                     0.0000000
A2ML1.AS1   0.0000000                     0.0000000
A2ML1.AS2   0.0000000                     0.0000000
A3GALT2     0.0000000                     0.0000000
A4GALT      0.0000000                     0.0000000
A4GNT       0.000000                      0.000000
AAAS        2.3623324                     2.0775197
AACS        2.9352167                     1.1454382
AADAC       0.0000000                     0.0000000
AADACL2     0.0000000                     0.0000000
AADACL2.AS1 2.0757785                     0.0000000
AADACL3     0.0000000                     0.0000000
AADACL4     0.0000000                     0.0000000
AADAT       0.0000000                     1.0998602
AAGAB       2.6303207                     2.6007526
AAK1        2.8358850                     2.9634620
AAMDC       2.0287620                     1.8201560
AAMP        2.8812297                     3.0864042
AANAT       0.0000000                     0.0000000
AAR2        2.1309327                     1.4848956
AARD        0.0000000                     0.0000000
AARS        2.6922956                     2.5835373
AARS2       1.3735193                     1.7594622
AARSD1      2.3178847                     2.8183377
⋮           ⋮                             ⋮
ZSCAN29     0.7940388                     1.4230101
ZSCAN30     0.0000000                     1.2865527
ZSCAN31     0.9370293                     0.0000000
ZSCAN32     0.9370293                     1.3409723
ZSCAN4      0.0000000                     0.0000000
ZSCAN5A     2.5673917                     0.8402402
ZSCAN5B     0.0000000                     0.0000000
ZSCAN5C     0.0000000                     0.0000000
ZSCAN9      1.0247594                     0.0000000
ZSWIM1      0.0000000                     0.0000000
ZSWIM2      0.0000000                     0.0000000
ZSWIM3      0.0000000                     0.7982645
ZSWIM4      0.9370293                     0.0000000
ZSWIM5      2.5976617                     3.5237384
ZSWIM6      3.8123239                     4.0930718
ZSWIM7      2.2938754                     3.0315395
ZSWIM8      0.0000000                     0.8153511
ZSWIM8.AS1  0.0000000                     0.0000000
ZSWIM9      1.3644329                     2.3150856
ZUP1        1.5542250                     2.0234924
ZW10        1.4496432                     1.2494055
ZWILCH      1.7173767                     1.8410204
ZWINT       2.3769017                     2.8726413
ZXDA        0.0000000                     0.0000000
ZXDB        1.3530170                     0.0000000
ZXDC        3.3223817                     2.4340736
ZYG11A      0.0000000                     0.0000000
ZYG11B      2.1598056                     2.5650931
ZYX         2.5355093                     1.8971029
ZZEF1       2.5491794                     0.9034024
            [,9]                            [,10]                        [,11]
X           146_M_Dediff_CTRL_1_SEACell-105 146_M_HISC_ZFPKD_1_SEACell-3 ⋯
A1BG        0.0000000                       0.0000000                    ⋯
A1BG.AS1    0.0000000                       0.0000000                    ⋯
A1CF        2.7030099                       4.0104060                    ⋯
A2M         0.0000000                       0.0000000                    ⋯
A2M.AS1     0.0000000                       0.0000000                    ⋯
A2ML1       0.0000000                       0.0000000                    ⋯
A2ML1.AS1   0.0000000                       0.0000000                    ⋯
A2ML1.AS2   0.0000000                       0.0000000                    ⋯
A3GALT2     0.0000000                       0.0000000                    ⋯
A4GALT      0.0000000                       0.0000000                    ⋯
A4GNT       0.000000                        0.000000                     ⋯
AAAS        1.9513491                       1.7067350                    ⋯
AACS        3.2105221                       3.3840992                    ⋯
AADAC       0.0000000                       0.0000000                    ⋯
AADACL2     0.0000000                       0.0000000                    ⋯
AADACL2.AS1 0.0000000                       1.2747899                    ⋯
AADACL3     0.0000000                       0.0000000                    ⋯
AADACL4     0.0000000                       0.0000000                    ⋯
AADAT       0.0000000                       0.0000000                    ⋯
AAGAB       3.0811840                       2.4554411                    ⋯
AAK1        3.6513350                       3.8434128                    ⋯
AAMDC       0.0000000                       3.6956277                    ⋯
AAMP        2.8074677                       2.8199014                    ⋯
AANAT       0.0000000                       0.0000000                    ⋯
AAR2        1.6625102                       2.5336418                    ⋯
AARD        0.0000000                       0.0000000                    ⋯
AARS        1.4660010                       3.5723695                    ⋯
AARS2       1.4660010                       0.0000000                    ⋯
AARSD1      0.0000000                       1.4522250                    ⋯
⋮           ⋮                               ⋮                            ⋱
ZSCAN29     0.0000000                       0.0000000                    ⋯
ZSCAN30     0.0000000                       1.4918462                    ⋯
ZSCAN31     1.6625102                       0.0000000                    ⋯
ZSCAN32     2.8718264                       1.2422244                    ⋯
ZSCAN4      0.0000000                       0.0000000                    ⋯
ZSCAN5A     3.5419183                       1.4067957                    ⋯
ZSCAN5B     0.0000000                       0.0000000                    ⋯
ZSCAN5C     0.0000000                       0.0000000                    ⋯
ZSCAN9      1.5375908                       0.0000000                    ⋯
ZSWIM1      0.0000000                       1.4067957                    ⋯
ZSWIM2      0.0000000                       0.0000000                    ⋯
ZSWIM3      1.5375908                       0.0000000                    ⋯
ZSWIM4      2.1349808                       1.2422244                    ⋯
ZSWIM5      3.9771175                       3.2493401                    ⋯
ZSWIM6      4.0010498                       4.2188954                    ⋯
ZSWIM7      2.5524712                       3.2315748                    ⋯
ZSWIM8      0.0000000                       0.0000000                    ⋯
ZSWIM8.AS1  0.0000000                       0.0000000                    ⋯
ZSWIM9      1.4660010                       1.2422244                    ⋯
ZUP1        3.4911971                       0.0000000                    ⋯
ZW10        1.5375908                       1.1971104                    ⋯
ZWILCH      1.6223073                       0.0000000                    ⋯
ZWINT       0.0000000                       0.0000000                    ⋯
ZXDA        0.0000000                       0.0000000                    ⋯
ZXDB        0.0000000                       0.0000000                    ⋯
ZXDC        0.0000000                       1.9801912                    ⋯
ZYG11A      0.0000000                       0.0000000                    ⋯
ZYG11B      2.6531812                       2.1897978                    ⋯
ZYX         2.2743845                       1.7067350                    ⋯
ZZEF1       2.7503436                       1.9460267                    ⋯
            [,12]                         [,13]
X           146_P_BASE_ZFPKD_2_SEACell-63 146_P_BASE_CTRL_1_SEACell-204
A1BG        0.0000000                     0.0000000
A1BG.AS1    0.0000000                     0.0000000
A1CF        4.1836377                     0.0000000
A2M         0.0000000                     0.0000000
A2M.AS1     0.0000000                     0.0000000
A2ML1       0.0000000                     0.0000000
A2ML1.AS1   0.0000000                     0.0000000
A2ML1.AS2   0.0000000                     0.0000000
A3GALT2     0.0000000                     0.0000000
A4GALT      0.0000000                     0.0000000
A4GNT       0.000000                      0.000000
AAAS        0.0000000                     0.0000000
AACS        3.7349318                     0.0000000
AADAC       0.0000000                     0.0000000
AADACL2     0.0000000                     0.0000000
AADACL2.AS1 0.0000000                     0.0000000
AADACL3     0.0000000                     0.0000000
AADACL4     0.0000000                     0.0000000
AADAT       1.0942416                     0.0000000
AAGAB       1.8933531                     0.0000000
AAK1        1.4512192                     4.7412535
AAMDC       3.4070992                     4.7412535
AAMP        2.6744953                     0.0000000
AANAT       0.0000000                     0.0000000
AAR2        1.3095605                     0.0000000
AARD        0.0000000                     0.0000000
AARS        1.0570315                     0.0000000
AARS2       0.0000000                     0.0000000
AARSD1      2.5727762                     0.0000000
⋮           ⋮                             ⋮
ZSCAN29     0.0000000                     0.0000000
ZSCAN30     2.3829735                     0.0000000
ZSCAN31     0.0000000                     0.0000000
ZSCAN32     1.2266644                     0.0000000
ZSCAN4      0.0000000                     0.0000000
ZSCAN5A     1.7971214                     0.0000000
ZSCAN5B     0.0000000                     0.0000000
ZSCAN5C     0.0000000                     0.0000000
ZSCAN9      0.0000000                     0.0000000

In [3]:
# Read in the observations
adata_obs <- read.csv("/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/metacells_noscvi/obs.combined.csv", sep = "\t")

In [19]:
# Look at the observation data
adata_obs

     X                                Patient Tumor_Site Culture_Media
1    146_P_BASE_ZFPKD_2_SEACell-139   146     Primary    BASE
2    146_P_BASE_ZFPKD_1_SEACell-90    146     Primary    BASE
3    146_P_HISC_ZFPKD_2_SEACell-82    146     Primary    HISC
4    125_P_BASE_ZFPKD_2_SEACell-29    125     Primary    BASE
5    146_M_Dediff_ZFPKD_2_SEACell-109 146     Metastatic Dedifferentiated
6    146_P_HISC_ZFPKD_1_SEACell-63    146     Primary    HISC
7    125_P_HISC_ZFPKD_2_SEACell-75    125     Primary    HISC
8    146_P_HISC_CTRL_1_SEACell-133    146     Primary    HISC
9    146_M_Dediff_CTRL_1_SEACell-105  146     Metastatic Dedifferentiated
10   146_M_HISC_ZFPKD_1_SEACell-3     146     Metastatic HISC
11   146_P_HISC_ZFPKD_2_SEACell-116   146     Primary    HISC
12   146_P_HISC_CTRL_1_SEACell-199    146     Primary    HISC
13   146_M_HISC_ZFPKD_1_SEACell-158   146     Metastatic HISC
14   125_P_HISC_CTRL_1_SEACell-119    125     Primary    HISC
15   146_P_BASE_CTRL_1_SEACell-121    146     Primary    BASE
16   125_P_BASE_ZFPKD_1_SEACell-120   125     Primary    BASE
17   125_P_HISC_ZFPKD_1_SEACell-108   125     Primary    HISC
18   125_P_HISC_CTRL_1_SEACell-185    125     Primary    HISC
19   125_P_HISC_CTRL_1_SEACell-214    125     Primary    HISC
20   125_P_BASE_CTRL_1_SEACell-80     125     Primary    BASE
21   146_M_HISC_ZFPKD_1_SEACell-152   146     Metastatic HISC
22   146_P_HISC_ZFPKD_2_SEACell-188   146     Primary    HISC
23   146_M_BASE_CTRL_1_SEACell-94     146     Metastatic BASE
24   146_P_BASE_ZFPKD_1_SEACell-57    146     Primary    BASE
25   146_M_Dediff_CTRL_1_SEACell-135  146     Metastatic Dedifferentiated
26   146_M_BASE_ZFPKD_1_SEACell-68    146     Metastatic BASE
27   146_M_BASE_CTRL_1_SEACell-154    146     Metastatic BASE
28   146_P_BASE_CTRL_1_SEACell-136    146     Primary    BASE
29   125_P_HISC_ZFPKD_1_SEACell-164   125     Primary    HISC
30   125_P_HISC_CTRL_1_SEACell-82     125     Primary    HISC
⋮    ⋮                                ⋮       ⋮          ⋮
3905 146_P_HISC_ZFPKD_2_SEACell-210   146     Primary    HISC
3906 146_M_BASE_ZFPKD_2_SEACell-8     146     Metastatic BASE
3907 125_P_BASE_ZFPKD_1_SEACell-92    125     Primary    BASE
3908 125_P_HISC_ZFPKD_1_SEACell-244   125     Primary    HISC
3909 146_M_BASE_CTRL_1_SEACell-148    146     Metastatic BASE
3910 146_P_HISC_ZFPKD_1_SEACell-126   146     Primary    HISC
3911 146_M_Dediff_CTRL_1_SEACell-19   146     Metastatic Dedifferentiated
3912 146_M_BASE_ZFPKD_1_SEACell-184   146     Metastatic BASE
3913 146_M_Dediff_ZFPKD_2_SEACell-68  146     Metastatic Dedifferentiated
3914 125_P_BASE_ZFPKD_1_SEACell-49    125     Primary    BASE
3915 125_P_HISC_ZFPKD_2_SEACell-135   125     Primary    HISC
3916 146_M_BASE_CTRL_1_SEACell-111    146     Metastatic BASE
3917 146_P_HISC_ZFPKD_2_SEACell-154   146     Primary    HISC
3918 146_P_HISC_ZFPKD_2_SEACell-15    146     Primary    HISC
3919 146_P_HISC_ZFPKD_2_SEACell-72    146     Primary    HISC
3920 146_P_BASE_ZFPKD_1_SEACell-133   146     Primary    BASE
3921 146_M_BASE_ZFPKD_2_SEACell-38    146     Metastatic BASE
3922 146_P_BASE_CTRL_1_SEACell-149    146     Primary    BASE
3923 146_M_HISC_CTRL_1_SEACell-118    146     Metastatic HISC
3924 125_P_HISC_ZFPKD_2_SEACell-81    125     Primary    HISC
3925 146_P_BASE_ZFPKD_2_SEACell-63    146     Primary    BASE
3926 146_P_BASE_CTRL_1_SEACell-204    146     Primary    BASE
3927 125_P_HISC_CTRL_1_SEACell-189    125     Primary    HISC
3928 146_M_Dediff_CTRL_1_SEACell-33   146     Metastatic Dedifferentiated
3929 125_P_HISC_ZFPKD_2_SEACell-116   125     Primary    HISC
3930 146_P_BASE_ZFPKD_2_SEACell-56    146     Primary    BASE
3931 125_P_BASE_CTRL_1_SEACell-31     125     Primary    BASE
3932 146_P_BASE_CTRL_1_SEACell-88     146     Primary    BASE
3933 125_P_HISC_ZFPKD_1_SEACell-130   125     Primary    HISC
3934 125_P_HISC_CTRL_1_SEACell-278    125     Primary    HISC
     ZFP_Expression Sample_Name          Batch
1    ZFPKD          146_P_BASE_ZFPKD_2   5
2    ZFPKD          146_P_BASE_ZFPKD_1   5
3    ZFPKD          146_P_HISC_ZFPKD_2   6
4    ZFPKD          125_P_BASE_ZFPKD_2   0
5    ZFPKD          146_M_Dediff_ZFPKD_2 4
6    ZFPKD          146_P_HISC_ZFPKD_1   6
7    ZFPKD          125_P_HISC_ZFPKD_2   1
8    CTRL           146_P_HISC_CTRL_1    6
9    CTRL           146_M_Dediff_CTRL_1  4
10   ZFPKD          146_M_HISC_ZFPKD_1   3
11   ZFPKD          146_P_HISC_ZFPKD_2   6
12   CTRL           146_P_HISC_CTRL_1    6
13   ZFPKD          146_M_HISC_ZFPKD_1   3
14   CTRL           125_P_HISC_CTRL_1    1
15   CTRL           146_P_BASE_CTRL_1    5
16   ZFPKD          125_P_BASE_ZFPKD_1   0
17   ZFPKD          125_P_HISC_ZFPKD_1   1
18   CTRL           125_P_HISC_CTRL_1    1
19   CTRL           125_P_HISC_CTRL_1    1
20   CTRL           125_P_BASE_CTRL_1    0
21   ZFPKD          146_M_HISC_ZFPKD_1   3
22   ZFPKD          146_P_HISC_ZFPKD_2   6
23   CTRL           146_M_BASE_CTRL_1    2
24   ZFPKD          146_P_BASE_ZFPKD_1   5
25   CTRL           146_M_Dediff_CTRL_1  4
26   ZFPKD          146_M_BASE_ZFPKD_1   2
27   CTRL           146_M_BASE_CTRL_1    2
28   CTRL           146_P_BASE_CTRL_1    5
29   ZFPKD          125_P_HISC_ZFPKD_1   1
30   CTRL           125_P_HISC_CTRL_1    1
⋮    ⋮              ⋮                    ⋮
3905 ZFPKD          146_P_HISC_ZFPKD_2   6
3906 ZFPKD          146_M_BASE_ZFPKD_2   2
3907 ZFPKD          125_P_BASE_ZFPKD_1   0
3908 ZFPKD          125_P_HISC_ZFPKD_1   1
3909 CTRL           146_M_BASE_CTRL_1    2
3910 ZFPKD          146_P_HISC_ZFPKD_1   6
3911 CTRL           146_M_Dediff_CTRL_1  4
3912 ZFPKD          146_M_BASE_ZFPKD_1   2
3913 ZFPKD          146_M_Dediff_ZFPKD_2 4
3914 ZFPKD          125_P_BASE_ZFPKD_1   0
3915 ZFPKD          125_P_HISC_ZFPKD_2   1
3916 CTRL           146_M_BASE_CTRL_1    2
3917 ZFPKD          146_P_HISC_ZFPKD_2   6
3918 ZFPKD          146_P_HISC_ZFPKD_2   6
3919 ZFPKD          146_P_HISC_ZFPKD_2   6
3920 ZFPKD          146_P_BASE_ZFPKD_1   5
3921 ZFPKD          146_M_BASE_ZFPKD_2   2
3922 CTRL           146_P_BASE_CTRL_1    5
3923 CTRL           146_M_HISC_CTRL_1    3
3924 ZFPKD          125_P_HISC_ZFPKD_2   1
3925 ZFPKD          146_P_BASE_ZFPKD_2   5
3926 CTRL           146_P_BASE_CTRL_1    5
3927 CTRL           125_P_HISC_CTRL_1    1
3928 CTRL           146_M_Dediff_CTRL_1  4
3929 ZFPKD          125_P_HISC_ZFPKD_2   1
3930 ZFPKD          146_P_BASE_ZFPKD_2   5
3931 CTRL           125_P_BASE_CTRL_1    0
3932 CTRL           146_P_BASE_CTRL_1    5
3933 ZFPKD          125_P_HISC_ZFPKD_1   1
3934 CTRL           125_P_HISC_CTRL_1    1

In [4]:
# Define the column data
coldata <- adata_obs[,c("Tumor_Site","Culture_Media", "ZFP_Expression", "Batch", "Patient")]

# Convert column data to factors
coldata$Tumor_Site <- factor(coldata$Tumor_Site)
coldata$Culture_Media <- factor(coldata$Culture_Media)
coldata$ZFP_Expression <- factor(coldata$ZFP_Expression)
coldata$Batch <- factor(coldata$Batch)
coldata$Patient <- factor(coldata$Patient)

In [28]:
coldata

     Tumor_Site Culture_Media    ZFP_Expression Batch Patient
1    Primary    BASE             ZFPKD          5     146
2    Primary    BASE             ZFPKD          5     146
3    Primary    HISC             ZFPKD          6     146
4    Primary    BASE             ZFPKD          0     125
5    Metastatic Dedifferentiated ZFPKD          4     146
6    Primary    HISC             ZFPKD          6     146
7    Primary    HISC             ZFPKD          1     125
8    Primary    HISC             CTRL           6     146
9    Metastatic Dedifferentiated CTRL           4     146
10   Metastatic HISC             ZFPKD          3     146
11   Primary    HISC             ZFPKD          6     146
12   Primary    HISC             CTRL           6     146
13   Metastatic HISC             ZFPKD          3     146
14   Primary    HISC             CTRL           1     125
15   Primary    BASE             CTRL           5     146
16   Primary    BASE             ZFPKD          0     125
17   Primary    HISC             ZFPKD          1     125
18   Primary    HISC             CTRL           1     125
19   Primary    HISC             CTRL           1     125
20   Primary    BASE             CTRL           0     125
21   Metastatic HISC             ZFPKD          3     146
22   Primary    HISC             ZFPKD          6     146
23   Metastatic BASE             CTRL           2     146
24   Primary    BASE             ZFPKD          5     146
25   Metastatic Dedifferentiated CTRL           4     146
26   Metastatic BASE             ZFPKD          2     146
27   Metastatic BASE             CTRL           2     146
28   Primary    BASE             CTRL           5     146
29   Primary    HISC             ZFPKD          1     125
30   Primary    HISC             CTRL           1     125
⋮    ⋮          ⋮                ⋮              ⋮     ⋮
3905 Primary    HISC             ZFPKD          6     146
3906 Metastatic BASE             ZFPKD          2     146
3907 Primary    BASE             ZFPKD          0     125
3908 Primary    HISC             ZFPKD          1     125
3909 Metastatic BASE             CTRL           2     146
3910 Primary    HISC             ZFPKD          6     146
3911 Metastatic Dedifferentiated CTRL           4     146
3912 Metastatic BASE             ZFPKD          2     146
3913 Metastatic Dedifferentiated ZFPKD          4     146
3914 Primary    BASE             ZFPKD          0     125
3915 Primary    HISC             ZFPKD          1     125
3916 Metastatic BASE             CTRL           2     146
3917 Primary    HISC             ZFPKD          6     146
3918 Primary    HISC             ZFPKD          6     146
3919 Primary    HISC             ZFPKD          6     146
3920 Primary    BASE             ZFPKD          5     146
3921 Metastatic BASE             ZFPKD          2     146
3922 Primary    BASE             CTRL           5     146
3923 Metastatic HISC             CTRL           3     146
3924 Primary    HISC             ZFPKD          1     125
3925 Primary    BASE             ZFPKD          5     146
3926 Primary    BASE             CTRL           5     146
3927 Primary    HISC             CTRL           1     125
3928 Metastatic Dedifferentiated CTRL           4     146
3929 Primary    HISC             ZFPKD          1     125
3930 Primary    BASE             ZFPKD          5     146
3931 Primary    BASE             CTRL           0     125
3932 Primary    BASE             CTRL           5     146
3933 Primary    HISC             ZFPKD          1     125
3934 Primary    HISC             CTRL           1     125

In [15]:
# Design a DESeqDataSet
dds_1 <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = coldata,
  design = ~ Tumor_Site + Culture_Media + Patient + ZFP_Expression 
)

ERROR: Error in validObject(.Object): invalid class “SummarizedExperiment” object:
    nb of cols in 'assay' (1) must equal nb of rows in 'colData' (3934)

In [23]:
n_cols_count_matrix <- ncol(count_matrix)
n_rows_coldata <- nrow(coldata)
n_cols_count_matrix
n_rows_coldata

NULL

[1] 3934

In [9]:
count_matrix <- as.numeric(count_matrix)

Warning message in eval(expr, envir, enclos):
“NAs introduced by coercion”

In [10]:
count_matrix[is.na(count_matrix)] <- 0

In [24]:
count_matrix

    [1] 0.0000000 0.0000000 0.0000000 3.9189490 0.0000000 0.0000000 0.0000000
    [8] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 2.2088860 3.3650782
   [15] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.5468200 2.5551500
   [22] 1.9122210 3.5085434 2.8352743 0.0000000 1.7911654 0.0000000 1.7278738
   [29] 1.7238803 2.4608328 2.8550525 2.2983221 0.0000000 0.0000000 2.7348941
   [36] 1.3177506 0.0000000 1.6161941 1.2897533 0.5202484 0.0000000 0.0000000
   [43] 0.0000000 0.0000000 0.0000000 0.8710784 0.0000000 0.0000000 0.0000000
   [50] 0.5903806 0.0000000 4.1736050 1.2646054 0.0000000 0.0000000 0.0000000
   [57] 1.2440402 3.3879601 0.5903806 0.7349010 3.0839222 0.6502195 0.0000000
   [64] 0.0000000 0.0000000 3.5249265 3.0606642 0.4013477 0.0000000 0.5060770
   [71] 0.0000000 0.0000000 0.4911091 0.0000000 3.4177450 1.8550140 3.4026423
   [78] 3.9282412 1.5578398 0.9395450 0.0000000 0.0000000 0.0000000 0.0000000
   [85] 0.0000000 0.0000000 2.7961010 1.4972641 2.1501709 1.9740594 0.7248106
   [92] 1.4566252 2.3123743 0.9472861 0.9999234 2.7569339 0.0000000 2.3780605
   [99] 3.0569211 3.6863280 2.2511633 2.4743567 2.7455170 1.9439339 0.8701505
  [106] 0.9880736 1.1647162 3.4248902 2.8670016 0.0000000 0.0000000 1.5111898
  [113] 3.6911776 3.0998871 3.8915180 0.0000000 0.0000000 2.7510612 2.3797084
  [120] 0.0000000 4.0026072 1.9724794 2.3626785 2.4428711 0.0000000 1.0165121
  [127] 0.0000000 0.0000000 0.0000000 0.5060770 0.4734145 0.5311426 0.0000000
  [134] 0.2925713 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [141] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [148] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [155] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [162] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [169] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [176] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [183] 0.0000000 0.0000000 0.0000000 0.0000000 1.3328917 0.0000000 0.0000000
  [190] 0.0000000 0.0000000 1.4660858 0.0000000 0.0000000 0.4013477 0.5903806
  [197] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [204] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [211] 0.0000000 0.5202484 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [218] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [225] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [232] 0.0000000 0.0000000 0.0000000 0.5640964 0.0000000 0.0000000 0.0000000
  [239] 0.0000000 0.0000000 0.0000000 0.5094471 0.0000000 0.0000000 0.0000000
  [246] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [253] 1.9803119 0.0000000 0.0000000 1.7584428 0.0000000 0.0000000 0.0000000
  [260] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [267] 0.9124953 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [274] 0.0000000 0.0000000 0.0000000 0.7965751 0.0000000 0.0000000 0.0000000
  [281] 1.2665455 0.5468200 0.7619358 0.0000000 0.0000000 0.0000000 0.0000000
  [288] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.9115346 0.0000000
  [295] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [302] 0.0000000 0.0000000 0.0000000 0.2925713 0.0000000 0.0000000 0.0000000
  [309] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [316] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.4911091 0.0000000
  [323] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [330] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [337] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [344] 0.5094471 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [351] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.5311426 0.0000000
  [358] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.5311426
  [365] 0.0000000 0.0000000 0.0000000 0.9472861 0.0000000 0.0000000 0.0000000
  [372] 0.0000000 0.0000000 0.5255297 1.5736725 0.0000000 0.0000000 0.0000000
  [379] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [386] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [393] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [400] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [407] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [414] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [421] 0.5202484 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [428] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [435] 1.6994774 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [442] 0.0000000 0.6297337 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [449] 0.4911091 0.0000000 0.0000000 0.0000000 0.5903806 0.0000000 0.0000000
  [456] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [463] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 1.1509282
  [470] 0.0000000 0.0000000 0.6086226 0.0000000 0.0000000 0.0000000 0.0000000
  [477] 0.0000000 0.0000000 0.0000000 1.8084888 0.0000000 0.0000000 0.0000000
  [484] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [491] 0.0000000 0.0000000 0.5468200 0.0000000 0.0000000 0.0000000 0.0000000
  [498] 0.0000000 0.5462362 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [505] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [512] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.5468200 0.5060770
  [519] 1.0664059 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [526] 0.0000000 0.0000000 0.0000000 0.0000000 1.1674210 0.0000000 0.0000000
  [533] 0.0000000 0.0000000 0.0000000 0.0000000 1.0160822 0.0000000 0.0000000
  [540] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [547] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [554] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.7883579
  [561] 0.0000000 0.0000000 1.3198568 0.0000000 0.0000000 0.0000000 0.0000000
  [568] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [575] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [582] 0.0000000 0.0000000 0.5468200 0.4013477 0.0000000 0.0000000 0.0000000
  [589] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [596] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.6502195 0.0000000
  [603] 0.4013477 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [610] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 1.8335505
  [617] 0.0000000 1.4149099 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [624] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [631] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [638] 1.1854777 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [645] 0.0000000 0.0000000 0.5060770 0.0000000 0.0000000 0.0000000 0.0000000
  [652] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [659] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [666] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.2925713
  [673] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [680] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.4013477 0.0000000
  [687] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [694] 0.0000000 0.0000000 0.5202484 0.0000000 0.0000000 0.0000000 0.0000000
  [701] 0.0000000 0.0000000 0.0000000 0.4911091 0.0000000 0.0000000 0.0000000
  [708] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [715] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [722] 0.0000000 0.0000000 0.0000000 0.0000000 1.4853370 0.0000000 0.0000000
  [729] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [736] 1.8719122 0.0000000 0.0000000 0.0000000 0.0000000 2.7776837 0.0000000
  [743] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [750] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [757] 0.0000000 0.0000000 0.9969378 0.0000000 0.0000000 0.0000000 0.0000000
  [764] 0.0000000 0.7965751 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [771] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.4911091 0.0000000
  [778] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.9922041
  [785] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.4013477
  [792] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.9002483
  [799] 0.0000000 0.0000000 0.0000000 0.2925713 0.0000000 0.0000000 0.0000000
  [806] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [813] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 1.2734176
  [820] 0.0000000 0.5462362 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [827] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [834] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [841] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [848] 0.0000000 0.0000000 0.0000000 0.9386354 0.0000000 0.0000000 0.0000000
  [855] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 1.3699419
  [862] 0.5311426 0.6125419 0.0000000 0.0000000 1.1026021 0.0000000 0.0000000
  [869] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [876] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [883] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.9338786 0.0000000
  [890] 0.0000000 0.7684347 0.0000000 0.0000000 0.0000000 0.0000000 0.7683178
  [897] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 1.4744263
  [904] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [911] 2.3026449 0.9690889 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [918] 0.0000000 0.5903806 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [925] 0.0000000 0.7463636 1.3899788 0.0000000 0.0000000 0.0000000 0.0000000
  [932] 0.0000000 0.0000000 0.0000000 2.6714469 0.0000000 0.0000000 0.0000000
  [939] 0.0000000 0.0000000 0.0000000 0.9355830 0.0000000 0.4013477 0.0000000
  [946] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 1.1173097
  [953] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [960] 0.6502195 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [967] 0.0000000 0.0000000 0.0000000 2.5519135 0.0000000 0.0000000 0.0000000
  [974] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.9986958 0.0000000
  [981] 0.7248106 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [988] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
  [995] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1002] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1009] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1016] 0.4734145 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1023] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1030] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1037] 0.5202484 0.6429855 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1044] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1051] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1058] 0.0000000 0.5060770 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1065] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1072] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1079] 1.0712749 0.0000000 0.0000000 0.0000000 0.7349010 0.0000000 0.0000000
 [1086] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1093] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.6086226 1.0348868
 [1100] 0.0000000 0.7883579 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1107] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1114] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1121] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1128] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.4911091 0.0000000
 [1135] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1142] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1149] 0.0000000 0.5462362 0.0000000 0.0000000 0.0000000 3.0755063 0.0000000
 [1156] 0.0000000 0.0000000 0.0000000 0.0000000 0.5640964 0.0000000 0.0000000
 [1163] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1170] 0.0000000 0.4013477 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1177] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1184] 0.0000000 0.0000000 0.0000000 0.6581061 0.0000000 0.0000000 0.0000000
 [1191] 0.0000000 0.4013477 0.0000000 0.0000000 0.0000000 0.6502195 0.8254606
 [1198] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1205] 0.0000000 0.0000000 0.9999234 0.0000000 0.5202484 0.0000000 0.0000000
 [1212] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 1.5859926
 [1219] 0.0000000 1.8449727 0.0000000 0.6297337 0.0000000 0.0000000 0.0000000
 [1226] 0.0000000 0.0000000 0.0000000 0.0000000 1.2901551 0.0000000 0.0000000
 [1233] 0.0000000 0.0000000 0.0000000 0.5640964 0.0000000 0.0000000 0.0000000
 [1240] 0.0000000 0.0000000 0.0000000 0.6581061 0.0000000 0.0000000 0.0000000
 [1247] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1254] 0.0000000 0.0000000 0.0000000 0.4734145 0.0000000 0.5640964 0.0000000
 [1261] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.5255297 0.0000000
 [1268] 0.0000000 0.0000000 0.0000000 0.0000000 0.5640964 1.0273528 0.0000000
 [1275] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1282] 0.2925713 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1289] 0.5202484 0.0000000 0.0000000 0.0000000 0.8413164 0.0000000 0.0000000
 [1296] 0.0000000 0.5060770 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1303] 0.0000000 0.0000000 1.1429728 0.2925713 0.0000000 0.0000000 0.0000000
 [1310] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1317] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1324] 0.0000000 0.0000000 0.0000000 0.0000000 0.9655474 0.0000000 0.0000000
 [1331] 0.5060770 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1338] 1.2976022 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1345] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1352] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1359] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1366] 0.0000000 0.0000000 0.0000000 2.6526713 0.0000000 0.2925713 0.5903806
 [1373] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.6297337
 [1380] 0.0000000 0.0000000 0.0000000 0.5468200 0.0000000 0.0000000 0.0000000
 [1387] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1394] 0.0000000 0.8872849 0.0000000 0.0000000 0.0000000 0.5060770 0.0000000
 [1401] 0.0000000 0.0000000 0.0000000 1.7343951 0.0000000 0.0000000 0.0000000
 [1408] 0.0000000 0.0000000 0.0000000 0.0000000 0.5202484 0.0000000 0.0000000
 [1415] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.5640964 0.0000000
 [1422] 0.0000000 0.0000000 0.0000000 0.0000000 1.3325881 0.0000000 0.0000000
 [1429] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1436] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1443] 0.5640964 0.0000000 1.6183678 0.0000000 0.0000000 0.0000000 0.0000000
 [1450] 1.7249653 0.5462362 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1457] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1464] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1471] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1478] 0.0000000 0.0000000 0.0000000 0.0000000 2.5802204 0.0000000 0.0000000
 [1485] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.6429855
 [1492] 0.0000000 0.0000000 0.5255297 0.0000000 0.0000000 0.0000000 0.0000000
 [1499] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 1.2652676 0.0000000
 [1506] 0.0000000 0.0000000 0.4734145 0.0000000 0.0000000 0.0000000 0.0000000
 [1513] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1520] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1527] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.5060770
 [1534] 0.0000000 0.0000000 0.0000000 0.6429855 0.0000000 0.0000000 0.0000000
 [1541] 0.0000000 0.0000000 0.5094471 0.0000000 0.0000000 0.0000000 0.0000000
 [1548] 0.0000000 0.0000000 0.0000000 0.0000000 0.5311426 0.0000000 0.0000000
 [1555] 0.0000000 0.6502195 0.0000000 0.0000000 0.0000000 0.0000000 0.9072331
 [1562] 0.0000000 0.5311426 0.0000000 0.0000000 0.0000000 1.3927447 1.0965461
 [1569] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1576] 0.0000000 1.2135221 0.5311426 0.5462362 0.0000000 0.0000000 0.0000000
 [1583] 0.0000000 0.2925713 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1590] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1597] 0.0000000 0.0000000 0.0000000 0.0000000 0.8869432 0.0000000 0.0000000
 [1604] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.6502195 0.0000000
 [1611] 0.0000000 0.5640964 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1618] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1625] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1632] 0.0000000 0.0000000 0.0000000 0.0000000 0.6086226 0.0000000 0.0000000
 [1639] 0.0000000 0.5468200 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1646] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.5567415
 [1653] 0.4013477 0.9865795 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1660] 0.0000000 0.4911091 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1667] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1674] 0.0000000 0.0000000 0.0000000 0.5202484 0.0000000 0.0000000 0.0000000
 [1681] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.5255297 0.0000000
 [1688] 0.0000000 0.0000000 0.0000000 0.0000000 0.6502195 0.0000000 0.8710784
 [1695] 0.5255297 1.2372324 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1702] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.5462362 0.0000000
 [1709] 0.5094471 0.0000000 0.5202484 0.0000000 0.0000000 0.0000000 0.0000000
 [1716] 0.0000000 0.0000000 0.0000000 0.0000000 0.5255297 0.0000000 0.0000000
 [1723] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1730] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1737] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.5903806
 [1744] 0.5567415 0.0000000 0.0000000 0.6429855 0.0000000 0.0000000 0.0000000
 [1751] 0.0000000 0.0000000 0.0000000 0.0000000 0.6125419 0.0000000 0.0000000
 [1758] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1765] 0.6297337 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1772] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [1779] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.4013477
 [1786] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000

In [8]:
# Read h5ad file
adata <- read_h5ad("/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/metacells_noscvi/adata.post.combined.h5ad")

ERROR: Above error raised while reading key '/layers' of type <class 'h5py._hl.group.Group'> from /.

In [29]:
# Extract count matrix from the raw layer
count_matrix <- adata$raw$X
count_matrix <- t(count_matrix)
count_matrix <- round(count_matrix)

In [30]:
# Define the column data
coldata <- adata$obs[,c("Tumor_Site","Culture_Media", "ZFP_Expression", "Batch", "Patient")]

# Convert column data to factors
coldata$Tumor_Site <- factor(coldata$Tumor_Site)
coldata$Culture_Media <- factor(coldata$Culture_Media)
coldata$ZFP_Expression <- factor(coldata$ZFP_Expression)
coldata$Batch <- factor(coldata$Batch)
coldata$Patient <- factor(coldata$Patient)

In [ ]:
# Design a DESeqDataSet
dds_1 <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = coldata,
  design = ~ Tumor_Site + Culture_Media + Patient + ZFP_Expression 
)

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 14.3 GiB”
converting counts to integer mode

In [ ]:
# Add a pseudo-count of 1 to all counts
count_matrix <- counts(dds_1) + 1

# Specify the row names as the gene names
rownames(count_matrix) <- adata$raw$var_names

In [ ]:
# Set the reference levels
dds_1$Tumor_Site<-relevel(dds_1$Tumor_Site,ref="Primary")
dds_1$Culture_Media<-relevel(dds_1$Culture_Media,ref="BASE")
dds_1$ZFP_Expression<-relevel(dds_1$ZFP_Expression,ref="CTRL")
dds_1$Patient<-relevel(dds_1$Patient,ref="125")

In [ ]:
# Design a DESeqDataSet with modified count matrix
dds_1 <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = coldata,
  design = ~ Tumor_Site + Culture_Media + Patient + ZFP_Expression 
)

In [ ]:
# Perform DESeq analysis
dds_1 <- DESeq(dds_1)

In [21]:
dds_1

class: DESeqDataSet
dim: 32485 3934
metadata(1): version
assays(5): counts mu H cooks originalCounts
rownames(32485): A1BG A1BG-AS1 ... ZYX ZZEF1
rowData names(39): baseMean baseVar ... maxCooks replace
colnames(3934): 146_P_BASE_ZFPKD_2_SEACell-139
  146_P_BASE_ZFPKD_1_SEACell-90 ... 125_P_HISC_ZFPKD_1_SEACell-130
  125_P_HISC_CTRL_1_SEACell-278
colData names(7): Tumor_Site Culture_Media ... sizeFactor replaceable

In [18]:
# Extract results
result_names_1 <- resultsNames(dds_1)
result_names_1

# Specify the contrast and extract results
res_1 <- results(dds_1)
res_1

[1] "Intercept"
[2] "Tumor_Site_Primary_vs_Metastatic"
[3] "Culture_Media_Dedifferentiated_vs_BASE"
[4] "Culture_Media_HISC_vs_BASE"
[5] "Patient_146_vs_125"
[6] "ZFP_Expression_ZFPKD_vs_CTRL"

log2 fold change (MLE): ZFP Expression ZFPKD vs CTRL
Wald test p-value: ZFP Expression ZFPKD vs CTRL
DataFrame with 32485 rows and 6 columns
          baseMean log2FoldChange     lfcSE       stat      pvalue        padj
         <numeric>      <numeric> <numeric>  <numeric>   <numeric>   <numeric>
A1BG       1.02231     0.00211305 0.0479774  0.0440427    0.964870          NA
A1BG-AS1   1.01236     0.00216575 0.0482165  0.0449172    0.964173          NA
A1CF       3.33497    -0.01149037 0.0266570 -0.4310456    0.666435    0.906265
A2M        1.02463    -0.03585165 0.0477423 -0.7509409    0.452688          NA
A2M-AS1    1.02563    -0.03043614 0.0477451 -0.6374714    0.523818          NA
...            ...            ...       ...        ...         ...         ...
ZXDC       3.80565     -0.0227616 0.0247967  -0.917929 3.58656e-01 7.20065e-01
ZYG11A     1.04943     -0.0187291 0.0472598  -0.396300 6.91884e-01          NA
ZYG11B     3.71665     -0.0163685 0.0251284  -0.651394 5.14792e-01 8.31422e-01
ZYX        2.62246     -0.1414233 0.0295128  -4.791931 1.65184e-06 6.69534e-05
ZZEF1      3.12789      0.0279146 0.0275063   1.014843 3.10181e-01 6.74684e-01

In [19]:
# Specify the file path where you want to save the results
result_file <- "/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/deseq/zfpexp_results.csv"

# Write the results table to a CSV file
write.csv(as.data.frame(res_1), file = result_file)

# Save the DESeqDataSet object
saveRDS(dds_1, file = "/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/deseq/zfpexp_dds.rds")

# Save the DESeq results
saveRDS(results(dds_1), file = "/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/deseq/zfpexp_results.rds")

In [20]:
# Assuming 'condition' is the factor variable
levels(dds_1$Tumor_Site)

[1] "Metastatic" "Primary"

In [23]:
# Define significant genes based on the value of padj and log2FoldChange
res_1$Significant = res_1$padj < 0.05 & abs(res_1$log2FoldChange) > log2(1.5)

# Filter out non-significant genes
significant_genes_df_1 = res_1[res_1$Significant, ]
significant_genes_df_1 <- significant_genes_df_1[complete.cases(significant_genes_df_1$padj), ]
significant_genes_df_1 <- na.omit(significant_genes_df_1)
significant_genes_df_1

log2 fold change (MLE): ZFP Expression ZFPKD vs CTRL
Wald test p-value: ZFP Expression ZFPKD vs CTRL
DataFrame with 6 rows and 7 columns
           baseMean log2FoldChange     lfcSE      stat       pvalue
          <numeric>      <numeric> <numeric> <numeric>    <numeric>
BEX5        1.64228       0.631837 0.0411797   15.3434  3.92197e-53
CADM2       1.29225      -0.649848 0.0408105  -15.9236  4.34826e-57
DANT2       1.66196       0.609677 0.0407152   14.9742  1.08267e-50
H19         3.05664       0.743351 0.0307511   24.1732 4.26124e-129
MEIOB       1.33242      -0.799260 0.0400116  -19.9757  8.95878e-89
MIR548XHG   1.82762       0.821233 0.0401998   20.4288  9.27420e-93
                  padj Significant
             <numeric>   <logical>
BEX5       8.20673e-50        TRUE
CADM2      1.03986e-53        TRUE
DANT2      1.76669e-47        TRUE
H19       7.13332e-125        TRUE
MEIOB      4.99900e-85        TRUE
MIR548XHG  7.76250e-89        TRUE

In [24]:
res_1['ZFP36L2',]

log2 fold change (MLE): ZFP Expression ZFPKD vs CTRL
Wald test p-value: ZFP Expression ZFPKD vs CTRL
DataFrame with 1 row and 7 columns
         baseMean log2FoldChange     lfcSE      stat      pvalue        padj
        <numeric>      <numeric> <numeric> <numeric>   <numeric>   <numeric>
ZFP36L2   4.49937      -0.285815  0.022302  -12.8157 1.33985e-37 1.31936e-34
        Significant
          <logical>
ZFP36L2       FALSE

In [1]:
# Install the R anndata package
install.packages("anndata")

# Run this only if you do not already have an installation of miniconda
#reticulate::install_miniconda(force = TRUE)
#install.packages("reticulate")

# Install the Python anndata package
#anndata::install_anndata()

In [13]:
#install.packages("reticulate")

In [1]:
#Sys.setenv(PATH = paste("lila/home/forsythb/anaconda3/envs/r_4.3.1/bin", Sys.getenv("PATH"), sep = ":"))

In [3]:
#library(reticulate)
#use_python("lila/home/forsythb/anaconda3/envs/r_4.3.1/bin/python")

In [2]:
# Load libraries
library(DESeq2)
library(anndata)

Loading required package: S4Vectors

Loading required package: stats4

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min



Attaching package: ‘S4Vectors’


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges

Loading required package: GenomicRanges

Loading required package: GenomeInfoDb

Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats


Attaching package: ‘MatrixGenerics’


The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘Biobase’


The following object is masked from ‘package:MatrixGenerics’:

    rowMedians


The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians

In [3]:
# Read h5ad file
adata <- read_h5ad("/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/combined/out_post_hvg/adata.combined.hvg_5000.h5ad")

In [4]:
# Extract count matrix from the raw layer
count_matrix <- adata$raw$X
count_matrix <- t(count_matrix)
count_matrix <- round(count_matrix)

In [5]:
# Define the column data
coldata <- adata$obs[,c("Tumor_Site","Culture_Media", "ZFP_Expression", "Batch", "Patient")]

# Convert column data to factors
coldata$Tumor_Site <- factor(coldata$Tumor_Site)
coldata$Culture_Media <- factor(coldata$Culture_Media)
coldata$ZFP_Expression <- factor(coldata$ZFP_Expression)
coldata$Batch <- factor(coldata$Batch)
coldata$Patient <- factor(coldata$Patient)

In [ ]:
# Design a DESeqDataSet
dds_1 <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = coldata,
  design = ~ Tumor_Site + Culture_Media + Patient + ZFP_Expression + ZFP_Expression:Culture_Media
)

# Add a pseudo-count of 1 to all counts
count_matrix <- counts(dds_1) + 1

# Specify the row names as the gene names
rownames(count_matrix) <- adata$raw$var_names

In [ ]:
# Set the reference levels
dds_1$Tumor_Site<-relevel(dds_1$Tumor_Site,ref="Primary")
dds_1$Culture_Media<-relevel(dds_1$Culture_Media,ref="BASE")
dds_1$ZFP_Expression<-relevel(dds_1$ZFP_Expression,ref="CTRL")
dds_1$Patient<-relevel(dds_1$Patient,ref="125")

In [ ]:
# Design a DESeqDataSet with modified count matrix
dds_1 <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = coldata,
  design = ~ Tumor_Site + Culture_Media + Patient + ZFP_Expression + ZFP_Expression:Culture_Media
)

In [ ]:
# Perform DESeq analysis
dds_1 <- DESeq(dds_1)

In [ ]:
# Extract results
result_names_1 <- resultsNames(dds_1)
result_names_1

# Specify the contrast and extract results
res_1 <- results(dds_1)
res_1

In [ ]:
# Specify the file path where you want to save the results
result_file <- "/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/deseq/zfpexp_results.csv"

# Write the results table to a CSV file
write.csv(as.data.frame(res_1), file = result_file)

# Save the DESeqDataSet object
saveRDS(dds_1, file = "/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/deseq/zfpexp_dds.rds")

# Save the DESeq results
saveRDS(results(dds_1), file = "/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/deseq/zfpexp_results.rds")