In [2]:
# Load libraries
library("anndata")
library("DESeq2")
library("reticulate")

In [3]:
# Use the path to your Python executable in the virtual environment
use_python("/lila/home/forsythb/.virtualenvs/r-reticulate/bin/")

# Look at where Python is located
py_config()

# Import scanpy
sc <- import("scanpy")

python:         /lila/home/forsythb/.virtualenvs/r-reticulate/bin/python
libpython:      /home/forsythb/anaconda3/lib/libpython3.8.so
pythonhome:     /lila/home/forsythb/.virtualenvs/r-reticulate:/lila/home/forsythb/.virtualenvs/r-reticulate
version:        3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0]
numpy:          /lila/home/forsythb/.virtualenvs/r-reticulate/lib/python3.8/site-packages/numpy
numpy_version:  1.24.4

NOTE: Python version was forced by use_python() function

In [4]:
# Read h5ad file
adata <- sc$read_h5ad("/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/combined/out_post_hvg/adata.filteredmultiplex.combined.hvg_5000.h5ad")

In [5]:
adata

AnnData object with n_obs × n_vars = 59140 × 32485
    obs: 'background_fraction', 'cell_probability', 'cell_size', 'droplet_efficiency', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'log10GenesPerUMI', 'original_total_counts', 'log10_original_total_counts', 'mito_frac', 'Patient', 'Tumor_Site', 'Culture_Media', 'ZFP_Expression', 'Replicate', 'Batch', 'Sample', 'phenograph'
    var: 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'ribo', 'n_cells', 'highly_variable', 'highly_variable_rank', 'means', 'variances', 'variances_norm', 'highly_variable_nbatches'
    uns: 'hvg', 'log1p', 'neighbors', 'num_components', 'paga', 'phenograph_sizes', 'umap', 'var_explained'
    obsm: 'X_pca', 'X_umap', 'gene_expression_encoding'
    layers: 'counts', 'without_log'
    obsp: 'connectivities', 'distances'

In [6]:
# Extract count matrix from the raw layer
count_matrix <- adata$raw$X
count_matrix <- t(count_matrix)
count_matrix <- round(count_matrix)

In [18]:
dim(count_matrix)

[1] 32485 59140

In [26]:
sum(rowSums(count_matrix>10)<=10)

[1] 32479

In [24]:
rowSums(count_matrix>10)

             A1BG          A1BG-AS1              A1CF               A2M
                0                 0                 0                 0
          A2M-AS1             A2ML1         A2ML1-AS1         A2ML1-AS2
                0                 0                 0                 0
          A3GALT2            A4GALT             A4GNT              AAAS
                0                 0                 0                 0
             AACS             AADAC           AADACL2       AADACL2-AS1
                0                 0                 0                 0
          AADACL3           AADACL4             AADAT             AAGAB
                0                 0                 0                 0
             AAK1             AAMDC              AAMP             AANAT
                0                 0                 0                 0
             AAR2              AARD              AARS             AARS2
                0                 0                 0                 0
           AARSD1             AASDH          AASDHPPT              AASS
                0                 0                 0                 0
            AATBC              AATF              AATK            ABALON
                0                 0                 0                 0
             ABAT             ABCA1            ABCA10            ABCA12
                0                 0                 0                 0
           ABCA13             ABCA2             ABCA3             ABCA4
                0                 0                 0                 0
            ABCA5             ABCA6             ABCA7             ABCA8
                0                 0                 0                 0
            ABCA9         ABCA9-AS1             ABCB1            ABCB10
                0                 0                 0                 0
           ABCB11             ABCB4             ABCB5             ABCB6
                0                 0                 0                 0
            ABCB7             ABCB8             ABCB9             ABCC1
                0                 0                 0                 0
           ABCC10            ABCC11            ABCC12             ABCC2
                0                 0                 0                 0
            ABCC3             ABCC4             ABCC5         ABCC5-AS1
                0                 0                 0                 0
            ABCC6             ABCC8             ABCC9             ABCD1
                0                 0                 0                 0
            ABCD2             ABCD3             ABCD4             ABCE1
                0                 0                 0                 0
            ABCF1             ABCF2             ABCF3             ABCG1
                0                 0                 0                 0
            ABCG2             ABCG4             ABCG5             ABCG8
                0                 0                 0                 0
            ABHD1            ABHD10            ABHD11            ABHD12
                0                 0                 0                 0
          ABHD12B            ABHD13           ABHD14A           ABHD14B
                0                 0                 0                 0
           ABHD15        ABHD15-AS1           ABHD16A           ABHD16B
                0                 0                 0                 0
          ABHD17A           ABHD17B           ABHD17C            ABHD18
                0                 0                 0                 0
            ABHD2             ABHD3             ABHD4             ABHD5
                0                 0                 0                 0
            ABHD6             ABHD8              ABI1              ABI2
                0                 0                 0                 0
             ABI3            ABI3BP           ABITRAM              ABL1
                0                 0                 0                 0
             ABL2            ABLIM1            ABLIM2            ABLIM3
                0                 0                 0                 0
              ABO               ABR              ABRA            ABRACL
                0                 0                 0                 0
         ABRAXAS1          ABRAXAS2              ABT1             ABTB1
                0                 0                 0                 0
            ABTB2        AC000032.1        AC000058.1        AC000061.1
                0                 0                 0                 0
       AC000065.1        AC000065.2        AC000068.1        AC000068.2
                0                 0                 0                 0
       AC000068.3        AC000072.1        AC000082.1        AC000085.1
                0                 0                 0                 0
       AC000099.1        AC000113.1        AC000120.1        AC000123.1
                0                 0                 0                 0
       AC000124.1        AC000403.1        AC001226.1        AC002044.1
                0                 0                 0                 0
       AC002056.2        AC002057.2        AC002059.1        AC002064.1
                0                 0                 0                 0
       AC002064.2        AC002066.1        AC002069.2        AC002070.1
                0                 0                 0                 0
       AC002072.1        AC002074.1        AC002074.2        AC002076.1
                0                 0                 0                 0
       AC002091.1        AC002094.2        AC002094.4        AC002101.1
                0                 0                 0                 0
       AC002115.1        AC002116.2        AC002128.1        AC002128.2
                0                 0                 0                 0
       AC002306.1        AC002310.1        AC002310.2        AC002331.1
                0                 0                 0                 0
       AC002347.1        AC002347.2        AC002351.1        AC002375.1
                0                 0                 0                 0
       AC002377.1        AC002378.1        AC002383.1        AC002386.1
                0                 0                 0                 0
       AC002398.1        AC002398.2        AC002401.1        AC002401.2
                0                 0                 0                 0
       AC002401.3        AC002401.4        AC002407.1        AC002428.1
                0                 0                 0                 0
       AC002428.2        AC002429.2        AC002451.1        AC002454.1
                0                 0                 0                 0
       AC002458.1        AC002460.2        AC002463.1        AC002465.1
                0                 0                 0                 0
       AC002465.2        AC002467.1        AC002470.1        AC002472.1
                0                 0                 0                 0
       AC002480.1        AC002480.2        AC002511.1        AC002511.2
                0                 0                 0                 0
       AC002519.1        AC002529.1        AC002542.6        AC002546.1
                0                 0                 0                 0
       AC002550.1        AC002550.2        AC002551.1        AC002553.1
                0                 0                 0                 0
       AC002553.2        AC002558.2        AC002558.3        AC002563.1
                0                 0                 0                 0
       AC003001.1        AC003005.2        AC003035.1        AC003035.2
                0                 0                 0                 0
       AC003043.1        AC003043.2        AC003044.1        AC003070.1
                0                 0                 0                 0
       AC003070.2        AC003077.1        AC003084.1        AC003086.1
                0                 0                 0                 0
       AC003087.1        AC003092.1        AC003092.2        AC003093.1
                0                 0                 0                 0
       AC003101.1        AC003101.2        AC003102.1        AC003659.1
                0                 0                 0                 0
       AC003666.1        AC003681.1        AC003682.1        AC003684.1
                0                 0                 0                 0
       AC003688.2        AC003950.1        AC003956.1        AC003958.2
                0                 0                 0                 0
       AC003965.1        AC003965.2        AC003973.1        AC003975.1
                0                 0                 0                 0
       AC003982.1        AC003984.1        AC003985.1        AC003986.1
                0                 0                 0                 0
       AC003986.2        AC003986.3        AC003988.1        AC003991.1
                0                 0                 0                 0
       AC003991.2        AC004000.1        AC004009.1        AC004012.1
                0                 0                 0                 0
       AC004014.1        AC004023.1        AC004034.1        AC004039.1
                0                 0                 0                 0
       AC004047.1        AC004052.1        AC004053.1        AC004054.1
                0                 0                 0                 0
       AC004063.1        AC004066.2        AC004067.1        AC004069.1
                0                 0                 0                 0
       AC004076.2        AC004080.1       AC004080.17        AC004080.2
                0                 0                 0                 0
       AC004080.4        AC004083.1        AC004112.1        AC004130.2
                0                 0                 0                 0
       AC004147.2        AC004147.3        AC004147.5        AC004148.1
                0                 0                 0                 0
       AC004156.1        AC004158.1        AC004160.1        AC004217.1
                0                 0                 0                 0
       AC004221.1        AC004223.2        AC004223.4        AC004231.1
                0                 0                 0                 0
       AC004231.3        AC004232.1        AC004233.1        AC004233.2
                0                 0                 0                 0
       AC004233.3        AC004241.1        AC004241.2        AC004241.3
                0                 0                 0                 0
       AC004241.4        AC004253.1        AC004253.2        AC004257.1
                0                 0                 0                 0
       AC004263.1        AC004263.2        AC004264.1        AC004381.1
                0                 0                 0                 0
       AC004448.2        AC004449.1        AC004461.2        AC004464.1
                0                 0                 0                 0
       AC004466.1        AC004466.2        AC004466.3        AC004470.1
                0                 0                 0                 0
       AC004471.1        AC004471.2        AC004477.1        AC004477.2
                0                 0                 0                 0
       AC004477.3        AC004485.1        AC004490.1        AC004492.1
                0                 0                 0                 0
       AC004494.1        AC004522.3        AC004522.4        AC004522.5
                0                 0                 0                 0
       AC004528.1        AC004528.2        AC004540.1        AC004540.2
                0                 0                 0                 0
       AC004542.1        AC004542.2        AC004543.1        AC004549.1
                0                 0                 0                 0
       AC004551.1        AC004554.2        AC004556.3        AC004584.1
                0                 0                 0                 0
       AC004584.3        AC004585.1        AC004590.1        AC004593.1
                0                 0                 0                 0
       AC004593.2        AC004593.3        AC004594.1        AC004596.1
                0                 0                 0                 0
       AC004597.1        AC004672.1        AC004672.2        AC004674.1
                0                 0                 0                 0
       AC004687.1        AC004687.3        AC004690.2        AC004691.1
                0                 0                 0                 0
       AC004692.2        AC004702.1        AC004704.1        AC004706.1
                0                 0                 0                 0
       AC004706.3        AC004707.1        AC004765.1        AC004771.1
                0                 0                 0                 0
       AC004771.2        AC004771.3        AC004771.4        AC004771.5
                0                 0                 0                 0
       AC004775.1        AC004784.1        AC004797.1        AC004801.3
                0                 0                 0                 0
       AC004801.4        AC004801.5        AC004801.6        AC004803.1
                0                 0                 0                 0
       AC004812.2        AC004816.1        AC004816.2        AC004817.1
                0                 0                 0                 0
       AC004817.3        AC004817.4        AC004817.5        AC004825.2
                0                 0                 0                 0
       AC004825.3        AC004828.1        AC004828.2        AC004830.2
                0                 0                 0                 0
       AC004832.1        AC004832.4        AC004832.5        AC004832.6
                0                 0                 0                 0
       AC004834.1        AC004835.1        AC004837.2        AC004837.3
                0                 0                 0                 0
       AC004837.4        AC004839.2        AC004846.1        AC004846.2
                0                 0                 0                 0
       AC004847.1        AC004852.2        AC004854.2        AC004862.1
                0                 0                 0                 0
       AC004863.1        AC004865.2        AC004869.1        AC004870.2
                0                 0                 0                 0
       AC004870.3        AC004870.4        AC004875.1        AC004877.1
                0                 0                 0                 0
       AC004879.1        AC004882.1        AC004882.3        AC004884.2
                0                 0                 0                 0
       AC004888.1        AC004889.1        AC004893.3        AC004895.1
                0                 0                 0                 0
       AC004900.1        AC004906.1        AC004908.1        AC004908.2
                0                 0                 0                 0
       AC004908.3        AC004917.1        AC004918.1        AC004918.4
                0                 0                 0                 0
       AC004920.1        AC004921.1        AC004921.2        AC004923.4
                0                 0                 0                 0
       AC004930.1        AC004936.1        AC004938.2        AC004941.1
                0                 0                 0                 0
       AC004943.1        AC004943.2        AC004943.3        AC004946.1
                0                 0                 0                 0
       AC004946.2        AC004947.1        AC004947.3        AC004948.1
                0                 0                 0                 0
       AC004949.1        AC004951.1        AC004969.1        AC004973.1
                0                 0                 0                 0
       AC004974.1        AC004975.2        AC004982.1        AC004982.2
                0                 0                 0                 0
       AC004988.1        AC004990.1        AC005005.3        AC005005.4
                0                 0                 0                 0
       AC005006.1        AC005008.2        AC005009.1        AC005009.2
                0                 0                 0                 0
       AC005013.1        AC005014.2        AC005014.3        AC005014.4
                0                 0                 0                 0
       AC005019.2        AC005021.1        AC005034.2        AC005034.3
                0                 0                 0                 0
       AC005034.4        AC005034.5        AC005034.6        AC005037.1
                0                 0                 0                 0
       AC005040.2        AC005041.3        AC005041.4        AC005041.5
                0                 0                 0                 0
       AC005042.2        AC005046.1        AC005050.1        AC005050.2
                0                 0                 0                 0
       AC005050.3        AC005052.2        AC005062.1        AC005064.1
                0                 0                 0                 0
       AC005070.3        AC005071.1        AC005072.1        AC005076.1
                0                 0                 0                 0
       AC005081.1        AC005082.1        AC005082.2        AC005083.1
                0                 0                 0                 0
       AC005086.2        AC005089.1        AC005090.1        AC005091.1
                0                 0                 0                 0
       AC005096.1        AC005100.1        AC005100.2        AC005104.1
                0                 0                 0                 0
       AC005104.3        AC005144.1        AC005153.1        AC005154.3
                0                 0                 0                 0
       AC005154.4        AC005162.1        AC005162.2        AC005162.3
                0                 0                 0                 0
       AC005165.1        AC005165.3        AC005180.1        AC005180.2
                0                 0                 0                 0
       AC005197.1        AC005208.1        AC005209.1        AC005220.1
                0                 0                 0                 0
       AC005224.2        AC005224.3        AC005225.1        AC005225.2
                0                 0                 0                 0
       AC005225.3        AC005229.4        AC005229.5        AC005234.1
                0                 0                 0                 0
       AC005234.2        AC005237.1        AC005244.2        AC005252.4
                0                 0                 0                 0
       AC005253.1        AC005253.2        AC005256.1        AC005258.2
                0                 0                 0                 0
       AC005261.1        AC005261.2        AC005261.3        AC005262.2
                0                 0                 0                 0
       AC005264.1        AC005277.1        AC005277.2        AC005280.1
                0                 0                 0                 0
       AC005280.2        AC005281.1        AC005288.1        AC005291.1
                0                 0                 0                 0
       AC005291.2        AC005293.1        AC005301.2        AC005303.1
                0                 0                 0                 0
       AC005304.1        AC005304.2        AC005304.3        AC005306.1
                0                 0                 0                 0
       AC005307.1        AC005323.1        AC005323.2        AC005324.5
                0                 0                 0                 0
       AC005329.1        AC005329.2        AC005329.3        AC005330.1

In [8]:
# Define the column data
coldata <- adata$obs[,c("Tumor_Site","Culture_Media", "ZFP_Expression", "Batch", "Patient")]

# Convert column data to factors
coldata$Tumor_Site <- factor(coldata$Tumor_Site)
coldata$Culture_Media <- factor(coldata$Culture_Media)
coldata$ZFP_Expression <- factor(coldata$ZFP_Expression)
coldata$Batch <- factor(coldata$Batch)
coldata$Patient <- factor(coldata$Patient)

In [9]:
coldata

                                                       Tumor_Site
146P_BASE_shZFP36L2_3_TTAGGGTCAGTAACGG-1               Primary
KG146Li_BASE_shZFP36L2_4_CGTTAGACACGTAACT-1            Metastatic
146P_BASE_shCTRL_AGGTGTTCATACAGGG-1                    Primary
146P_BASE_shZFP36L2_4_CCTCTAGGTCGCATTA-1               Primary
125P_HISC_shZFP36L2_3_GTTGTCCTCCACTGGG-1               Primary
146P_BASE_shZFP36L2_4_CTGTAGACACTCAAGT-1               Primary
KG146Li_BASE_shCtrl_TTGTTCACAGGAGACT-1                 Metastatic
KG146Li_BASE_shZFP36L2_3_TCTTGCGAGCATGATA-1            Metastatic
KG146Li_BASE_shZFP36L2_4_TACTTACAGAGTCCGA-1            Metastatic
KG146Li_BASE_shZFP36L2_3_GCACATAGTAGTTCCA-1            Metastatic
125P_BASE_shCTRL_TTCGATTGTGTTTCTT-1                    Primary
146P_HISC_shZFP36L2_3_TTACCGCGTTAAACAG-1               Primary
146P_HISC_shZFP36L2_4_CCGTGAGAGAACTCCT-1               Primary
125P_HISC_shZFP36L2_4_GTGGCGTGTGCTATTG-1               Primary
125P_HISC_shZFP36L2_4_CAGCGTGCAAGTCGTT-1               Primary
146P_HISC_shCTRL_ACAGCCGAGACCAACG-1                    Primary
125P_HISC_shZFP36L2_4_CTCTCAGGTACGTGAG-1               Primary
146P_HISC_shZFP36L2_4_AAGGAATGTGGGCTCT-1               Primary
125P_HISC_shZFP36L2_4_GCGAGAAAGGTCCTGC-1               Primary
KG146Li_HISC_shZFP36L2_3_AGGACTTAGGGATCGT-1            Metastatic
KG146Li_BASE_shZFP36L2_4_CGTGCTTAGTTTGAGA-1            Metastatic
KG146Li_HISC_shCtrl_GTGCGTGTCGAGGCAA-1                 Metastatic
146P_HISC_shCTRL_AATAGAGCACGCGGTT-1                    Primary
KG146Li_HISC_shZFP36L2_3_GCATCTCAGTGGACGT-1            Metastatic
125P_HISC_shCTRL_GTGCTTCAGCCATTGT-1                    Primary
KG146Li_BASE_shZFP36L2_3_GCGTGCAAGAGTCAAT-1            Metastatic
146P_BASE_shZFP36L2_3_GGTAGAGTCCTTGAAG-1               Primary
125P_HISC_shZFP36L2_4_TCGTGGGTCAGCGGAA-1               Primary
KG146Li_BASE_shZFP36L2_3_GAGGGTAAGTGCACAG-1            Metastatic
146P_BASE_shZFP36L2_3_GCACGGTCACTACAGT-1               Primary
⋮                                                      ⋮
125P_BASE_shCTRL_CTGAATGTCAAACGTC-1                    Primary
146P_BASE_shCTRL_GTTACCCTCCAATCCC-1                    Primary
146P_HISC_shZFP36L2_4_GTTAGACGTAGTAAGT-1               Primary
146P_BASE_shCTRL_CTAACCCGTGGAACCA-1                    Primary
125P_HISC_shZFP36L2_3_GATTCTTAGCACGATG-1               Primary
KG146Li_BASE_shCtrl_AGTACCAAGGGAGTGG-1                 Metastatic
146Li_dedifferentiation_shZFP36L2_4_AACCCAATCCAGCCTT-1 Metastatic
KG146Li_HISC_shCtrl_CATGGTACATAGCACT-1                 Metastatic
KG146Li_BASE_shCtrl_TGTAACGTCCATTTAC-1                 Metastatic
146P_HISC_shZFP36L2_3_AGGAATAGTGCTGCAC-1               Primary
146Li_dedifferentiation_shCtrl_CATGCAAAGCCTTTGA-1      Metastatic
146P_BASE_shCTRL_AGAGCCCGTCGGATTT-1                    Primary
146P_BASE_shCTRL_CACTTCGAGTCTGTAC-1                    Primary
KG146Li_BASE_shZFP36L2_4_CAAAGAAGTCATGGCC-1            Metastatic
125P_HISC_shCTRL_TCCGTGTGTTTCAGAC-1                    Primary
146Li_dedifferentiation_shZFP36L2_4_TCTACCGCATAAGCAA-1 Metastatic
125P_BASE_shCTRL_TCGACGGTCCGCGGAT-1                    Primary
146P_BASE_shZFP36L2_3_GTAGTACAGGCCCACT-1               Primary
KG146Li_HISC_shCtrl_TCTTAGTGTTAAGTCC-1                 Metastatic
146P_HISC_shCTRL_AGGACGAGTAATGATG-1                    Primary
146P_BASE_shZFP36L2_4_TTTGGTTTCGAAGCAG-1               Primary
125P_HISC_shZFP36L2_4_TACTTGTCAAGATGGC-1               Primary
146Li_dedifferentiation_shZFP36L2_4_GCAACATTCTTCTCAA-1 Metastatic
146P_HISC_shZFP36L2_4_ATGAGGGGTCACTGAT-1               Primary
125P_HISC_shCTRL_CGGACACCACAAAGTA-1                    Primary
125P_HISC_shZFP36L2_4_TTCGGTCTCCGTTGGG-1               Primary
146P_HISC_shZFP36L2_4_ACAAAGATCATCACTT-1               Primary
146P_BASE_shZFP36L2_3_TCAGGTAAGTTTAGGA-1               Primary
146P_HISC_shZFP36L2_3_TCATCATAGATCGGTG-1               Primary
125P_HISC_shZFP36L2_4_TCATCATCAGGTACGA-1               Primary
                                                       Culture_Media
146P_BASE_shZFP36L2_3_TTAGGGTCAGTAACGG-1               BASE
KG146Li_BASE_shZFP36L2_4_CGTTAGACACGTAACT-1            BASE
146P_BASE_shCTRL_AGGTGTTCATACAGGG-1                    BASE
146P_BASE_shZFP36L2_4_CCTCTAGGTCGCATTA-1               BASE
125P_HISC_shZFP36L2_3_GTTGTCCTCCACTGGG-1               HISC
146P_BASE_shZFP36L2_4_CTGTAGACACTCAAGT-1               BASE
KG146Li_BASE_shCtrl_TTGTTCACAGGAGACT-1                 BASE
KG146Li_BASE_shZFP36L2_3_TCTTGCGAGCATGATA-1            BASE
KG146Li_BASE_shZFP36L2_4_TACTTACAGAGTCCGA-1            BASE
KG146Li_BASE_shZFP36L2_3_GCACATAGTAGTTCCA-1            BASE
125P_BASE_shCTRL_TTCGATTGTGTTTCTT-1                    BASE
146P_HISC_shZFP36L2_3_TTACCGCGTTAAACAG-1               HISC
146P_HISC_shZFP36L2_4_CCGTGAGAGAACTCCT-1               HISC
125P_HISC_shZFP36L2_4_GTGGCGTGTGCTATTG-1               HISC
125P_HISC_shZFP36L2_4_CAGCGTGCAAGTCGTT-1               HISC
146P_HISC_shCTRL_ACAGCCGAGACCAACG-1                    HISC
125P_HISC_shZFP36L2_4_CTCTCAGGTACGTGAG-1               HISC
146P_HISC_shZFP36L2_4_AAGGAATGTGGGCTCT-1               HISC
125P_HISC_shZFP36L2_4_GCGAGAAAGGTCCTGC-1               HISC
KG146Li_HISC_shZFP36L2_3_AGGACTTAGGGATCGT-1            HISC
KG146Li_BASE_shZFP36L2_4_CGTGCTTAGTTTGAGA-1            BASE
KG146Li_HISC_shCtrl_GTGCGTGTCGAGGCAA-1                 HISC
146P_HISC_shCTRL_AATAGAGCACGCGGTT-1                    HISC
KG146Li_HISC_shZFP36L2_3_GCATCTCAGTGGACGT-1            HISC
125P_HISC_shCTRL_GTGCTTCAGCCATTGT-1                    HISC
KG146Li_BASE_shZFP36L2_3_GCGTGCAAGAGTCAAT-1            BASE
146P_BASE_shZFP36L2_3_GGTAGAGTCCTTGAAG-1               BASE
125P_HISC_shZFP36L2_4_TCGTGGGTCAGCGGAA-1               HISC
KG146Li_BASE_shZFP36L2_3_GAGGGTAAGTGCACAG-1            BASE
146P_BASE_shZFP36L2_3_GCACGGTCACTACAGT-1               BASE
⋮                                                      ⋮
125P_BASE_shCTRL_CTGAATGTCAAACGTC-1                    BASE
146P_BASE_shCTRL_GTTACCCTCCAATCCC-1                    BASE
146P_HISC_shZFP36L2_4_GTTAGACGTAGTAAGT-1               HISC
146P_BASE_shCTRL_CTAACCCGTGGAACCA-1                    BASE
125P_HISC_shZFP36L2_3_GATTCTTAGCACGATG-1               HISC
KG146Li_BASE_shCtrl_AGTACCAAGGGAGTGG-1                 BASE
146Li_dedifferentiation_shZFP36L2_4_AACCCAATCCAGCCTT-1 Dedifferentiated
KG146Li_HISC_shCtrl_CATGGTACATAGCACT-1                 HISC
KG146Li_BASE_shCtrl_TGTAACGTCCATTTAC-1                 BASE
146P_HISC_shZFP36L2_3_AGGAATAGTGCTGCAC-1               HISC
146Li_dedifferentiation_shCtrl_CATGCAAAGCCTTTGA-1      Dedifferentiated
146P_BASE_shCTRL_AGAGCCCGTCGGATTT-1                    BASE
146P_BASE_shCTRL_CACTTCGAGTCTGTAC-1                    BASE
KG146Li_BASE_shZFP36L2_4_CAAAGAAGTCATGGCC-1            BASE
125P_HISC_shCTRL_TCCGTGTGTTTCAGAC-1                    HISC
146Li_dedifferentiation_shZFP36L2_4_TCTACCGCATAAGCAA-1 Dedifferentiated
125P_BASE_shCTRL_TCGACGGTCCGCGGAT-1                    BASE
146P_BASE_shZFP36L2_3_GTAGTACAGGCCCACT-1               BASE
KG146Li_HISC_shCtrl_TCTTAGTGTTAAGTCC-1                 HISC
146P_HISC_shCTRL_AGGACGAGTAATGATG-1                    HISC
146P_BASE_shZFP36L2_4_TTTGGTTTCGAAGCAG-1               BASE
125P_HISC_shZFP36L2_4_TACTTGTCAAGATGGC-1               HISC
146Li_dedifferentiation_shZFP36L2_4_GCAACATTCTTCTCAA-1 Dedifferentiated
146P_HISC_shZFP36L2_4_ATGAGGGGTCACTGAT-1               HISC
125P_HISC_shCTRL_CGGACACCACAAAGTA-1                    HISC
125P_HISC_shZFP36L2_4_TTCGGTCTCCGTTGGG-1               HISC
146P_HISC_shZFP36L2_4_ACAAAGATCATCACTT-1               HISC
146P_BASE_shZFP36L2_3_TCAGGTAAGTTTAGGA-1               BASE
146P_HISC_shZFP36L2_3_TCATCATAGATCGGTG-1               HISC
125P_HISC_shZFP36L2_4_TCATCATCAGGTACGA-1               HISC
                                                       ZFP_Expression Batch
146P_BASE_shZFP36L2_3_TTAGGGTCAGTAACGG-1               ZFP_KD         5
KG146Li_BASE_shZFP36L2_4_CGTTAGACACGTAACT-1            ZFP_KD         2
146P_BASE_shCTRL_AGGTGTTCATACAGGG-1                    CTRL           5
146P_BASE_shZFP36L2_4_CCTCTAGGTCGCATTA-1               ZFP_KD         5
125P_HISC_shZFP36L2_3_GTTGTCCTCCACTGGG-1               ZFP_KD         1
146P_BASE_shZFP36L2_4_CTGTAGACACTCAAGT-1               ZFP_KD         5
KG146Li_BASE_shCtrl_TTGTTCACAGGAGACT-1                 CTRL           2
KG146Li_BASE_shZFP36L2_3_TCTTGCGAGCATGATA-1            ZFP_KD         2
KG146Li_BASE_shZFP36L2_4_TACTTACAGAGTCCGA-1            ZFP_KD         2
KG146Li_BASE_shZFP36L2_3_GCACATAGTAGTTCCA-1            ZFP_KD         2
125P_BASE_shCTRL_TTCGATTGTGTTTCTT-1                    CTRL           0
146P_HISC_shZFP36L2_3_TTACCGCGTTAAACAG-1               ZFP_KD         6
146P_HISC_shZFP36L2_4_CCGTGAGAGAACTCCT-1               ZFP_KD         6
125P_HISC_shZFP36L2_4_GTGGCGTGTGCTATTG-1               ZFP_KD         1
125P_HISC_shZFP36L2_4_CAGCGTGCAAGTCGTT-1               ZFP_KD         1
146P_HISC_shCTRL_ACAGCCGAGACCAACG-1                    CTRL           6
125P_HISC_shZFP36L2_4_CTCTCAGGTACGTGAG-1               ZFP_KD         1
146P_HISC_shZFP36L2_4_AAGGAATGTGGGCTCT-1               ZFP_KD         6
125P_HISC_shZFP36L2_4_GCGAGAAAGGTCCTGC-1               ZFP_KD         1
KG146Li_HISC_shZFP36L2_3_AGGACTTAGGGATCGT-1            ZFP_KD         3
KG146Li_BASE_shZFP36L2_4_CGTGCTTAGTTTGAGA-1            ZFP_KD         2
KG146Li_HISC_shCtrl_GTGCGTGTCGAGGCAA-1                 CTRL           3
146P_HISC_shCTRL_AATAGAGCACGCGGTT-1                    CTRL           6
KG146Li_HISC_shZFP36L2_3_GCATCTCAGTGGACGT-1            ZFP_KD         3
125P_HISC_shCTRL_GTGCTTCAGCCATTGT-1                    CTRL           1
KG146Li_BASE_shZFP36L2_3_GCGTGCAAGAGTCAAT-1            ZFP_KD         2
146P_BASE_shZFP36L2_3_GGTAGAGTCCTTGAAG-1               ZFP_KD         5
125P_HISC_shZFP36L2_4_TCGTGGGTCAGCGGAA-1               ZFP_KD         1
KG146Li_BASE_shZFP36L2_3_GAGGGTAAGTGCACAG-1            ZFP_KD         2
146P_BASE_shZFP36L2_3_GCACGGTCACTACAGT-1               ZFP_KD         5
⋮                                                      ⋮              ⋮
125P_BASE_shCTRL_CTGAATGTCAAACGTC-1                    CTRL           0
146P_BASE_shCTRL_GTTACCCTCCAATCCC-1                    CTRL           5
146P_HISC_shZFP36L2_4_GTTAGACGTAGTAAGT-1               ZFP_KD         6
146P_BASE_shCTRL_CTAACCCGTGGAACCA-1                    CTRL           5
125P_HISC_shZFP36L2_3_GATTCTTAGCACGATG-1               ZFP_KD         1
KG146Li_BASE_shCtrl_AGTACCAAGGGAGTGG-1                 CTRL           2
146Li_dedifferentiation_shZFP36L2_4_AACCCAATCCAGCCTT-1 ZFP_KD         4
KG146Li_HISC_shCtrl_CATGGTACATAGCACT-1                 CTRL           3
KG146Li_BASE_shCtrl_TGTAACGTCCATTTAC-1                 CTRL           2
146P_HISC_shZFP36L2_3_AGGAATAGTGCTGCAC-1               ZFP_KD         6
146Li_dedifferentiation_shCtrl_CATGCAAAGCCTTTGA-1      CTRL           4
146P_BASE_shCTRL_AGAGCCCGTCGGATTT-1                    CTRL           5
146P_BASE_shCTRL_CACTTCGAGTCTGTAC-1                    CTRL           5
KG146Li_BASE_shZFP36L2_4_CAAAGAAGTCATGGCC-1            ZFP_KD         2
125P_HISC_shCTRL_TCCGTGTGTTTCAGAC-1                    CTRL           1
146Li_dedifferentiation_shZFP36L2_4_TCTACCGCATAAGCAA-1 ZFP_KD         4
125P_BASE_shCTRL_TCGACGGTCCGCGGAT-1                    CTRL           0
146P_BASE_shZFP36L2_3_GTAGTACAGGCCCACT-1               ZFP_KD         5
KG146Li_HISC_shCtrl_TCTTAGTGTTAAGTCC-1                 CTRL           3
146P_HISC_shCTRL_AGGACGAGTAATGATG-1                    CTRL           6
146P_BASE_shZFP36L2_4_TTTGGTTTCGAAGCAG-1               ZFP_KD         5
125P_HISC_shZFP36L2_4_TACTTGTCAAGATGGC-1               ZFP_KD         1
146Li_dedifferentiation_shZFP36L2_4_GCAACATTCTTCTCAA-1 ZFP_KD         4
146P_HISC_shZFP36L2_4_ATGAGGGGTCACTGAT-1               ZFP_KD         6
125P_HISC_shCTRL_CGGACACCACAAAGTA-1                    CTRL           1
125P_HISC_shZFP36L2_4_TTCGGTCTCCGTTGGG-1               ZFP_KD         1
146P_HISC_shZFP36L2_4_ACAAAGATCATCACTT-1               ZFP_KD         6
146P_BASE_shZFP36L2_3_TCAGGTAAGTTTAGGA-1               ZFP_KD         5
146P_HISC_shZFP36L2_3_TCATCATAGATCGGTG-1               ZFP_KD         6
125P_HISC_shZFP36L2_4_TCATCATCAGGTACGA-1               ZFP_KD         1
                                                       Patient
146P_BASE_shZFP36L2_3_TTAGGGTCAGTAACGG-1               146
KG146Li_BASE_shZFP36L2_4_CGTTAGACACGTAACT-1            146
146P_BASE_shCTRL_AGGTGTTCATACAGGG-1                    146
146P_BASE_shZFP36L2_4_CCTCTAGGTCGCATTA-1               146
125P_HISC_shZFP36L2_3_GTTGTCCTCCACTGGG-1               125
146P_BASE_shZFP36L2_4_CTGTAGACACTCAAGT-1               146
KG146Li_BASE_shCtrl_TTGTTCACAGGAGACT-1                 146
KG146Li_BASE_shZFP36L2_3_TCTTGCGAGCATGATA-1            146
KG146Li_BASE_shZFP36L2_4_TACTTACAGAGTCCGA-1            146
KG146Li_BASE_shZFP36L2_3_GCACATAGTAGTTCCA-1            146
125P_BASE_shCTRL_TTCGATTGTGTTTCTT-1                    125
146P_HISC_shZFP36L2_3_TTACCGCGTTAAACAG-1               146
146P_HISC_shZFP36L2_4_CCGTGAGAGAACTCCT-1               146
125P_HISC_shZFP36L2_4_GTGGCGTGTGCTATTG-1               125
125P_HISC_shZFP36L2_4_CAGCGTGCAAGTCGTT-1               125
146P_HISC_shCTRL_ACAGCCGAGACCAACG-1                    146
125P_HISC_shZFP36L2_4_CTCTCAGGTACGTGAG-1               125
146P_HISC_shZFP36L2_4_AAGGAATGTGGGCTCT-1               146
125P_HISC_shZFP36L2_4_GCGAGAAAGGTCCTGC-1               125
KG146Li_HISC_shZFP36L2_3_AGGACTTAGGGATCGT-1            146
KG146Li_BASE_shZFP36L2_4_CGTGCTTAGTTTGAGA-1            146
KG146Li_HISC_shCtrl_GTGCGTGTCGAGGCAA-1                 146
146P_HISC_shCTRL_AATAGAGCACGCGGTT-1                    146
KG146Li_HISC_shZFP36L2_3_GCATCTCAGTGGACGT-1            146
125P_HISC_shCTRL_GTGCTTCAGCCATTGT-1                    125
KG146Li_BASE_shZFP36L2_3_GCGTGCAAGAGTCAAT-1            146
146P_BASE_shZFP36L2_3_GGTAGAGTCCTTGAAG-1               146
125P_HISC_shZFP36L2_4_TCGTGGGTCAGCGGAA-1               125
KG146Li_BASE_shZFP36L2_3_GAGGGTAAGTGCACAG-1            146
146P_BASE_shZFP36L2_3_GCACGGTCACTACAGT-1               146
⋮                                                      ⋮
125P_BASE_shCTRL_CTGAATGTCAAACGTC-1                    125
146P_BASE_shCTRL_GTTACCCTCCAATCCC-1                    146
146P_HISC_shZFP36L2_4_GTTAGACGTAGTAAGT-1               146
146P_BASE_shCTRL_CTAACCCGTGGAACCA-1                    146
125P_HISC_shZFP36L2_3_GATTCTTAGCACGATG-1               125
KG146Li_BASE_shCtrl_AGTACCAAGGGAGTGG-1                 146
146Li_dedifferentiation_shZFP36L2_4_AACCCAATCCAGCCTT-1 146
KG146Li_HISC_shCtrl_CATGGTACATAGCACT-1                 146
KG146Li_BASE_shCtrl_TGTAACGTCCATTTAC-1                 146
146P_HISC_shZFP36L2_3_AGGAATAGTGCTGCAC-1               146
146Li_dedifferentiation_shCtrl_CATGCAAAGCCTTTGA-1      146
146P_BASE_shCTRL_AGAGCCCGTCGGATTT-1                    146
146P_BASE_shCTRL_CACTTCGAGTCTGTAC-1                    146
KG146Li_BASE_shZFP36L2_4_CAAAGAAGTCATGGCC-1            146
125P_HISC_shCTRL_TCCGTGTGTTTCAGAC-1                    125
146Li_dedifferentiation_shZFP36L2_4_TCTACCGCATAAGCAA-1 146
125P_BASE_shCTRL_TCGACGGTCCGCGGAT-1                    125
146P_BASE_shZFP36L2_3_GTAGTACAGGCCCACT-1               146
KG146Li_HISC_shCtrl_TCTTAGTGTTAAGTCC-1                 146
146P_HISC_shCTRL_AGGACGAGTAATGATG-1                    146
146P_BASE_shZFP36L2_4_TTTGGTTTCGAAGCAG-1               146
125P_HISC_shZFP36L2_4_TACTTGTCAAGATGGC-1               125
146Li_dedifferentiation_shZFP36L2_4_GCAACATTCTTCTCAA-1 146
146P_HISC_shZFP36L2_4_ATGAGGGGTCACTGAT-1               146
125P_HISC_shCTRL_CGGACACCACAAAGTA-1                    125
125P_HISC_shZFP36L2_4_TTCGGTCTCCGTTGGG-1               125
146P_HISC_shZFP36L2_4_ACAAAGATCATCACTT-1               146
146P_BASE_shZFP36L2_3_TCAGGTAAGTTTAGGA-1               146
146P_HISC_shZFP36L2_3_TCATCATAGATCGGTG-1               146
125P_HISC_shZFP36L2_4_TCATCATCAGGTACGA-1               125

In [10]:
# Design a DESeqDataSet
dds_1 <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = coldata,
  design = ~ Tumor_Site + Culture_Media + Patient + ZFP_Expression
)

converting counts to integer mode

In [11]:
# Add a pseudo-count of 1 to all counts
count_matrix <- counts(dds_1) + 1

# Specify the row names as the gene names
rownames(count_matrix) <- adata$raw$var_names

In [12]:
count_matrix

            146P_BASE_shZFP36L2_3_TTAGGGTCAGTAACGG-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        2
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       3
AAMP        2
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN5C     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      1
ZSWIM6      2
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       3
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      2
ZYX         1
ZZEF1       1
            KG146Li_BASE_shZFP36L2_4_CGTTAGACACGTAACT-1
A1BG        1
A1BG-AS1    1
A1CF        4
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       1
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN5C     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      1
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       1
            146P_BASE_shCTRL_AGGTGTTCATACAGGG-1
A1BG        1
A1BG-AS1    1
A1CF        3
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       1
AAMP        3
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN5C     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      1
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      3
ZYX         1
ZZEF1       1
            146P_BASE_shZFP36L2_4_CCTCTAGGTCGCATTA-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        3
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       2
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        2
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     2
ZSCAN5B     1
ZSCAN5C     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      2
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      3
ZWINT       1
ZXDA        1
ZXDB        2
ZXDC        1
ZYG11A      1
ZYG11B      2
ZYX         2
ZZEF1       1
            125P_HISC_shZFP36L2_3_GTTGTCCTCCACTGGG-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       1
AAMP        3
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      1
AASDH       3
⋮           ⋮
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN5C     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      2
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       1
            146P_BASE_shZFP36L2_4_CTGTAGACACTCAAGT-1
A1BG        1
A1BG-AS1    1
A1CF        2
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        2
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       1
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN5C     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      3
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      2
ZWINT       3
ZXDA        1
ZXDB        1
ZXDC        2
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       2
            KG146Li_BASE_shCtrl_TTGTTCACAGGAGACT-1
A1BG        1
A1BG-AS1    1
A1CF        3
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       2
AAMP        2
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      2
AASDH       1
⋮           ⋮
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN5C     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      2
ZSWIM4      1
ZSWIM5      1
ZSWIM6      4
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       2
            KG146Li_BASE_shZFP36L2_3_TCTTGCGAGCATGATA-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        3
AAMDC       1
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        3
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN5C     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      1
ZSWIM6      3
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      3
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       1
            KG146Li_BASE_shZFP36L2_4_TACTTACAGAGTCCGA-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        2
AAMDC       1
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      1
AASDH       2
⋮           ⋮
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN5C     1
ZSCAN9      2
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      2
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        2
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       1
            KG146Li_BASE_shZFP36L2_3_GCACATAGTAGTTCCA-1 ⋯
A1BG        1                                           ⋯
A1BG-AS1    1                                           ⋯
A1CF        2                                           ⋯
A2M         1                                           ⋯
A2M-AS1     1                                           ⋯
A2ML1       1                                           ⋯
A2ML1-AS1   1                                           ⋯
A2ML1-AS2   1                                           ⋯
A3GALT2     1                                           ⋯
A4GALT      1                                           ⋯
A4GNT       1                                           ⋯
AAAS        1                                           ⋯
AACS        2                                           ⋯
AADAC       1                                           ⋯
AADACL2     1                                           ⋯
AADACL2-AS1 1                                           ⋯
AADACL3     1                                           ⋯
AADACL4     1                                           ⋯
AADAT       1                                           ⋯
AAGAB       2                                           ⋯
AAK1        1                                           ⋯
AAMDC       1                                           ⋯
AAMP        2                                           ⋯
AANAT       1                                           ⋯
AAR2        1                                           ⋯
AARD        1                                           ⋯
AARS        1                                           ⋯
AARS2       1                                           ⋯
AARSD1      2                                           ⋯
AASDH       1                                           ⋯
⋮           ⋮                                           ⋱
ZSCAN29     1                                           ⋯
ZSCAN30     1                                           ⋯
ZSCAN31     1                                           ⋯
ZSCAN32     1                                           ⋯
ZSCAN4      1                                           ⋯
ZSCAN5A     2                                           ⋯
ZSCAN5B     1                                           ⋯
ZSCAN5C     1                                           ⋯
ZSCAN9      1                                           ⋯
ZSWIM1      1                                           ⋯
ZSWIM2      1                                           ⋯
ZSWIM3      1                                           ⋯
ZSWIM4      1                                           ⋯
ZSWIM5      2                                           ⋯
ZSWIM6      2                                           ⋯
ZSWIM7      1                                           ⋯
ZSWIM8      1                                           ⋯
ZSWIM8-AS1  1                                           ⋯
ZSWIM9      1                                           ⋯
ZUP1        1                                           ⋯
ZW10        2                                           ⋯
ZWILCH      1                                           ⋯
ZWINT       2                                           ⋯
ZXDA        1                                           ⋯
ZXDB        1                                           ⋯
ZXDC        1                                           ⋯
ZYG11A      1                                           ⋯
ZYG11B      1                                           ⋯
ZYX         1                                           ⋯
ZZEF1       1                                           ⋯
            146P_BASE_shZFP36L2_4_TTTGGTTTCGAAGCAG-1
A1BG        1
A1BG-AS1    1
A1CF        4
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       1
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      3
AASDH       1
⋮           ⋮
ZSCAN29     3
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN5C     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      3
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       3
            125P_HISC_shZFP36L2_4_TACTTGTCAAGATGGC-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       1
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      3
AASDH       1
⋮           ⋮
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN5C     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      2
ZSWIM6      1
ZSWIM7      2
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        2
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      2
ZYX         1
ZZEF1       1
            146Li_dedifferentiation_shZFP36L2_4_GCAACATTCTTCTCAA-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        3
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       3
AAK1        1
AAMDC       1
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        3
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN5C     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      1
ZSWIM6      4
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       1
            146P_HISC_shZFP36L2_4_ATGAGGGGTCACTGAT-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       1
AAMP        1
AANAT       1
AAR2        2
AARD        1
AARS        3
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN5C     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      2
ZSWIM6      2
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      2
ZUP1        1
ZW10        2
ZWILCH      1
ZWINT       2
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         2
ZZEF1       1
            125P_HISC_shCTRL_CGGACACCACAAAGTA-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       1
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     3
ZSCAN5B     1
ZSCAN5C     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      1
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       1
            125P_HISC_shZFP36L2_4_TTCGGTCTCCGTTGGG-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       2
AAK1        1
AAMDC       1
AAMP        3
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      1
AASDH       2
⋮           ⋮
ZSCAN29     2
ZSCAN30     1
ZSCAN31     2
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN5C     1
ZSCAN9      2
ZSWIM1      1
ZSWIM2      1
ZSWIM3      2
ZSWIM4      1
ZSWIM5      1
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        2
ZYG11A      1
ZYG11B      2
ZYX         1
ZZEF1       1
            146P_HISC_shZFP36L2_4_ACAAAGATCATCACTT-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        2
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       2
AAK1        1
AAMDC       1
AAMP        1
AANAT       1
AAR2        2
AARD        1
AARS        2
AARS2       1
AARSD1      1
AASDH       2
⋮           ⋮
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN5C     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      2
ZSWIM5      2
ZSWIM6      2
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        2
ZWILCH      1
ZWINT       2
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       2
            146P_BASE_shZFP36L2_3_TCAGGTAAGTTTAGGA-1
A1BG        1
A1BG-AS1    1
A1CF        2
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       2
AAMP        2
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN5C     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      1
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      2
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      3
ZYX         1
ZZEF1       2
            146P_HISC_shZFP36L2_3_TCATCATAGATCGGTG-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       2
AAK1        1
AAMDC       1
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        2
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN5C     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      3
ZSWIM6      3
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       1
            125P_HISC_shZFP36L2_4_TCATCATCAGGTACGA-1
A1BG        1

In [14]:
# Set the reference levels
coldata$Tumor_Site<-relevel(coldata$Tumor_Site,ref="Primary")
coldata$Culture_Media<-relevel(coldata$Culture_Media,ref="BASE")
coldata$ZFP_Expression<-relevel(coldata$ZFP_Expression,ref="CTRL")
coldata$Patient<-relevel(coldata$Patient,ref="125")

In [15]:
coldata

                                                       Tumor_Site
146P_BASE_shZFP36L2_3_TTAGGGTCAGTAACGG-1               Primary
KG146Li_BASE_shZFP36L2_4_CGTTAGACACGTAACT-1            Metastatic
146P_BASE_shCTRL_AGGTGTTCATACAGGG-1                    Primary
146P_BASE_shZFP36L2_4_CCTCTAGGTCGCATTA-1               Primary
125P_HISC_shZFP36L2_3_GTTGTCCTCCACTGGG-1               Primary
146P_BASE_shZFP36L2_4_CTGTAGACACTCAAGT-1               Primary
KG146Li_BASE_shCtrl_TTGTTCACAGGAGACT-1                 Metastatic
KG146Li_BASE_shZFP36L2_3_TCTTGCGAGCATGATA-1            Metastatic
KG146Li_BASE_shZFP36L2_4_TACTTACAGAGTCCGA-1            Metastatic
KG146Li_BASE_shZFP36L2_3_GCACATAGTAGTTCCA-1            Metastatic
125P_BASE_shCTRL_TTCGATTGTGTTTCTT-1                    Primary
146P_HISC_shZFP36L2_3_TTACCGCGTTAAACAG-1               Primary
146P_HISC_shZFP36L2_4_CCGTGAGAGAACTCCT-1               Primary
125P_HISC_shZFP36L2_4_GTGGCGTGTGCTATTG-1               Primary
125P_HISC_shZFP36L2_4_CAGCGTGCAAGTCGTT-1               Primary
146P_HISC_shCTRL_ACAGCCGAGACCAACG-1                    Primary
125P_HISC_shZFP36L2_4_CTCTCAGGTACGTGAG-1               Primary
146P_HISC_shZFP36L2_4_AAGGAATGTGGGCTCT-1               Primary
125P_HISC_shZFP36L2_4_GCGAGAAAGGTCCTGC-1               Primary
KG146Li_HISC_shZFP36L2_3_AGGACTTAGGGATCGT-1            Metastatic
KG146Li_BASE_shZFP36L2_4_CGTGCTTAGTTTGAGA-1            Metastatic
KG146Li_HISC_shCtrl_GTGCGTGTCGAGGCAA-1                 Metastatic
146P_HISC_shCTRL_AATAGAGCACGCGGTT-1                    Primary
KG146Li_HISC_shZFP36L2_3_GCATCTCAGTGGACGT-1            Metastatic
125P_HISC_shCTRL_GTGCTTCAGCCATTGT-1                    Primary
KG146Li_BASE_shZFP36L2_3_GCGTGCAAGAGTCAAT-1            Metastatic
146P_BASE_shZFP36L2_3_GGTAGAGTCCTTGAAG-1               Primary
125P_HISC_shZFP36L2_4_TCGTGGGTCAGCGGAA-1               Primary
KG146Li_BASE_shZFP36L2_3_GAGGGTAAGTGCACAG-1            Metastatic
146P_BASE_shZFP36L2_3_GCACGGTCACTACAGT-1               Primary
⋮                                                      ⋮
125P_BASE_shCTRL_CTGAATGTCAAACGTC-1                    Primary
146P_BASE_shCTRL_GTTACCCTCCAATCCC-1                    Primary
146P_HISC_shZFP36L2_4_GTTAGACGTAGTAAGT-1               Primary
146P_BASE_shCTRL_CTAACCCGTGGAACCA-1                    Primary
125P_HISC_shZFP36L2_3_GATTCTTAGCACGATG-1               Primary
KG146Li_BASE_shCtrl_AGTACCAAGGGAGTGG-1                 Metastatic
146Li_dedifferentiation_shZFP36L2_4_AACCCAATCCAGCCTT-1 Metastatic
KG146Li_HISC_shCtrl_CATGGTACATAGCACT-1                 Metastatic
KG146Li_BASE_shCtrl_TGTAACGTCCATTTAC-1                 Metastatic
146P_HISC_shZFP36L2_3_AGGAATAGTGCTGCAC-1               Primary
146Li_dedifferentiation_shCtrl_CATGCAAAGCCTTTGA-1      Metastatic
146P_BASE_shCTRL_AGAGCCCGTCGGATTT-1                    Primary
146P_BASE_shCTRL_CACTTCGAGTCTGTAC-1                    Primary
KG146Li_BASE_shZFP36L2_4_CAAAGAAGTCATGGCC-1            Metastatic
125P_HISC_shCTRL_TCCGTGTGTTTCAGAC-1                    Primary
146Li_dedifferentiation_shZFP36L2_4_TCTACCGCATAAGCAA-1 Metastatic
125P_BASE_shCTRL_TCGACGGTCCGCGGAT-1                    Primary
146P_BASE_shZFP36L2_3_GTAGTACAGGCCCACT-1               Primary
KG146Li_HISC_shCtrl_TCTTAGTGTTAAGTCC-1                 Metastatic
146P_HISC_shCTRL_AGGACGAGTAATGATG-1                    Primary
146P_BASE_shZFP36L2_4_TTTGGTTTCGAAGCAG-1               Primary
125P_HISC_shZFP36L2_4_TACTTGTCAAGATGGC-1               Primary
146Li_dedifferentiation_shZFP36L2_4_GCAACATTCTTCTCAA-1 Metastatic
146P_HISC_shZFP36L2_4_ATGAGGGGTCACTGAT-1               Primary
125P_HISC_shCTRL_CGGACACCACAAAGTA-1                    Primary
125P_HISC_shZFP36L2_4_TTCGGTCTCCGTTGGG-1               Primary
146P_HISC_shZFP36L2_4_ACAAAGATCATCACTT-1               Primary
146P_BASE_shZFP36L2_3_TCAGGTAAGTTTAGGA-1               Primary
146P_HISC_shZFP36L2_3_TCATCATAGATCGGTG-1               Primary
125P_HISC_shZFP36L2_4_TCATCATCAGGTACGA-1               Primary
                                                       Culture_Media
146P_BASE_shZFP36L2_3_TTAGGGTCAGTAACGG-1               BASE
KG146Li_BASE_shZFP36L2_4_CGTTAGACACGTAACT-1            BASE
146P_BASE_shCTRL_AGGTGTTCATACAGGG-1                    BASE
146P_BASE_shZFP36L2_4_CCTCTAGGTCGCATTA-1               BASE
125P_HISC_shZFP36L2_3_GTTGTCCTCCACTGGG-1               HISC
146P_BASE_shZFP36L2_4_CTGTAGACACTCAAGT-1               BASE
KG146Li_BASE_shCtrl_TTGTTCACAGGAGACT-1                 BASE
KG146Li_BASE_shZFP36L2_3_TCTTGCGAGCATGATA-1            BASE
KG146Li_BASE_shZFP36L2_4_TACTTACAGAGTCCGA-1            BASE
KG146Li_BASE_shZFP36L2_3_GCACATAGTAGTTCCA-1            BASE
125P_BASE_shCTRL_TTCGATTGTGTTTCTT-1                    BASE
146P_HISC_shZFP36L2_3_TTACCGCGTTAAACAG-1               HISC
146P_HISC_shZFP36L2_4_CCGTGAGAGAACTCCT-1               HISC
125P_HISC_shZFP36L2_4_GTGGCGTGTGCTATTG-1               HISC
125P_HISC_shZFP36L2_4_CAGCGTGCAAGTCGTT-1               HISC
146P_HISC_shCTRL_ACAGCCGAGACCAACG-1                    HISC
125P_HISC_shZFP36L2_4_CTCTCAGGTACGTGAG-1               HISC
146P_HISC_shZFP36L2_4_AAGGAATGTGGGCTCT-1               HISC
125P_HISC_shZFP36L2_4_GCGAGAAAGGTCCTGC-1               HISC
KG146Li_HISC_shZFP36L2_3_AGGACTTAGGGATCGT-1            HISC
KG146Li_BASE_shZFP36L2_4_CGTGCTTAGTTTGAGA-1            BASE
KG146Li_HISC_shCtrl_GTGCGTGTCGAGGCAA-1                 HISC
146P_HISC_shCTRL_AATAGAGCACGCGGTT-1                    HISC
KG146Li_HISC_shZFP36L2_3_GCATCTCAGTGGACGT-1            HISC
125P_HISC_shCTRL_GTGCTTCAGCCATTGT-1                    HISC
KG146Li_BASE_shZFP36L2_3_GCGTGCAAGAGTCAAT-1            BASE
146P_BASE_shZFP36L2_3_GGTAGAGTCCTTGAAG-1               BASE
125P_HISC_shZFP36L2_4_TCGTGGGTCAGCGGAA-1               HISC
KG146Li_BASE_shZFP36L2_3_GAGGGTAAGTGCACAG-1            BASE
146P_BASE_shZFP36L2_3_GCACGGTCACTACAGT-1               BASE
⋮                                                      ⋮
125P_BASE_shCTRL_CTGAATGTCAAACGTC-1                    BASE
146P_BASE_shCTRL_GTTACCCTCCAATCCC-1                    BASE
146P_HISC_shZFP36L2_4_GTTAGACGTAGTAAGT-1               HISC
146P_BASE_shCTRL_CTAACCCGTGGAACCA-1                    BASE
125P_HISC_shZFP36L2_3_GATTCTTAGCACGATG-1               HISC
KG146Li_BASE_shCtrl_AGTACCAAGGGAGTGG-1                 BASE
146Li_dedifferentiation_shZFP36L2_4_AACCCAATCCAGCCTT-1 Dedifferentiated
KG146Li_HISC_shCtrl_CATGGTACATAGCACT-1                 HISC
KG146Li_BASE_shCtrl_TGTAACGTCCATTTAC-1                 BASE
146P_HISC_shZFP36L2_3_AGGAATAGTGCTGCAC-1               HISC
146Li_dedifferentiation_shCtrl_CATGCAAAGCCTTTGA-1      Dedifferentiated
146P_BASE_shCTRL_AGAGCCCGTCGGATTT-1                    BASE
146P_BASE_shCTRL_CACTTCGAGTCTGTAC-1                    BASE
KG146Li_BASE_shZFP36L2_4_CAAAGAAGTCATGGCC-1            BASE
125P_HISC_shCTRL_TCCGTGTGTTTCAGAC-1                    HISC
146Li_dedifferentiation_shZFP36L2_4_TCTACCGCATAAGCAA-1 Dedifferentiated
125P_BASE_shCTRL_TCGACGGTCCGCGGAT-1                    BASE
146P_BASE_shZFP36L2_3_GTAGTACAGGCCCACT-1               BASE
KG146Li_HISC_shCtrl_TCTTAGTGTTAAGTCC-1                 HISC
146P_HISC_shCTRL_AGGACGAGTAATGATG-1                    HISC
146P_BASE_shZFP36L2_4_TTTGGTTTCGAAGCAG-1               BASE
125P_HISC_shZFP36L2_4_TACTTGTCAAGATGGC-1               HISC
146Li_dedifferentiation_shZFP36L2_4_GCAACATTCTTCTCAA-1 Dedifferentiated
146P_HISC_shZFP36L2_4_ATGAGGGGTCACTGAT-1               HISC
125P_HISC_shCTRL_CGGACACCACAAAGTA-1                    HISC
125P_HISC_shZFP36L2_4_TTCGGTCTCCGTTGGG-1               HISC
146P_HISC_shZFP36L2_4_ACAAAGATCATCACTT-1               HISC
146P_BASE_shZFP36L2_3_TCAGGTAAGTTTAGGA-1               BASE
146P_HISC_shZFP36L2_3_TCATCATAGATCGGTG-1               HISC
125P_HISC_shZFP36L2_4_TCATCATCAGGTACGA-1               HISC
                                                       ZFP_Expression Batch
146P_BASE_shZFP36L2_3_TTAGGGTCAGTAACGG-1               ZFP_KD         5
KG146Li_BASE_shZFP36L2_4_CGTTAGACACGTAACT-1            ZFP_KD         2
146P_BASE_shCTRL_AGGTGTTCATACAGGG-1                    CTRL           5
146P_BASE_shZFP36L2_4_CCTCTAGGTCGCATTA-1               ZFP_KD         5
125P_HISC_shZFP36L2_3_GTTGTCCTCCACTGGG-1               ZFP_KD         1
146P_BASE_shZFP36L2_4_CTGTAGACACTCAAGT-1               ZFP_KD         5
KG146Li_BASE_shCtrl_TTGTTCACAGGAGACT-1                 CTRL           2
KG146Li_BASE_shZFP36L2_3_TCTTGCGAGCATGATA-1            ZFP_KD         2
KG146Li_BASE_shZFP36L2_4_TACTTACAGAGTCCGA-1            ZFP_KD         2
KG146Li_BASE_shZFP36L2_3_GCACATAGTAGTTCCA-1            ZFP_KD         2
125P_BASE_shCTRL_TTCGATTGTGTTTCTT-1                    CTRL           0
146P_HISC_shZFP36L2_3_TTACCGCGTTAAACAG-1               ZFP_KD         6
146P_HISC_shZFP36L2_4_CCGTGAGAGAACTCCT-1               ZFP_KD         6
125P_HISC_shZFP36L2_4_GTGGCGTGTGCTATTG-1               ZFP_KD         1
125P_HISC_shZFP36L2_4_CAGCGTGCAAGTCGTT-1               ZFP_KD         1
146P_HISC_shCTRL_ACAGCCGAGACCAACG-1                    CTRL           6
125P_HISC_shZFP36L2_4_CTCTCAGGTACGTGAG-1               ZFP_KD         1
146P_HISC_shZFP36L2_4_AAGGAATGTGGGCTCT-1               ZFP_KD         6
125P_HISC_shZFP36L2_4_GCGAGAAAGGTCCTGC-1               ZFP_KD         1
KG146Li_HISC_shZFP36L2_3_AGGACTTAGGGATCGT-1            ZFP_KD         3
KG146Li_BASE_shZFP36L2_4_CGTGCTTAGTTTGAGA-1            ZFP_KD         2
KG146Li_HISC_shCtrl_GTGCGTGTCGAGGCAA-1                 CTRL           3
146P_HISC_shCTRL_AATAGAGCACGCGGTT-1                    CTRL           6
KG146Li_HISC_shZFP36L2_3_GCATCTCAGTGGACGT-1            ZFP_KD         3
125P_HISC_shCTRL_GTGCTTCAGCCATTGT-1                    CTRL           1
KG146Li_BASE_shZFP36L2_3_GCGTGCAAGAGTCAAT-1            ZFP_KD         2
146P_BASE_shZFP36L2_3_GGTAGAGTCCTTGAAG-1               ZFP_KD         5
125P_HISC_shZFP36L2_4_TCGTGGGTCAGCGGAA-1               ZFP_KD         1
KG146Li_BASE_shZFP36L2_3_GAGGGTAAGTGCACAG-1            ZFP_KD         2
146P_BASE_shZFP36L2_3_GCACGGTCACTACAGT-1               ZFP_KD         5
⋮                                                      ⋮              ⋮
125P_BASE_shCTRL_CTGAATGTCAAACGTC-1                    CTRL           0
146P_BASE_shCTRL_GTTACCCTCCAATCCC-1                    CTRL           5
146P_HISC_shZFP36L2_4_GTTAGACGTAGTAAGT-1               ZFP_KD         6
146P_BASE_shCTRL_CTAACCCGTGGAACCA-1                    CTRL           5
125P_HISC_shZFP36L2_3_GATTCTTAGCACGATG-1               ZFP_KD         1
KG146Li_BASE_shCtrl_AGTACCAAGGGAGTGG-1                 CTRL           2
146Li_dedifferentiation_shZFP36L2_4_AACCCAATCCAGCCTT-1 ZFP_KD         4
KG146Li_HISC_shCtrl_CATGGTACATAGCACT-1                 CTRL           3
KG146Li_BASE_shCtrl_TGTAACGTCCATTTAC-1                 CTRL           2
146P_HISC_shZFP36L2_3_AGGAATAGTGCTGCAC-1               ZFP_KD         6
146Li_dedifferentiation_shCtrl_CATGCAAAGCCTTTGA-1      CTRL           4
146P_BASE_shCTRL_AGAGCCCGTCGGATTT-1                    CTRL           5
146P_BASE_shCTRL_CACTTCGAGTCTGTAC-1                    CTRL           5
KG146Li_BASE_shZFP36L2_4_CAAAGAAGTCATGGCC-1            ZFP_KD         2
125P_HISC_shCTRL_TCCGTGTGTTTCAGAC-1                    CTRL           1
146Li_dedifferentiation_shZFP36L2_4_TCTACCGCATAAGCAA-1 ZFP_KD         4
125P_BASE_shCTRL_TCGACGGTCCGCGGAT-1                    CTRL           0
146P_BASE_shZFP36L2_3_GTAGTACAGGCCCACT-1               ZFP_KD         5
KG146Li_HISC_shCtrl_TCTTAGTGTTAAGTCC-1                 CTRL           3
146P_HISC_shCTRL_AGGACGAGTAATGATG-1                    CTRL           6
146P_BASE_shZFP36L2_4_TTTGGTTTCGAAGCAG-1               ZFP_KD         5
125P_HISC_shZFP36L2_4_TACTTGTCAAGATGGC-1               ZFP_KD         1
146Li_dedifferentiation_shZFP36L2_4_GCAACATTCTTCTCAA-1 ZFP_KD         4
146P_HISC_shZFP36L2_4_ATGAGGGGTCACTGAT-1               ZFP_KD         6
125P_HISC_shCTRL_CGGACACCACAAAGTA-1                    CTRL           1
125P_HISC_shZFP36L2_4_TTCGGTCTCCGTTGGG-1               ZFP_KD         1
146P_HISC_shZFP36L2_4_ACAAAGATCATCACTT-1               ZFP_KD         6
146P_BASE_shZFP36L2_3_TCAGGTAAGTTTAGGA-1               ZFP_KD         5
146P_HISC_shZFP36L2_3_TCATCATAGATCGGTG-1               ZFP_KD         6
125P_HISC_shZFP36L2_4_TCATCATCAGGTACGA-1               ZFP_KD         1
                                                       Patient
146P_BASE_shZFP36L2_3_TTAGGGTCAGTAACGG-1               146
KG146Li_BASE_shZFP36L2_4_CGTTAGACACGTAACT-1            146
146P_BASE_shCTRL_AGGTGTTCATACAGGG-1                    146
146P_BASE_shZFP36L2_4_CCTCTAGGTCGCATTA-1               146
125P_HISC_shZFP36L2_3_GTTGTCCTCCACTGGG-1               125
146P_BASE_shZFP36L2_4_CTGTAGACACTCAAGT-1               146
KG146Li_BASE_shCtrl_TTGTTCACAGGAGACT-1                 146
KG146Li_BASE_shZFP36L2_3_TCTTGCGAGCATGATA-1            146
KG146Li_BASE_shZFP36L2_4_TACTTACAGAGTCCGA-1            146
KG146Li_BASE_shZFP36L2_3_GCACATAGTAGTTCCA-1            146
125P_BASE_shCTRL_TTCGATTGTGTTTCTT-1                    125
146P_HISC_shZFP36L2_3_TTACCGCGTTAAACAG-1               146
146P_HISC_shZFP36L2_4_CCGTGAGAGAACTCCT-1               146
125P_HISC_shZFP36L2_4_GTGGCGTGTGCTATTG-1               125
125P_HISC_shZFP36L2_4_CAGCGTGCAAGTCGTT-1               125
146P_HISC_shCTRL_ACAGCCGAGACCAACG-1                    146
125P_HISC_shZFP36L2_4_CTCTCAGGTACGTGAG-1               125
146P_HISC_shZFP36L2_4_AAGGAATGTGGGCTCT-1               146
125P_HISC_shZFP36L2_4_GCGAGAAAGGTCCTGC-1               125
KG146Li_HISC_shZFP36L2_3_AGGACTTAGGGATCGT-1            146
KG146Li_BASE_shZFP36L2_4_CGTGCTTAGTTTGAGA-1            146
KG146Li_HISC_shCtrl_GTGCGTGTCGAGGCAA-1                 146
146P_HISC_shCTRL_AATAGAGCACGCGGTT-1                    146
KG146Li_HISC_shZFP36L2_3_GCATCTCAGTGGACGT-1            146
125P_HISC_shCTRL_GTGCTTCAGCCATTGT-1                    125
KG146Li_BASE_shZFP36L2_3_GCGTGCAAGAGTCAAT-1            146
146P_BASE_shZFP36L2_3_GGTAGAGTCCTTGAAG-1               146
125P_HISC_shZFP36L2_4_TCGTGGGTCAGCGGAA-1               125
KG146Li_BASE_shZFP36L2_3_GAGGGTAAGTGCACAG-1            146
146P_BASE_shZFP36L2_3_GCACGGTCACTACAGT-1               146
⋮                                                      ⋮
125P_BASE_shCTRL_CTGAATGTCAAACGTC-1                    125
146P_BASE_shCTRL_GTTACCCTCCAATCCC-1                    146
146P_HISC_shZFP36L2_4_GTTAGACGTAGTAAGT-1               146
146P_BASE_shCTRL_CTAACCCGTGGAACCA-1                    146
125P_HISC_shZFP36L2_3_GATTCTTAGCACGATG-1               125
KG146Li_BASE_shCtrl_AGTACCAAGGGAGTGG-1                 146
146Li_dedifferentiation_shZFP36L2_4_AACCCAATCCAGCCTT-1 146
KG146Li_HISC_shCtrl_CATGGTACATAGCACT-1                 146
KG146Li_BASE_shCtrl_TGTAACGTCCATTTAC-1                 146
146P_HISC_shZFP36L2_3_AGGAATAGTGCTGCAC-1               146
146Li_dedifferentiation_shCtrl_CATGCAAAGCCTTTGA-1      146
146P_BASE_shCTRL_AGAGCCCGTCGGATTT-1                    146
146P_BASE_shCTRL_CACTTCGAGTCTGTAC-1                    146
KG146Li_BASE_shZFP36L2_4_CAAAGAAGTCATGGCC-1            146
125P_HISC_shCTRL_TCCGTGTGTTTCAGAC-1                    125
146Li_dedifferentiation_shZFP36L2_4_TCTACCGCATAAGCAA-1 146
125P_BASE_shCTRL_TCGACGGTCCGCGGAT-1                    125
146P_BASE_shZFP36L2_3_GTAGTACAGGCCCACT-1               146
KG146Li_HISC_shCtrl_TCTTAGTGTTAAGTCC-1                 146
146P_HISC_shCTRL_AGGACGAGTAATGATG-1                    146
146P_BASE_shZFP36L2_4_TTTGGTTTCGAAGCAG-1               146
125P_HISC_shZFP36L2_4_TACTTGTCAAGATGGC-1               125
146Li_dedifferentiation_shZFP36L2_4_GCAACATTCTTCTCAA-1 146
146P_HISC_shZFP36L2_4_ATGAGGGGTCACTGAT-1               146
125P_HISC_shCTRL_CGGACACCACAAAGTA-1                    125
125P_HISC_shZFP36L2_4_TTCGGTCTCCGTTGGG-1               125
146P_HISC_shZFP36L2_4_ACAAAGATCATCACTT-1               146
146P_BASE_shZFP36L2_3_TCAGGTAAGTTTAGGA-1               146
146P_HISC_shZFP36L2_3_TCATCATAGATCGGTG-1               146
125P_HISC_shZFP36L2_4_TCATCATCAGGTACGA-1               125

In [16]:
# Design a DESeqDataSet with modified count matrix
dds_1 <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = coldata,
  design = ~ Tumor_Site + Culture_Media + Patient + ZFP_Expression 
)

converting counts to integer mode

In [17]:
dds_1

class: DESeqDataSet
dim: 32485 59140
metadata(1): version
assays(1): counts
rownames(32485): A1BG A1BG-AS1 ... ZYX ZZEF1
rowData names(0):
colnames(59140): 146P_BASE_shZFP36L2_3_TTAGGGTCAGTAACGG-1
  KG146Li_BASE_shZFP36L2_4_CGTTAGACACGTAACT-1 ...
  146P_HISC_shZFP36L2_3_TCATCATAGATCGGTG-1
  125P_HISC_shZFP36L2_4_TCATCATCAGGTACGA-1
colData names(5): Tumor_Site Culture_Media ZFP_Expression Batch Patient

In [1]:
# Set the CRAN mirror
options(repos = c(CRAN = "https://cran.r-project.org"))

# If not already downloaded in environment, then download DESeq2
if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")
}
BiocManager::install("DESeq2")

'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.r-project.org

Bioconductor version 3.18 (BiocManager 1.30.22), R 4.3.1 (2023-06-16)

Warning message:
“package(s) not installed when version(s) same as or greater than current; use
  `force = TRUE` to re-install: 'DESeq2'”
Old packages: 'cli', 'cluster', 'evaluate', 'fansi', 'foreign', 'htmltools',
  'jsonlite', 'lifecycle', 'Matrix', 'nlme', 'rlang', 'rpart', 'rprojroot',
  'vctrs', 'withr'

In [1]:
library("anndata")
library("DESeq2")

Loading required package: S4Vectors

Loading required package: stats4

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min



Attaching package: ‘S4Vectors’


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges

Loading required package: GenomicRanges

Loading required package: GenomeInfoDb

Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats


Attaching package: ‘MatrixGenerics’


The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘Biobase’


The following object is masked from ‘package:MatrixGenerics’:

    rowMedians


The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians

In [2]:
# Read h5ad file
adata <- read_h5ad("/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/combined/out_post_hvg/adata.combined.hvg_5000.h5ad")

In [3]:
# Extract count matrix from the raw layer
count_matrix <- adata$raw$X
count_matrix <- t(count_matrix)
count_matrix <- round(count_matrix)

In [4]:
# Define the column data
coldata <- adata$obs[,c("Tumor_Site","Culture_Media", "ZFP_Expression", "Batch", "Patient")]

# Convert column data to factors
coldata$Tumor_Site <- factor(coldata$Tumor_Site)
coldata$Culture_Media <- factor(coldata$Culture_Media)
coldata$ZFP_Expression <- factor(coldata$ZFP_Expression)
coldata$Batch <- factor(coldata$Batch)
coldata$Patient <- factor(coldata$Patient)

In [5]:
# Design a DESeqDataSet
dds_1 <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = coldata,
  design = ~ Tumor_Site + Culture_Media + Patient + ZFP_Expression
)

# Add a pseudo-count of 1 to all counts
count_matrix <- counts(dds_1) + 1

# Specify the row names as the gene names
rownames(count_matrix) <- adata$raw$var_names

converting counts to integer mode

In [6]:
# Set the reference levels
dds_1$Tumor_Site<-relevel(dds_1$Tumor_Site,ref="Primary")
dds_1$Culture_Media<-relevel(dds_1$Culture_Media,ref="BASE")
dds_1$ZFP_Expression<-relevel(dds_1$ZFP_Expression,ref="CTRL")
dds_1$Patient<-relevel(dds_1$Patient,ref="125")

In [7]:
# Design a DESeqDataSet with modified count matrix
dds_1 <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = coldata,
  design = ~ Tumor_Site + Culture_Media + Patient + ZFP_Expression 
)

converting counts to integer mode

In [ ]:
# Perform DESeq analysis
dds_1 <- DESeq(dds_1)

estimating size factors

estimating dispersions

gene-wise dispersion estimates

In [ ]:
# Extract results
result_names_1 <- resultsNames(dds_1)
result_names_1

# Specify the contrast and extract results
res_1 <- results(dds_1)
res_1

In [ ]:
# Specify the file path where you want to save the results
result_file <- "/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/deseq/zfpexp_results.csv"

# Write the results table to a CSV file
write.csv(as.data.frame(res_1), file = result_file)

# Save the DESeqDataSet object
saveRDS(dds_1, file = "/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/deseq/zfpexp_dds.rds")

# Save the DESeq results
saveRDS(results(dds_1), file = "/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/deseq/zfpexp_results.rds")

In [1]:
# Install the R anndata package
install.packages("anndata")

# Run this only if you do not already have an installation of miniconda
#reticulate::install_miniconda(force = TRUE)
#install.packages("reticulate")

# Install the Python anndata package
#anndata::install_anndata()

In [13]:
#install.packages("reticulate")

In [1]:
#Sys.setenv(PATH = paste("lila/home/forsythb/anaconda3/envs/r_4.3.1/bin", Sys.getenv("PATH"), sep = ":"))

In [3]:
#library(reticulate)
#use_python("lila/home/forsythb/anaconda3/envs/r_4.3.1/bin/python")

In [2]:
# Load libraries
library(DESeq2)
library(anndata)

Loading required package: S4Vectors

Loading required package: stats4

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min



Attaching package: ‘S4Vectors’


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges

Loading required package: GenomicRanges

Loading required package: GenomeInfoDb

Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats


Attaching package: ‘MatrixGenerics’


The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘Biobase’


The following object is masked from ‘package:MatrixGenerics’:

    rowMedians


The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians

In [3]:
# Read h5ad file
adata <- read_h5ad("/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/combined/out_post_hvg/adata.combined.hvg_5000.h5ad")

In [4]:
# Extract count matrix from the raw layer
count_matrix <- adata$raw$X
count_matrix <- t(count_matrix)
count_matrix <- round(count_matrix)

In [5]:
# Define the column data
coldata <- adata$obs[,c("Tumor_Site","Culture_Media", "ZFP_Expression", "Batch", "Patient")]

# Convert column data to factors
coldata$Tumor_Site <- factor(coldata$Tumor_Site)
coldata$Culture_Media <- factor(coldata$Culture_Media)
coldata$ZFP_Expression <- factor(coldata$ZFP_Expression)
coldata$Batch <- factor(coldata$Batch)
coldata$Patient <- factor(coldata$Patient)

In [ ]:
# Design a DESeqDataSet
dds_1 <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = coldata,
  design = ~ Tumor_Site + Culture_Media + Patient + ZFP_Expression + ZFP_Expression:Culture_Media
)

# Add a pseudo-count of 1 to all counts
count_matrix <- counts(dds_1) + 1

# Specify the row names as the gene names
rownames(count_matrix) <- adata$raw$var_names

In [ ]:
# Set the reference levels
dds_1$Tumor_Site<-relevel(dds_1$Tumor_Site,ref="Primary")
dds_1$Culture_Media<-relevel(dds_1$Culture_Media,ref="BASE")
dds_1$ZFP_Expression<-relevel(dds_1$ZFP_Expression,ref="CTRL")
dds_1$Patient<-relevel(dds_1$Patient,ref="125")

In [ ]:
# Design a DESeqDataSet with modified count matrix
dds_1 <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = coldata,
  design = ~ Tumor_Site + Culture_Media + Patient + ZFP_Expression + ZFP_Expression:Culture_Media
)

In [ ]:
# Perform DESeq analysis
dds_1 <- DESeq(dds_1)

In [ ]:
# Extract results
result_names_1 <- resultsNames(dds_1)
result_names_1

# Specify the contrast and extract results
res_1 <- results(dds_1)
res_1

In [ ]:
# Specify the file path where you want to save the results
result_file <- "/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/deseq/zfpexp_results.csv"

# Write the results table to a CSV file
write.csv(as.data.frame(res_1), file = result_file)

# Save the DESeqDataSet object
saveRDS(dds_1, file = "/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/deseq/zfpexp_dds.rds")

# Save the DESeq results
saveRDS(results(dds_1), file = "/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output/deseq/zfpexp_results.rds")