In [1]:
library(DESeq2)
library(dplyr)
library('Matrix')
library(tibble)
library(zoo)
library(stringr)
library(lubridate)
library(fgsea)
library(stringr)
library(gage)
library(devtools)
library(pals)
library(ggplot2)
library(repr)
library(ggrepel)

Loading required package: S4Vectors

Loading required package: stats4

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min



Attaching package: ‘S4Vectors’


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges

Loading required package: GenomicRanges

Loading required package: GenomeInfoDb

Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats


Attaching package: ‘MatrixGenerics’


The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘Biobase’


The following object is masked from ‘package:MatrixGenerics’:

    rowMedians


The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians



Attaching package: ‘dplyr’


The following object is masked from ‘package:Biobase’:

    combine


The following object is masked from ‘package:matrixStats’:

    count


The following objects are masked from ‘package:GenomicRanges’:

    intersect, setdiff, union


The following object is masked from ‘package:GenomeInfoDb’:

    intersect


The following objects are masked from ‘package:IRanges’:

    collapse, desc, intersect, setdiff, slice, union


The following objects are masked from ‘package:S4Vectors’:

    first, intersect, rename, setdiff, setequal, union


The following objects are masked from ‘package:BiocGenerics’:

    combine, intersect, setdiff, union


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



Attaching package: ‘Matrix’


The following object is masked from ‘package:S4Vectors’:

    expand



Attaching package: ‘zoo’


The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric


Warning message:
“package ‘stringr’ was built under R version 4.3.2”

Attaching package: ‘lubridate’


The following objects are masked from ‘package:GenomicRanges’:

    intersect, setdiff, union


The following object is masked from ‘package:GenomeInfoDb’:

    intersect


The following objects are masked from ‘package:IRanges’:

    %within%, intersect, setdiff, union


The following objects are masked from ‘package:S4Vectors’:

    intersect, second, second<-, setdiff, union


The following objects are masked from ‘package:BiocGenerics’:

    intersect, setdiff, union


The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union




Loading required package: usethis

In [5]:
local_corr_modules = read.csv('/data/chanjlab/CRC_ZFP36L2.092023/Patients.HTAN/notebooks/ML/Organoid/local_corr_clusters_DEGs/degs_leiden_clusters_concat.csv')

In [6]:
local_corr_modules

      cluster names    scores   logfoldchanges pvals       pvals_adj
1     8       TCF7L2   17.26022 0.5598861      9.37471e-67 1.37851e-65
2     8       ATRX     16.54984 0.5173059      1.60528e-61 2.25519e-60
3     8       SETD5    15.57358 0.5723956      1.10065e-54 1.44599e-53
4     8       RBM47    14.94454 0.5174391      1.69065e-50 2.13131e-49
5     8       ITGA6    14.66685 0.5753797      1.05108e-48 1.29980e-47
6     8       NCOR1    14.65324 0.5779376      1.28446e-48 1.58654e-47
7     8       CHD2     14.57000 0.5525929      4.35907e-48 5.36343e-47
8     8       SENP6    14.30458 0.5086332      2.04868e-46 2.46633e-45
9     8       SBF2     14.23994 0.5610374      5.17707e-46 6.19962e-45
10    8       ANKRD11  13.94016 0.4221368      3.61136e-44 4.23380e-43
11    8       NEBL     13.66501 0.5651239      1.64290e-42 1.88711e-41
12    8       RBFOX2   13.59119 0.4556981      4.51680e-42 5.15840e-41
13    8       CCNY     13.23850 0.5383229      5.25867e-40 5.84611e-39
14    8       BPTF     12.99936 0.3584899      1.23367e-38 1.34377e-37
15    8       HECTD1   12.91066 0.5828043      3.91929e-38 4.24292e-37
16    8       AFDN     12.67815 0.4807498      7.81498e-37 8.32150e-36
17    8       UBAC2    12.44965 0.5759262      1.40455e-35 1.47097e-34
18    8       PHF14    12.23813 0.5157099      1.94464e-34 2.00947e-33
19    8       EIF4G3   12.16137 0.5231437      4.99154e-34 5.12960e-33
20    8       RAP1B    12.09838 0.5450330      1.07713e-33 1.10336e-32
21    8       GSK3B    11.89094 0.4921018      1.31912e-32 1.33024e-31
22    8       LCOR     11.57828 0.5097579      5.30989e-31 5.21576e-30
23    8       CNOT1    11.51137 0.5524728      1.15623e-30 1.12807e-29
24    8       IMMP2L   11.40757 0.3944600      3.83299e-30 3.70707e-29
25    8       FAM49B   11.37685 0.5232717      5.45323e-30 5.25911e-29
26    8       TEAD1    11.28612 0.5567604      1.53677e-29 1.47047e-28
27    8       PPP2R5E  11.20848 0.5509486      3.70519e-29 3.52204e-28
28    8       DDAH1    11.01293 0.5491880      3.31050e-28 3.11059e-27
29    8       CUL3     10.90870 0.5023716      1.04745e-27 9.74125e-27
30    8       SMYD3    10.84021 0.3760937      2.21966e-27 2.05348e-26
⋮     ⋮       ⋮        ⋮        ⋮              ⋮           ⋮
73287 11      MLEC     -11.6510 -0.57214        2.27e-31    6.49e-29
73288 11      C15orf48 -11.6680 -1.99867        1.86e-31    5.37e-29
73289 11      NHS      -11.7569 -2.34121        6.51e-32    1.90e-29
73290 11      SVIL     -11.8158 -1.54188        3.23e-32    9.61e-30
73291 11      CKB      -11.9404 -1.42193        7.29e-33    2.29e-30
73292 11      CPA6     -12.0634 -2.17491        1.65e-33    5.40e-31
73293 11      PEBP1    -12.1508 -0.57709        5.68e-34    1.92e-31
73294 11      TFDP2    -12.2903 -1.24922        1.02e-34    3.57e-32
73295 11      MT-ATP8  -12.2989 -1.30269        9.19e-35    3.25e-32
73296 11      TNIK     -12.3926 -1.81694        2.87e-35    1.04e-32
73297 11      RSRC1    -12.4496 -1.20790        1.41e-35    5.14e-33
73298 11      HEPH     -12.6957 -4.85759        6.24e-37    2.51e-34
73299 11      PPARG    -12.7132 -1.03717        4.99e-37    2.04e-34
73300 11      TSPAN8   -12.8156 -1.03293        1.34e-37    5.69e-35
73301 11      MAML2    -12.8981 -3.02641        4.61e-38    2.01e-35
73302 11      IGF2BP2  -13.3142 -1.17471        1.91e-40    9.22e-38
73303 11      SMIM14   -13.3732 -1.27605        8.68e-41    4.38e-38
73304 11      SUCLG2   -13.6354 -1.31409        2.47e-42    1.29e-39
73305 11      AGR3     -13.8062 -4.94739        2.34e-43    1.30e-40
73306 11      SPINK1   -13.8188 -2.44199        1.96e-43    1.12e-40
73307 11      SIVA1    -13.8698 -1.45972        9.65e-44    5.58e-41
73308 11      AGR2     -14.1840 -1.01590        1.15e-45    6.77e-43
73309 11      MBNL1    -14.5454 -1.19617        6.25e-48    3.90e-45
73310 11      ALDH1A1  -14.9626 -1.46964        1.29e-50    8.73e-48
73311 11      CACNB2   -15.2699 -1.77110        1.21e-52    8.97e-50
73312 11      UTRN     -16.3080 -4.35378        8.65e-60    7.65e-57
73313 11      DLGAP1   -16.9431 -2.73891        2.16e-64    2.09e-61
73314 11      GNAS     -17.7696 -2.35087        1.22e-70    1.43e-67
73315 11      BEX3     -19.9287 -2.85566        2.30e-88    4.29e-85
73316 11      XIST     -22.3907 -2.77244       4.90e-111   1.20e-107

In [11]:
unique_clusters <- unique(local_corr_modules$cluster)

for (cluster_value in unique_clusters) {
  cluster_df <- local_corr_modules[local_corr_modules$cluster == cluster_value, ]
  
  df_name <- paste("local_corr_module_", cluster_value, sep = "")
  
  assign(df_name, cluster_df)
}

In [12]:
unique_clusters1 <- unique(local_corr_modules$cluster)

for (cluster_value in unique_clusters1) {
  df_name1 <- paste("local_corr_module_", cluster_value, sep = "")
  
  cat("Variable name:", df_name1, "\n")
}

Variable name: local_corr_module_8
Variable name: local_corr_module_6
Variable name: local_corr_module_3
Variable name: local_corr_module_9
Variable name: local_corr_module_0
Variable name: local_corr_module_1
Variable name: local_corr_module_2
Variable name: local_corr_module_5
Variable name: local_corr_module_4
Variable name: local_corr_module_7
Variable name: local_corr_module_10
Variable name: local_corr_module_11

In [23]:
local_corr_module_8

     cluster names   scores    logfoldchanges pvals       pvals_adj
1    8       TCF7L2  17.26022  0.5598861      9.37471e-67 1.37851e-65
2    8       ATRX    16.54984  0.5173059      1.60528e-61 2.25519e-60
3    8       SETD5   15.57358  0.5723956      1.10065e-54 1.44599e-53
4    8       RBM47   14.94454  0.5174391      1.69065e-50 2.13131e-49
5    8       ITGA6   14.66685  0.5753797      1.05108e-48 1.29980e-47
6    8       NCOR1   14.65324  0.5779376      1.28446e-48 1.58654e-47
7    8       CHD2    14.57000  0.5525929      4.35907e-48 5.36343e-47
8    8       SENP6   14.30458  0.5086332      2.04868e-46 2.46633e-45
9    8       SBF2    14.23994  0.5610374      5.17707e-46 6.19962e-45
10   8       ANKRD11 13.94016  0.4221368      3.61136e-44 4.23380e-43
11   8       NEBL    13.66501  0.5651239      1.64290e-42 1.88711e-41
12   8       RBFOX2  13.59119  0.4556981      4.51680e-42 5.15840e-41
13   8       CCNY    13.23850  0.5383229      5.25867e-40 5.84611e-39
14   8       BPTF    12.99936  0.3584899      1.23367e-38 1.34377e-37
15   8       HECTD1  12.91066  0.5828043      3.91929e-38 4.24292e-37
16   8       AFDN    12.67815  0.4807498      7.81498e-37 8.32150e-36
17   8       UBAC2   12.44965  0.5759262      1.40455e-35 1.47097e-34
18   8       PHF14   12.23813  0.5157099      1.94464e-34 2.00947e-33
19   8       EIF4G3  12.16137  0.5231437      4.99154e-34 5.12960e-33
20   8       RAP1B   12.09838  0.5450330      1.07713e-33 1.10336e-32
21   8       GSK3B   11.89094  0.4921018      1.31912e-32 1.33024e-31
22   8       LCOR    11.57828  0.5097579      5.30989e-31 5.21576e-30
23   8       CNOT1   11.51137  0.5524728      1.15623e-30 1.12807e-29
24   8       IMMP2L  11.40757  0.3944600      3.83299e-30 3.70707e-29
25   8       FAM49B  11.37685  0.5232717      5.45323e-30 5.25911e-29
26   8       TEAD1   11.28612  0.5567604      1.53677e-29 1.47047e-28
27   8       PPP2R5E 11.20848  0.5509486      3.70519e-29 3.52204e-28
28   8       DDAH1   11.01293  0.5491880      3.31050e-28 3.11059e-27
29   8       CUL3    10.90870  0.5023716      1.04745e-27 9.74125e-27
30   8       SMYD3   10.84021  0.3760937      2.21966e-27 2.05348e-26
⋮    ⋮       ⋮       ⋮         ⋮              ⋮           ⋮
7156 8       RPS15A  -65.09006 -6.111470      0           0
7157 8       RPS23   -65.10453 -5.672727      0           0
7158 8       TPT1    -65.21830 -5.315385      0           0
7159 8       RPL26   -65.22241 -6.442435      0           0
7160 8       RPL29   -65.22717 -5.808085      0           0
7161 8       RPS17   -65.24764 -6.796072      0           0
7162 8       RPL23   -65.27608 -6.009693      0           0
7163 8       RPL3    -65.29056 -4.464499      0           0
7164 8       NACA    -65.29358 -5.770826      0           0
7165 8       EEF1G   -65.34774 -5.172054      0           0
7166 8       RPL10A  -65.37300 -5.827374      0           0
7167 8       RPL9    -65.39080 -5.361531      0           0
7168 8       RPL8    -65.39915 -4.685196      0           0
7169 8       RPS14   -65.45794 -6.202813      0           0
7170 8       RACK1   -65.46577 -6.087686      0           0
7171 8       RPL24   -65.50465 -5.875355      0           0
7172 8       RPL5    -65.60364 -4.771524      0           0
7173 8       RPS3    -65.71356 -5.162680      0           0
7174 8       RPL12   -65.71779 -6.330395      0           0
7175 8       RPL15   -65.71925 -5.639977      0           0
7176 8       RPL17   -65.77258 -6.579128      0           0
7177 8       RPS3A   -65.80972 -5.513491      0           0
7178 8       RPS12   -65.82714 -6.686757      0           0
7179 8       EEF1A1  -66.03580 -4.627867      0           0
7180 8       RPL7A   -66.13719 -5.426052      0           0
7181 8       RPL7    -66.37634 -6.218183      0           0
7182 8       RPL13   -66.45635 -5.374727      0           0
7183 8       RPS6    -66.57674 -5.671107      0           0
7184 8       RPS4X   -66.69457 -6.185492      0           0
7185 8       RPS2    -66.77142 -5.057484      0           0

In [44]:
#gene matrix transposed
gset = list()
i = 'small'
gmt_fn = '/data/chanjlab/CRC_ZFP36L2.092023/ref/pathways_for_gsea.curated.small.110123.gmt'
gset[[i]] = gage::readList(gmt_fn)

In [71]:
RunGSEA <- function(local_corr_module_0, gset0) {
  rnk = local_corr_module_0$logfoldchanges

  names(rnk) = local_corr_module_0$names
  score = rnk[!is.na(rnk)] 
  
  fgseaRes_0 <- fgsea(pathways = gset0, 
              stats = score,
              minSize=10,
              maxSize=500)#,
              #nperm=10000)
  
  fgseaRes_0$leadingEdge = sapply(fgseaRes_0$leadingEdge, function(x) str_c(x,collapse=','))
  return(fgseaRes_0)
}

In [72]:
gsea_dir = '/data/chanjlab/CRC_ZFP36L2.092023/Patients.HTAN/output/organoid_ML/GSEA_local_corr_modules_DEGS'

In [73]:
for (mode in 'small') {
    fgseaRes_0 = RunGSEA(local_corr_module_0, gset[[mode]])

    ofile = sprintf('GSEA.logfc_local_corr_module_0.%s.txt', mode)
    write.table(fgseaRes_0, sprintf('%s/%s',gsea_dir,ofile), sep='\t', quote=F, row.names=F)

}

Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“There were 70 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values. For such pathways pval, padj, NES, log2err are set to NA. You can try to increase the value of the argument nPermSimple (for example set it nPermSimple = 10000)”

In [74]:
fgseaRes_0

    pathway                                          pval         padj
1   ABBUD_LIF_SIGNALING_1_UP                         3.018480e-01 6.610090e-01
2   ACEVEDO_LIVER_CANCER_UP                                    NA           NA
3   ACEVEDO_LIVER_TUMOR_VS_NORMAL_ADJACENT_TISSUE_UP           NA           NA
4   AGUIRRE_PANCREATIC_CANCER_COPY_NUMBER_DN         9.890110e-01 1.000000e+00
5   AGUIRRE_PANCREATIC_CANCER_COPY_NUMBER_UP         1.000000e+00 1.000000e+00
6   AKT_UP_MTOR_DN.V1_DN                             6.675376e-03 4.174121e-02
7   AKT_UP_MTOR_DN.V1_UP                             7.414830e-02 2.497221e-01
8   ALFANO_MYC_TARGETS                               2.837163e-01 6.311598e-01
9   ALONSO_METASTASIS_UP                             9.720280e-01 1.000000e+00
10  ASC_SMITH_CELL2018                               9.222798e-02 2.973063e-01
11  BACOLOD_RESISTANCE_TO_ALKYLATING_AGENTS_DN       6.248694e-01 1.000000e+00
12  BACOLOD_RESISTANCE_TO_ALKYLATING_AGENTS_UP       9.741060e-02 3.101601e-01
13  BASAKI_YBX1_TARGETS_DN                           1.053681e-02 6.009453e-02
14  BASAKI_YBX1_TARGETS_UP                           9.780220e-01 1.000000e+00
15  BASAL_MONTORO                                    5.834279e-01 1.000000e+00
16  BECKER_TAMOXIFEN_RESISTANCE_DN                   3.060109e-02 1.345929e-01
17  BECKER_TAMOXIFEN_RESISTANCE_UP                   5.112108e-01 9.342197e-01
18  BENPORATH_CYCLING_GENES                          1.000000e+00 1.000000e+00
19  BENPORATH_EED_TARGETS                            2.555145e-05 5.304481e-04
20  BENPORATH_ES_1                                   2.617383e-01 6.091577e-01
21  BENPORATH_ES_WITH_H3K27ME3                       1.459733e-10 2.525337e-08
22  BENPORATH_MYC_MAX_TARGETS                                  NA           NA
23  BENPORATH_MYC_TARGETS_WITH_EBOX                  9.710290e-01 1.000000e+00
24  BENPORATH_PROLIFERATION                                    NA           NA
25  BENPORATH_SOX2_TARGETS                           1.000000e+00 1.000000e+00
26  BENPORATH_SUZ12_TARGETS                          5.406596e-07 2.550930e-05
27  BERENJENO_TRANSFORMED_BY_RHOA_DN                 2.747253e-01 6.226306e-01
28  BERENJENO_TRANSFORMED_BY_RHOA_UP                 1.000000e+00 1.000000e+00
29  BHATTACHARYA_EMBRYONIC_STEM_CELL                 6.847390e-01 1.000000e+00
30  BIDUS_METASTASIS_UP                                        NA           NA
⋮   ⋮                                                ⋮            ⋮
560 WAKABAYASHI_ADIPOGENESIS_PPARG_RXRA_BOUND_8D     1.000000e+00 1.000000e+00
561 WAMUNYOKOLI_OVARIAN_CANCER_LMP_UP                          NA           NA
562 WANG_LMO4_TARGETS_DN                                       NA           NA
563 WANG_LMO4_TARGETS_UP                             9.980020e-01 1.000000e+00
564 WANG_RESPONSE_TO_GSK3_INHIBITOR_SB216763_DN      8.771229e-01 1.000000e+00
565 WANG_SMARCE1_TARGETS_DN                          6.243756e-01 1.000000e+00
566 WANG_TUMOR_INVASIVENESS_DN                       9.980020e-01 1.000000e+00
567 WANG_TUMOR_INVASIVENESS_UP                                 NA           NA
568 WEI_MYCN_TARGETS_WITH_E_BOX                                NA           NA
569 WELCSH_BRCA1_TARGETS_DN                          9.750000e-01 1.000000e+00
570 WELCSH_BRCA1_TARGETS_UP                          9.850000e-01 1.000000e+00
571 WEST_ADRENOCORTICAL_TUMOR_UP                     9.970030e-01 1.000000e+00
572 WHITFIELD_CELL_CYCLE_M_G1                        9.970030e-01 1.000000e+00
573 WINNEPENNINCKX_MELANOMA_METASTASIS_UP                      NA           NA
574 WNT_SIGNALING                                    3.425641e-01 7.173641e-01
575 WNT_UP.V1_DN                                     1.216080e-01 3.648241e-01
576 WNT_UP.V1_UP                                     5.864198e-02 2.128335e-01
577 WONG_ADULT_TISSUE_STEM_MODULE                    6.763972e-08 5.015002e-06
578 WONG_EMBRYONIC_STEM_CELL_CORE                              NA           NA
579 WONG_IFNA2_RESISTANCE_DN                         1.518325e-01 4.236615e-01
580 YAMAZAKI_TCEB3_TARGETS_DN                        5.964036e-01 1.000000e+00
581 YAO_TEMPORAL_RESPONSE_TO_PROGESTERONE_CLUSTER_13           NA           NA
582 YOSHIMURA_MAPK8_TARGETS_DN                       8.901099e-01 1.000000e+00
583 ZHANG_BREAST_CANCER_PROGENITORS_UP               1.000000e+00 1.000000e+00
584 ZHANG_GATA6_TARGETS_DN                           7.150480e-02 2.448169e-01
585 ZHANG_TLX_TARGETS_36HR_DN                                  NA           NA
586 ZHANG_TLX_TARGETS_60HR_DN                                  NA           NA
587 axonogenesis_Yang_etal                           4.240740e-05 8.151644e-04
588 hESC_NAIVE_SMITH_CELL2018                        9.009009e-01 1.000000e+00
589 hESC_PRIMED_SMITH_CELL2018                       3.929663e-04 4.248948e-03
    log2err     ES          NES        size
1   0.070789909 -0.45228800 -1.1529448  36
2            NA  0.11013996         NA 498
3            NA  0.12459045         NA 448
4   0.004808996 -0.22095493 -0.5950063 121
5   0.000000000 -0.18666594 -0.5054019 158
6   0.407017919 -0.56099154 -1.4748692  60
7   0.161978949 -0.48858697 -1.2932507  72
8   0.072535186 -0.40811314 -1.0997009 119
9   0.007739273 -0.23679610 -0.6347011  98
10  0.146416238 -0.53633427 -1.3506575  33
11  0.037458421 -0.36609335 -0.9141270  30
12  0.156312403 -0.66171853 -1.4108906  10
13  0.380730401 -0.46404327 -1.2651937 210
14  0.006839067 -0.24553307 -0.6638086 138
15  0.044418115 -0.40922366 -0.9374459  16
16  0.271288555 -0.62868078 -1.5072309  21
17  0.049890736 -0.42898131 -0.9998899  18
18  0.000000000 -0.13683562 -0.3763483 357
19  0.575610261 -0.53773827 -1.4606767 189
20  0.076674687 -0.39845397 -1.0836430 199
21  0.826657301 -0.63634987 -1.7231868 155
22           NA  0.09472565         NA 438
23  0.007880314 -0.24706396 -0.6653150 121
24           NA  0.16045699         NA  97
25  0.000000000 -0.20666952 -0.5696019 388
26  0.659444398 -0.58647930 -1.5892256 151
27  0.074175897 -0.39795458 -1.0798033 178
28  0.000000000 -0.22663075 -0.6220018 300
29  0.031205297 -0.33752283 -0.8856599  54
30           NA  0.14647836         NA 131
⋮   ⋮           ⋮           ⋮          ⋮
560 0.000000000 -0.1967496  -0.5416008 377
561          NA  0.1917451          NA 136
562          NA  0.1634681          NA 193
563 0.002041300 -0.2196609  -0.5974943 196
564 0.017076345 -0.3084695  -0.8369375 177
565 0.035391062 -0.3553398  -0.9641024 174
566 0.002041300 -0.1731659  -0.4664179 124
567          NA  0.1384998          NA 208
568          NA  0.1177046          NA 429
569 0.007450093 -0.2375586  -0.6354862  86
570 0.005814576 -0.2290068  -0.6156014 108
571 0.002501325 -0.2281538  -0.6197876 191
572 0.002501325 -0.1725826  -0.4609104  82
573          NA  0.2292172          NA  96
574 0.064503125 -0.4404958  -1.1257355  37
575 0.123257226 -0.4892977  -1.2803252  50
576 0.186432558 -0.5540445  -1.4052716  35
577 0.704975715 -0.5520098  -1.5114241 264
578          NA  0.1728569          NA 204
579 0.266350657  0.4093589   1.3177531  10
580 0.037536291 -0.3577371  -0.9641017 114
581          NA  0.1909956          NA  86
582 0.016030435 -0.3046965  -0.8277772 187
583 0.000000000 -0.1458990  -0.3994846 260
584 0.170932335 -0.5629592  -1.3811123  25
585          NA  0.2494164          NA 122
586          NA  0.1647485          NA 160
587 0.557332239 -0.7747408  -1.8967659  24
588 0.022869397 -0.2677615  -0.6182475  17
589 0.498493109 -0.7719593  -1.7824144  17
    leadingEdge
1   ALCAM,FGFR1,PFKP,MTSS2,FOXA2,UPP1,ALDOC,CEBPB,CYB561,TGFBR2,ACVR1,PELI1,MAN1A1,ITGA6,HK2
2   TMEM109,CHMP2B,PTTG1IP,CHCHD1,GRN,HMGB2,VAMP5,LLPH,RPF1,MARVELD2,ABHD16A,MFAP1,PAK1,MET,SCNM1,MCM4,CHMP1B,CYB561D2,ACTL6A,TYMS,STAMBPL1,HARS2,EIF1B,RPL23A,GNPAT,COMMD2,IMPA1,SRP54,TMEM183A,VBP1,SLC38A9,LINC00467,LAMTOR3,HCFC1,DYNLRB1,VPS26A,RPS27A,IRF6,KIFAP3,TMED7,RPL14,IL32,DAD1,VAMP7,MRPL13,VPS25,ORC3,PHF23,ZNF83,MRPS33,SNRPC,BOLA1,BTG3,RPLP1,PEX2,CCDC117,NFE2L2,STAG2,CASK,AQP11,HSD17B11,SMARCE1,HSPA14,XRCC1,IRAK1,RFX5,C12orf65,TMED5,HNRNPR,SMC3,ROCK2,TOX4,CNPY3,SUB1,SMNDC1,TSC22D2,PURA,ZFP36L1,TIGD5,C16orf91,ZXDB,CISD1,ABHD5,SPNS1,MRPL50,FADD,TFIP11,TALDO1,ATP6V0E1,IDI1,RNF26,NDUFB5,PON2,PRPF3,TESK1,KANK2,CKLF,RRM2B,ALG14,BZW2,BMI1,MRPS7,TATDN1,ANKMY2,SORT1,ZBTB33
3   RPS25,PTTG1IP,CHCHD1,GRN,HMGB2,DDX46,PFN1,ZMYND19,NUDT1,VAMP5,NDUFA12,LLPH,ABHD16A,SNRPF,MFAP1,SCNM1,MCM4,CHMP1B,ACTL6A,TYMS,STAMBPL1,HARS2,EIF1B,RPL23A,GNPAT,SPTSSA,C1orf198,DYNLL1,RAB22A,TMEM183A,RPL30,CHPT1,VBP1,SLC38A9,HTATSF1,DPY30,POGK,C16orf87,DYNLRB1,RPS27A,IRF6,TFRC,KIFAP3,TMED7,RPS13,SPCS2,DAD1,VAMP7,VPS25,SNRPC,BOLA1,BTG3,PEX2,CCDC117,DNAJC9,CASK,AQP11,HSD17B11,HSPA14,SLC39A1,IRAK1,DCTPP1,RFX5,CNN3,NDUFA8,UBB,TARS2,CDC42EP4,HNRNPR,SMC3,ARL1,ROCK2,CNPY3,HAUS4,PURA,MLH1,TIGD5,ZMPSTE24,ABHD5,WDR55,RPL10A,FADD,EXOSC5,TFIP11,ATP6V0E1,IDI1,RNF26,RDH10,NDUFB5,VPS28,TESK1,SNRPB,CKAP4,CKLF,ALG14,BZW2,BMI1,TFDP1,TATDN1,ANKMY2,MTX1,POLR2C,CORO1B,BTF3,TIMELESS,LSG1,LARS,SUPT4H1,CETN2,CTCF,RPL26L1,MRPS27,CDC5L,H2AFX,VPS29,IARS2,SLC9A6,CAP2,PRC1,CHMP5,YIF1B,LMNA,NOL7,TMEM167B,GPN1,OSTC,PAK1IP1,SF3B4,TIMM8A,IFRD2,ATP6V0C,TMTC4,APEX2,DCAF12,FAM120AOS,KIAA1191,GNG10
4   VLDLR,PDGFB,DUSP6,LRP2BP,PPIL6,MMP11,PIAS2,TIMP3,CSNK1E,BTG1,SFI1,IL20RA,YARS,KCTD17,AHI1,XPOT,CHEK2,WASF1
5   HAS2,ASNS,BMP4,FUT1,C5AR1,LPCAT1,SNAPC1,ZNF331,TSEN34,CASD1,PVT1,GARS,TCFL5,FAM117A,DMPK,RUVBL2,GYS1,PON3,TRRAP,PRMT1,ANXA13,ZNF787,ZNF460,EML2,DUSP3,ZNF264,DOCK4,MBOAT7
6   GSDMA,TNFRSF19,IRS1,SLC18A1,MLXIPL,PROM1,PDZRN3,PHLDA2,NID1,VCAN,PSAT1,SLCO3A1,FKBP10
7   TESC,DUSP10,HLA-DQB1,C3orf52,KRT23,KCNQ1,CPE,HBEGF,GLDC,BMP8B,TTLL1,SYT17,PDK3,HOXB3,DUSP8,ABCA7,RASD1,ALDOC
8   MAP1B,RBP1,PTPRN2,MME,KCNH2,ADM,BMP4,QSOX1,TIMP2,GLDC,MGLL,LY6E,PDLIM4,DUSP2,KIF3C,PHLDA1,SLC16A1,FYN,CDC42EP3,ASB13,RRP12,TRAP1,RUVBL1,E2F5,SLC39A6,PDIA5,HERPUD1,TARBP1,ADCY3
9   CA9,TUBB3,VCAN,VKORC1,TUBA1A,GOLT1A,SCD,TUBA4A
10  VSNL1,PRNP,SAMD5,FAM216A,SLC41A1,ARHGAP25,SLCO3A1,CACHD1
11  CXCR4,VCAN,LIG4,YARS,FADS1
12  PEG10,SGCE,SEMA3A,MT1A
13  ETV5,SMOC2,VLDLR,ISG20,SLC25A27,SLC7A11,GALNT14,RRAGD,DDIT4,H19,NCALD,ADM,DUSP6,PRUNE2,PFKFB3,BHLHE40,PARP8,DYNC2H1,HLA-DMA,P4HA1,SPRY2,CGNL1,GBE1,KDM4B,MZF1,DMXL2,CRYM,TFPI,MMP24,PDK1,PDK3,FAM110C,PITPNC1,DPP4,PHLDA1,BTG1,AMN1,SEMA4B,PCSK6,FAM13A,SPRY1,GDF15,LAMB1,SCD,NEBL,ALDOC,GLCCI1,MSI2,CASZ1,ASMTL,ZNF780B,PKD2,DNAH12,TPCN1,MYEF2,HGD
14  MAP1B,TUBB3,COTL1,PDLIM7,AREG,TIMP2,PRSS23,TUBB6,MYBL1,TUBA1A,CDC42EP3,TUBA4A,SLC7A5,NEK2
15  COTL1
16  RBP1,FGFR1,DUSP6,PEG10,KHDRBS3,AREG,TIAM1,CEP170
17  CPE,EPHX1,PROCR,EGR3,ISG15,ARL4A,PPP2R2A
18  CADM1,RAB3A,SLC25A27,SLC22A3,TIMP1,BAIAP2,DUSP4,MZF1,DMXL2,ITPR1,CDCA7L,UBE2S,HOXB4,LENG8,MYCBP2,EFHC1,TUBA1A,DNAJC6,ME3,ABCA7,FYN,GDF15,USP6NL,NCS1,WDR62,INSIG2,NEK2,NLRP2,ZSCAN5A,BAG3,CCND1,GOT1,AHI1,ODF2,PPP1R10,HSPA13,E2F5,PDXP,RUNX1,BBS2,ARL4A,CHEK2,REEP1,ARHGAP8
19  FZD10,PLXND1,COL4A5,MKX,SHISA6,ANKRD18A,MAGI2,FOXQ1,PPM1E,RASSF5,NRCAM,INHBB,STC2,SLCO4A1,TMOD2,ADM,SLC22A3,NEUROD1,KCNQ1,SOX21,EPHB3,PGM5,FOXA2,PCSK1N,CD44,GAD1,SETD7,GABRA2,ELAVL2,DPY19L2,HOXA3,GADD45G,SGPP2,BAIAP2,DMRT2,DUSP4,RIMKLA,DLL4,SLC1A4,MT1A,NFIX,HLA-A,CSNK1E,NAV2,HOXB3,SIM2,TUBA4A,KIAA1324,IL20RA,EFNA3,GRK5,CASZ1,PIR,LGR5,ABTB2,TBCB,EGR3,HHLA3,GALNT10,STK17A,B4GALT6,RGS10,ATF3,SOX5,HYOU1,PPP1R10,ZNF503,IER5L,INTU
20  ROBO1,TUBB2B,VSNL1,ETV4,RAB3B,SLC6A8,KIF5C,FGFR1,PROM1,GAL,GAD1,EGLN3,MTHFD2,SPRY4,HAS3,ELOVL6,MGST1,GLDC,FOXO1,CACHD1,CAPRIN2,PDK1,PODXL,ZNF589,PIM2,PITPNC1,SOX2,NFE2L3,SLC16A1,LRP8,PMAIP1,HOMER1,BCL2L12,JARID2,NTHL1,MARS,GPR19,DMKN,USP44,POLR3G,FKBP5,LRIG1,RUVBL1
21  FZD10,SMOC2,COL4A5,MKX,EPHA4,SHISA6,ANKRD18A,PTPRN2,NOTUM,NPAS2,FOXQ1,PPM1E,SLC25A27,RASSF5,MLXIPL,STC2,GRB10,SEMA4F,TMOD2,DUSP6,SLC22A3,ADAMTS17,NEUROD1,KCNQ1,LEF1,PRUNE2,EPHB3,PGM5,FOXA2,CYP39A1,DTNB,PARP8,GABRA2,ELAVL2,RAPGEF4,DPY19L2,HOXA3,SLCO3A1,SGPP2,DMRT2,ADAM15,DUSP4,RIMKLA,DLL4,SLC1A4,MT1A,NFIX,HLA-A,SKAP1,NAV2,HOXB3,TTLL7,SYT7,DUSP8,SIM2,CBX4,TNFRSF1B,LAMB1,RPS6KA2,DYNC1I1,KIAA1324,OSBP2,EFNA3,GRK5,CASZ1,PIR,LGR5,ABTB2
22  KHSRP,RPS25,AKAP9,RBBP8,ENTPD7,CACYBP,SNX3,SEC62,PFN1,WDR46,METTL1,PTOV1,DDX5,DCAF11,MFAP1,ALDH18A1,ZDHHC3,USP1,MYCBP,H2AFY,CEPT1,CYB561D2,YY1,GNPAT,SCO1,SRP54,FKBP2,IER2,SUPT16H,ZNF136,RPS6KA5,SRP68,COIL,ZFPL1,RPS27A,FTSJ1,TLE3,CIR1,RPS13,SLC39A7,IFNGR1,SAP18,ATP6V1D,SQSTM1,HNRNPL,TGIF2,MOCS3,PKN2,FLOT2,PDCD10,RPLP1,MOCS2,UBE2K,RNF141,AP4M1,SARS,RGL2,HSPA14,RPL5,SCAND1,UBL3,RFX5,MGAT2,TP53,CBX5,MED20,ARL1,UXT,ZMPSTE24,HNRNPA1,RAB8A,PNO1,ELOVL1,NCBP1,NCL,NUBP2,MSH2,CAPZA1,NDUFB5,AP4S1,PRPS2
23  ISG20,AMPD3,TERT,BMP4,SLC9A3R2,MGST1,RGS2,FOSL1,PIM2,EIF5A2,PSEN2,BCL2L12,NTHL1,TGFB1,MTHFR,SRM,CCND1,EGR3
24  MYBL2,TMSB10,MAGOHB,TYMS,PPIL1,COX5A,EZH2,H2AFV,TFRC,LBR,PDCD10,PURB,STMN1,HSPA14,GPSM2,CDT1,FANCE,MSH2,NDUFB5,NDC80,RRM2,GINS3,ASF1A,RAD51,PRC1,SNRPD1,PROSER1,TP53BP2,SPAG5,ARF1,PSMA3,HDAC2,AGFG1,CNIH4,FAM49B,PKMYT1,GGCT,MCM3,KDELR2,ILF2,CDCA5,SUV39H2,GDI2,TMEM14A,PCNA,BIRC5,RFC4,PRIM2,DBF4
25  FZD10,HAS2,KCNMB4,ALCAM,FGFR1,SLC7A11,PRNP,SPRED1,DUSP6,VCAN,FBXO16,EGLN3,ELAVL2,GADD45G,FOXO1,CACHD1,ST3GAL2,KDM3A,SNAPC1,CSNK1E,SOX2,MAPRE2,BTG1,NFE2L3,ZNF331,ARRDC3,SUGP2,SPIRE1,SASH1,NEBL,PSEN2,SLC7A5,JARID2,ABTB2,SUFU,CCND1,EGR3,B4GALT6,RGS10,IGFBP2,HLTF,USP44,POLR3G,ATF3,SFXN1,USP49,PPP1R10,IER5L,HSPA13,PCSK5,ZNF516,TRIT1,PTPN3,AVEN,EEF2,SLC3A2,SDCCAG8,ROR1,PRKRIP1,BAMBI,SCAF1,MED25,FEM1A,ZCCHC14,TAF15,AP2A1,UBR1,SNAPC3,PNISR,USO1,TCF7L2,POLR3E,MDC1,WDR77,GGA1,DNM2,NME7,WDFY2,CABLES1
26  FZD10,COL4A5,MKX,EPHA4,SHISA6,ANKRD18A,NPAS2,PPM1E,RASSF5,NRCAM,CDH13,BHMT,TLL2,SEMA4F,SLCO4A1,TMOD2,ADM,DUSP6,NEUROD1,SOX21,LEF1,GRIN2B,NKD1,EPHB3,PGM5,FOXA2,PCSK1N,CD44,PYCARD,SETD7,GABRA2,RAPGEF4,DPY19L2,GADD45G,SGPP2,DMRT2,MGLL,DUSP4,RIMKLA,DLL4,SLC1A4,MT1A,NFIX,LRRC8C,NAV2,HOXB3,SIM2,NHS,TNFRSF1B,TUBA4A,KIAA1324,EFNA3,CASZ1,PIR,LGR5,EFNB1,ABTB2
27  SMOC2,COL4A5,TCF4,CELF2,FGFR1,GRB10,PRNP,NAB2,RECK,BHLHE40,LPIN1,HES6,PTPN13,ITPR2,ELAVL2,SERPINE2,ARF5,ST3GAL2,LAMA2,SERPINB9,SSBP2,FKBP10,MT1A,IFT81,GAMT,TIMP3,NFIX,NUCB2,VKORC1
28  RGS16,HAS2,ALCAM,SMOC1,ADM,DUSP6,TIMP1,NID1,HBEGF,CD44,MTHFD2,PSAT1,SLCO3A1,GBE1,GK,TUBB6,CDCA7L,NGEF,FOSL1,EREG,PTPRE,SLC2A1,PHLDA1,ODC1,LRRC8C,SEMA4B
29  GAL,MTHFD2,ELOVL6,MGST1,CACHD1,TUBB6,PODXL,SLC16A1
30  YWHAE,HNRNPU,HNRNPA2B1,CDC23,DKC1,H2AFY,TYMS,RAB22A,VBP1,TARDBP,HNRNPD,TFRC,FEN1,WBP11,KLHL23,PAIP1,MED14,HNRNPR,SGMS2,ASF1B,RFC5,SFPQ,RRM1,RRN3,TFDP1,RRM2,YTHDF1,KIF11,SMC4,SEC23A,CCDC15,TRA2B,SNRPD1,NFIB,CDC6,NONO,PLK4,ELAVL1,PSMD10,CCNA2,DLGAP5,PAK2,SMS,RCOR1,DEPDC1,TPX2,MEAF6,RMND5A,TSR1,PATL1,FBXO3,UBQLN2,PPP2CA,EIF4A3,ARPP19,CDYL,RAE1,BIRC5,PTGES3,RFC4,DBF4,CSE1L,PHF10,ANKRD54
⋮   ⋮
560 C4orf47,MKX,LOXL1,HIVEP3,MSH4,CGREF1,PRNP,NID1,UQCRHL,CCDC85B,HOXA3,ABCB9,MGST1,ITPRIP,INPP1,ST3GAL2,NR2F1,SEC24D,MYCBP2,SLC25A25,BNIP3L,FAM13A,CREB3L2,ARHGAP29,PLOD1,RASSF6,USP6NL,EIF4G3,SCD,EPB41L2,WDR62,TTL,MAPKBP1,C2orf76,KLHL25,LDLRAD3,TBCD,GARS,FBXO31,SMYD3,MARS,KSR1,CSNK1D,CD302,DDIT3,SFXN1,CALU,CYTH1,FAM102A,ABCB8,POLR3H,POLR2H,TRIT1,SLC45A4,ELMOD3,STK40,PPP2R2A,EEF2,CCDC134,MID1IP1,CCDC18,TMEM116,R3HDM1,ACYP2,SCAF1,TSGA10
561 RRP7A,SLC35D2,MARVELD2,KLF5,JTB,CAMK2N1,POR,TMEM30B,MECOM,IMPA2,CISD3,CHPT1,VPS37B,MRPS18A,EPS8L2,EBP,VSIG10,HIP1R,TOMM40,SLC35A3,GNA11,RPS6KA1,STARD10,TNIP1,TMEM125,SCAMP2,BTBD3,LSM7,LZIC,PPDPF,TALDO1,ZGPAT,MED16,BZW2,FAM174B,TRAF4,MRPL14,POP7,ARRDC1,ALAS1,ARPC5L,BPHL,PWWP2B,NET1,FA2H,EPHB4,ARHGAP27,TXN,BAG1,MYO6,TPT1,GIPC1,ERBB3
562 FXR1,AKAP9,SNX6,DDX46,RPF1,HMGCS1,ZDHHC5,SH3GLB1,DKC1,OCLN,CHMP1B,MRPS31,TARDBP,SRP68,RBM15,COBLL1,DLST,RBM25,MTIF3,DDX20,PURB,MED6,CASK,CPSF2,ZFAND2A,WDR6,FBLIM1,KALRN,CCDC58,PTPRK,CGN,KAT5,TMOD3,RAB14,BCAS2,SIPA1L2,ATP6V0E1,SPTBN1,INSR,ACTR2,WDR41,ATP6V1C1,SUGT1,LARS,RNFT1,CAPZA2,SAR1A,LYRM2,IQGAP1,NCOA7,NBR1,SAP30BP,FUNDC1,DUSP23,GSTCD,CCDC127,CCDC15,DYNC1LI2,NOL7,CLTA,POLB
563 CXCR4,COTL1,DDIT4,PROM2,KIF3A,LPCAT1,AKR7A3,C9orf16,TIAM1,MIPOL1,SLC2A1,LPGAT1,SYT7,CREB3L2,USP6NL,NEBL,ANKRD13D,RHOQ,ABTB2,ENAH,SERTAD1,ARG2,IGFBP2,CYB561,SFXN1,GAS5,NEAT1,EMP2,PACRGL,N4BP2L2,CTNNB1,MAP3K3,NAP1L1
564 ETV5,ETV4,KIF21B,PFKP,SLCO4A1,DUSP6,MPP6,PSAT1,LPCAT1,LY6E,GK,SLC1A4,PDK1,PTPRE,PIM2,SLC2A1,TIMP3,PHLDA1,GPT2,SLC16A1,ARHGAP44,LRP8,CDC42EP3,MOB3A,NCS1,SCD,TUBA4A,SLC7A5
565 FJX1,BNIP3,PRAME,LOXL1,STC2,GALNT14,UCHL1,SLCO4A1,DUSP6,KIAA0895,GAL,PRR7,SACS,ELOVL6,TBC1D4,LY6E,ARSJ,DUSP4,PRSS23,MYBL1,MOK,GDF15,EIF4G3,CASD1,SRM,C11orf24,SLC4A7,OSTM1,POLR3G,SFXN1,ACOT9,E2F5,GLA,PLAGL1,OGFRL1,SLC25A37,BBIP1,BAMBI,HMGA1,MICA,HAUS6,MAN1A1,PNISR,NT5E,EGFR,HK2,SRPK1
566 CELF2,ABCG1,CD44,MYADM,LY6E,BTG1,BNIP3L,HABP4,INSIG2,MYEF2,PDE6D,TTBK2,TRAP1
567 HMGB2,SEC62,ADH5,FKBP3,HNRNPU,HMGCS1,HNRNPA2B1,DDX5,PAK1,RPS8,TMSB10,ARPC3,PSMA7,IER2,BRD3,RPL30,TARDBP,DPY30,EZH2,BRD7,PAF1,KIFAP3,RPL14,MOV10,SAP18,PSMA4,RPA2,HSD17B4,NFE2L2,UBE2K,CPSF2,SDHA,CTSZ,TUBB,CBX5,HNRNPR,PSMA2,SUB1,ABCF3,RRAS2,MDP1,PITPNB,CAPZA1,SPTBN1,RPL6,NUCKS1,ATP6V1C1,ACAT2,TEX10,EIF4H,CTCF,RPS14
568 CHCHD1,POLE2,CACYBP,RPP30,DDX46,ZMYND19,LLPH,HNRNPU,CALM3,AHSA1,CNOT7,ATL3,SNRPF,TFAM,GPD2,DKC1,CERS6,TMEM177,PSMD13,SMC2,MCM4,CHCHD4,LACTB2,STAMBPL1,SCO1,SLC20A1,BID,TMX1,LSM6,GFM1,HELLS,STARD7,C4orf46,TFRC,EHD4,PAPOLA,EBP,MRPL15,TMEM19,ANAPC5,DDX20,HAUS2,TOMM5,MYLK,FAHD1,BAG2,HSPA14,SKP2,IRAK1,DCTPP1,TUBB,MRPL30,TMED5,MRPL47,FASTKD2,ZNF330,TOX4,MRPL35,PDCD6,CCDC58,ASB9,SMNDC1,RB1,ZMPSTE24,CASP8,CISD1,PHF5A,SFPQ,MRPL50,PNO1,ISOC1,RFC3,MCMBP,ATP6V0E1,MSH2,UMPS,IDI1,FANCC,BRIX1,NOP16,VRK1,PHB,THAP5,DYNLL2,CKAP4,MRPS35,GLRX2,DYNC1LI1,ASCC3,PNPO,RRM2,OTUD6B,MRPL14,YDJC,POP7,TAF9,NUDT15,ATP6V1C1,LSG1,MANEA,SKA3,ARPC5L,DIAPH1,INO80C,NUP35,LEPROTL1,NOX1,COMMD8,BAZ1A,DCBLD2,ZBTB38,TXNDC9,TAF13,NOP14,USP14,TMEM97,SNRPD1,TPRKB,MRTO4,HAT1,CDC6,MRPL19,ACVR1B,C12orf49,MRPL22,CTTN
569 SLC6A8,HK1,GAL,CCDC85B,MGST1,MANF,PPM1F,SLC7A5,SRM,CCND1,POLG,TRAP1,SMARCA4,RABEPK,FDFT1,PKN1,CAD,SCAP,SRPK1,BOP1,PPAT
570 TUBB3,BNIP3,ALCAM,NID1
571 TUBB3,STXBP1,FGFR1,SLC7A11,PCYOX1L,LPIN1,MTHFD2,ANGPT2,ELOVL6,KDM4B,UBE2S,KIF3C,DNAJC6,SLC16A1,PCSK6,SCD,PMAIP1,HOMER1,SLC7A5,NEK2,IARS,MARS,PIR
572 RAB3A,TICAM2,UBE2S,GDF15,USP6NL,NCS1,ZSCAN5A,BAG3,ODF2
573 PSMC3IP,CACYBP,SMC2,MCM4,TYMS,ZWINT,H2AFV,MRPL32,TRUB2,PRPF38B,CNN3,ARF4,RFC5,NCBP1,GLRX2,NDC80,NCAPG2,RRM2,TIMELESS,KIF11,TARS,DCBLD2,PRC1,CEP55,CDC6,MRPS5,CCT5,SPAG5,DLGAP5,SPC25,SMARCA5,KNTC1,GEMIN6,HSPA4,MCM6,GINS2,ZNF367,ENY2,MRPS16,MAP4K4,KDELR2,CDCA5,TAF1A,PCNA,BIRC5,RFC4,PRIM2,HSPD1,VMA21,ATAD2,CHEK1,SRSF10
574 LEF1,CXXC4,NKD1,FOSL1,CSNK1D,CCND1,LRP5,NLK,CTNNB1,DIXDC1,BTRC,CTNNBIP1,GSK3B,WNT2B,KREMEN1
575 G0S2,ETV4,CD44,RSPH1,TSPAN5,TNNI3,ST3GAL2,CEACAM1,NGEF,PIM2,RASD1,ABCA1,CYTH1,ISG15,SERGEF,F10,SLC22A18,ATP7B
576 CD74,CHRNA7,KCNC3,PTPRO,INHBB,DTNB,TPK1,MAPRE2,GDF15,MAPKBP1,MST1R,CLEC16A,HYOU1
577 ROBO1,SMOC2,FBLN2,TCF4,COL18A1,RBP1,CADM1,STXBP1,MAGI2,VLDLR,FOXQ1,ALCAM,GABBR1,AMPD3,ADARB1,NRCAM,INHBB,ABCG1,PHLDA2,DDIT4,NAB2,ADM,LRP2BP,LGALS1,NID1,SLC9B2,SGCE,LRP4,EPHB3,HBEGF,BHLHE40,KHDRBS3,AK1,LPIN1,IQCH,KLF2,SLC41A1,UBE2E2,HOXA3,HLA-DMA,GADD45G,SLCO3A1,ELOVL6,MGST1,RGS2,MYADM,HDAC11,SCG5,DUSP4,LAMA2,PRSS23,WDR78,TUBB6,DUSP2,SSBP2,NR2F1,GNB5,CAPRIN2,TP53BP1,TTC28,TIMP3,CEP170,NFIX,PHLDA1,ANTXR2,PCLO,DUSP8,CBX4,FYN,RASD1,ARHGEF10,LAMB1,SCD,SASH1,ALDOC,ACTR3B,PHLPP1,MSI2,ARL3,PROCR,PKD2,PBX3,LGR5,RHOQ,BAG3,ENAH,CCND1,SERTAD1,DDIT3,DMD,CEBPB,ZNF23
578 PSMB6,POLE2,HMGB2,CYCS,ADH5,CKAP2,MYBL2,RPS8,SMC2,MCM4,PSMA7,MRPL16,YY1,TIMM13,RCC2,PRDX1,LSM5,VBP1,HELLS,MRPL15,NDUFB10,MRPL13,RPS23,HNRNPL,NDUFB8,TGIF2,RPSA,WBP11,RPA2,SARS,HSPA14,FAM136A,PRIM1,TP53,HAUS1,CISD1,HNRNPA1,PHF5A,RRM1,RPL10A,RFC3,NCL,MSH2,BRIX1,VRK1,FH,PHB,LSM2,NDC80,RRM2,FDPS,ALDH7A1,POP7,NDUFA9,BTF3,KIF11,CDK4,SMC4,SNRPD1,MRTO4,HAT1,CDC6,TIMM8A,MRPL11,NONO,PLK4,CCT5,SPAG5,CDC34,CCNA2,UQCRH,DLGAP5,SUMO1,CDKN1C
579 POR,MSH2,MRPS35,DPF2,HNRNPF
580 MAP1B,TUBB2B,COL18A1,UCHL1,GRB10,SPRED1,DUSP6,KLF2,ELAVL2,MT1A,CDCA7L,UBE2S,SLC2A1,SOX2
581 RPP30,FKBP3,MRPS18A,DYNLRB1,EBP,MRPL13,HNRNPL,OGFR,NDUFB8,MRPS33,C1D,PAFAH1B3,DPM3,NUDT16L1,TOMM5,MRPL35,NDUFB5,PSMG4,DAP,NDUFA9,GSR,LYRM2,ILVBL,NAB1,TXNDC17,VPS29,PMPCB,DNAJC15,GPN1,MRPL11,HDDC2,PRDX2,PCCB,CSRP1,NDUFS2,LAGE3,TMEM205,MRPL45,FAM49B,PQBP1,C9orf78,MRPL28,CHMP2A

### Loop for above

In [82]:
#Pos error- duplicates in module DEGs, and logfoldchange scores
#increase
RunGSEA <- function(local_corr_module, gset0) {
  rnk <- local_corr_module$logfoldchanges
  names(rnk) <- local_corr_module$names
  score <- rnk[!is.na(rnk)] 
  
  fgseaRes <- fgsea(pathways = gset0, 
                    stats = score,
                    minSize = 10,
                    maxSize = 500)#,
                    #nperm = 10000)
  
  fgseaRes$leadingEdge <- sapply(fgseaRes$leadingEdge, function(x) paste(x, collapse = ','))
  
  return(fgseaRes)
}

#res for each module
fgseaResults <- list()

#mod 0 -11
for (i in 0:11) {
    #name of the current local_corr_module
    module_name <- paste0("local_corr_module_", i)
    
    #GSEA for the current module
    fgseaResults[[paste0("fgseaRes_", i)]] <- RunGSEA(get(module_name), gset[['small']])
    
    #output file name
    ofile <- sprintf('GSEA.logfc_%s.txt', module_name, i)
    
    #gsea res to file
    write.table(fgseaResults[[paste0("fgseaRes_", i)]], file.path(gsea_dir, ofile), sep = '\t', quote = FALSE, row.names = FALSE)
}

Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“There were 71 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values. For such pathways pval, padj, NES, log2err are set to NA. You can try to increase the value of the argument nPermSimple (for example set it nPermSimple = 10000)”
Warning message in sprintf("GSEA.logfc_%s.txt", module_name, i):
“one argument not used by format 'GSEA.logfc_%s.txt'”
Warning message in preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam, :
“There are ties in the preranked stats (0.93% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.”
Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“There were 28 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values. For such pathways pval, padj, NES, log2err are set to NA. You can try to increase the value of the argument nPermSimple (for example set it nPermSimple = 10000)”
Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“For some of the pathways the P-values were likely overestimated. For such pathways log2err is set to NA.”
Warning message in sprintf("GSEA.logfc_%s.txt", module_name, i):
“one argument not used by format 'GSEA.logfc_%s.txt'”
Warning message in preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam, :
“There are ties in the preranked stats (2.18% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.”
Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“There were 73 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values. For such pathways pval, padj, NES, log2err are set to NA. You can try to increase the value of the argument nPermSimple (for example set it nPermSimple = 10000)”
Warning message in sprintf("GSEA.logfc_%s.txt", module_name, i):
“one argument not used by format 'GSEA.logfc_%s.txt'”
Warning message in preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam, :
“There are ties in the preranked stats (0.01% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.”
Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“There were 87 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values. For such pathways pval, padj, NES, log2err are set to NA. You can try to increase the value of the argument nPermSimple (for example set it nPermSimple = 10000)”
Warning message in sprintf("GSEA.logfc_%s.txt", module_name, i):
“one argument not used by format 'GSEA.logfc_%s.txt'”
Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“There were 59 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values. For such pathways pval, padj, NES, log2err are set to NA. You can try to increase the value of the argument nPermSimple (for example set it nPermSimple = 10000)”
Warning message in sprintf("GSEA.logfc_%s.txt", module_name, i):
“one argument not used by format 'GSEA.logfc_%s.txt'”
Warning message in preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam, :
“There are ties in the preranked stats (1.99% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.”
Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“There were 8 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values. For such pathways pval, padj, NES, log2err are set to NA. You can try to increase the value of the argument nPermSimple (for example set it nPermSimple = 10000)”
Warning message in sprintf("GSEA.logfc_%s.txt", module_name, i):
“one argument not used by format 'GSEA.logfc_%s.txt'”
Warning message in preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam, :
“There are ties in the preranked stats (0.72% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.”
Warning message in preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam, :
“There are duplicate gene names, fgsea may produce unexpected results.”
Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“There were 7 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values. For such pathways pval, padj, NES, log2err are set to NA. You can try to increase the value of the argument nPermSimple (for example set it nPermSimple = 10000)”
Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“For some of the pathways the P-values were likely overestimated. For such pathways log2err is set to NA.”
Warning message in sprintf("GSEA.logfc_%s.txt", module_name, i):
“one argument not used by format 'GSEA.logfc_%s.txt'”
Warning message in preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam, :
“There are ties in the preranked stats (0.02% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.”
Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“There were 2 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values. For such pathways pval, padj, NES, log2err are set to NA. You can try to increase the value of the argument nPermSimple (for example set it nPermSimple = 10000)”
Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“For some pathways, in reality P-values are less than 1e-50. You can set the `eps` argument to zero for better estimation.”
Warning message in sprintf("GSEA.logfc_%s.txt", module_name, i):
“one argument not used by format 'GSEA.logfc_%s.txt'”
Warning message in preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam, :
“There are ties in the preranked stats (0.01% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.”
Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“There were 4 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values. For such pathways pval, padj, NES, log2err are set to NA. You can try to increase the value of the argument nPermSimple (for example set it nPermSimple = 10000)”
Warning message in sprintf("GSEA.logfc_%s.txt", module_name, i):
“one argument not used by format 'GSEA.logfc_%s.txt'”
Warning message in preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam, :
“There are ties in the preranked stats (0.58% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.”
Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“There were 34 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values. For such pathways pval, padj, NES, log2err are set to NA. You can try to increase the value of the argument nPermSimple (for example set it nPermSimple = 10000)”
Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“For some of the pathways the P-values were likely overestimated. For such pathways log2err is set to NA.”
Warning message in sprintf("GSEA.logfc_%s.txt", module_name, i):
“one argument not used by format 'GSEA.logfc_%s.txt'”
Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“There were 49 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values. For such pathways pval, padj, NES, log2err are set to NA. You can try to increase the value of the argument nPermSimple (for example set it nPermSimple = 10000)”

Warning message in sprintf("GSEA.logfc_%s.txt", module_name, i):
“one argument not used by format 'GSEA.logfc_%s.txt'”
Warning message in preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam, :
“There are ties in the preranked stats (1.02% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.”
Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“There were 37 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values. For such pathways pval, padj, NES, log2err are set to NA. You can try to increase the value of the argument nPermSimple (for example set it nPermSimple = 10000)”
Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“For some of the pathways the P-values were likely overestimated. For such pathways log2err is set to NA.”
Warning message in sprintf("GSEA.logfc_%s.txt", module_name, i):
“one argument not used by format 'GSEA.logfc_%s.txt'”

In [76]:
fgseaResults[["fgseaRes_1"]]

    pathway                                          pval         padj
1   ABBUD_LIF_SIGNALING_1_UP                         4.934542e-02 2.873343e-01
2   ACEVEDO_LIVER_TUMOR_VS_NORMAL_ADJACENT_TISSUE_UP 1.000000e+00 1.000000e+00
3   AGUIRRE_PANCREATIC_CANCER_COPY_NUMBER_DN         9.980020e-01 1.000000e+00
4   AGUIRRE_PANCREATIC_CANCER_COPY_NUMBER_UP         2.587413e-01 7.455483e-01
5   AKT_UP_MTOR_DN.V1_DN                             7.807808e-02 3.577512e-01
6   AKT_UP_MTOR_DN.V1_UP                             6.587590e-03 7.220516e-02
7   ALFANO_MYC_TARGETS                               9.490509e-02 4.019087e-01
8   ALONSO_METASTASIS_UP                             4.595405e-01 9.842265e-01
9   ASC_SMITH_CELL2018                               7.435367e-01 1.000000e+00
10  BACOLOD_RESISTANCE_TO_ALKYLATING_AGENTS_DN       4.871309e-01 1.000000e+00
11  BACOLOD_RESISTANCE_TO_ALKYLATING_AGENTS_UP       3.382187e-02 2.305662e-01
12  BASAKI_YBX1_TARGETS_DN                           6.973027e-01 1.000000e+00
13  BASAKI_YBX1_TARGETS_UP                           5.354645e-01 1.000000e+00
14  BASAL_MONTORO                                    2.102534e-03 2.733294e-02
15  BECKER_TAMOXIFEN_RESISTANCE_DN                   1.637602e-02 1.387000e-01
16  BECKER_TAMOXIFEN_RESISTANCE_UP                   1.712120e-03 2.431050e-02
17  BENPORATH_CYCLING_GENES                          1.000000e+00 1.000000e+00
18  BENPORATH_EED_TARGETS                            2.834393e-05 9.320152e-04
19  BENPORATH_ES_1                                   9.920080e-01 1.000000e+00
20  BENPORATH_ES_WITH_H3K27ME3                       8.460095e-09 1.182298e-06
21  BENPORATH_MYC_MAX_TARGETS                        1.000000e+00 1.000000e+00
22  BENPORATH_MYC_TARGETS_WITH_EBOX                  5.914086e-01 1.000000e+00
23  BENPORATH_PROLIFERATION                                    NA           NA
24  BENPORATH_SOX2_TARGETS                           1.000000e+00 1.000000e+00
25  BENPORATH_SUZ12_TARGETS                          3.435109e-12 1.920226e-09
26  BERENJENO_TRANSFORMED_BY_RHOA_DN                 6.533467e-01 1.000000e+00
27  BERENJENO_TRANSFORMED_BY_RHOA_UP                 9.870130e-01 1.000000e+00
28  BHATTACHARYA_EMBRYONIC_STEM_CELL                 9.758065e-01 1.000000e+00
29  BIDUS_METASTASIS_UP                                        NA           NA
30  BIOCARTA_ALK_PATHWAY                             7.222222e-01 1.000000e+00
⋮   ⋮                                                ⋮            ⋮
562 WANG_LMO4_TARGETS_UP                             0.995004995  1.000000000
563 WANG_RESPONSE_TO_GSK3_INHIBITOR_SB216763_DN      0.917082917  1.000000000
564 WANG_SMARCE1_TARGETS_DN                          0.956043956  1.000000000
565 WANG_TUMOR_INVASIVENESS_DN                                NA           NA
566 WANG_TUMOR_INVASIVENESS_UP                       0.906093906  1.000000000
567 WEI_MYCN_TARGETS_WITH_E_BOX                      0.923076923  1.000000000
568 WELCSH_BRCA1_TARGETS_DN                          0.481518482  1.000000000
569 WELCSH_BRCA1_TARGETS_UP                                   NA           NA
570 WEST_ADRENOCORTICAL_TUMOR_UP                     1.000000000  1.000000000
571 WHITESIDE_CISPLATIN_RESISTANCE_DN                0.689095128  1.000000000
572 WHITFIELD_CELL_CYCLE_M_G1                        0.966033966  1.000000000
573 WINNEPENNINCKX_MELANOMA_METASTASIS_UP                     NA           NA
574 WNT_SIGNALING                                    0.693548387  1.000000000
575 WNT_UP.V1_DN                                     0.128514056  0.502373129
576 WNT_UP.V1_UP                                     0.007878092  0.083091572
577 WONG_ADULT_TISSUE_STEM_MODULE                    0.000062608  0.001590812
578 WONG_EMBRYONIC_STEM_CELL_CORE                    1.000000000  1.000000000
579 WONG_IFNA2_RESISTANCE_DN                         0.560975610  1.000000000
580 WONG_IFNA2_RESISTANCE_UP                         0.126450116  0.497786020
581 YAMAZAKI_TCEB3_TARGETS_DN                        0.993006993  1.000000000
582 YAO_TEMPORAL_RESPONSE_TO_PROGESTERONE_CLUSTER_13 0.053946054  0.298572714
583 YOSHIMURA_MAPK8_TARGETS_DN                       0.997002997  1.000000000
584 ZHANG_BREAST_CANCER_PROGENITORS_UP               1.000000000  1.000000000
585 ZHANG_GATA6_TARGETS_DN                           0.079414838  0.360917841
586 ZHANG_INTERFERON_RESPONSE                        0.082366589  0.368343387
587 ZHANG_TLX_TARGETS_36HR_DN                                 NA           NA
588 ZHANG_TLX_TARGETS_60HR_DN                                 NA           NA
589 axonogenesis_Yang_etal                           0.081081081  0.365518745
590 hESC_NAIVE_SMITH_CELL2018                        0.088726514  0.386613387
591 hESC_PRIMED_SMITH_CELL2018                       0.214922049  0.667203977
    log2err     ES         NES        size
1   0.202071709 -0.5047721 -1.3613999  46
2   0.000000000 -0.2324237 -0.6866907 492
3   0.002041300 -0.1838830 -0.5280511 125
4   0.077274697 -0.3720573 -1.0824347 189
5   0.157402899 -0.4573884 -1.2709435  71
6   0.407017919 -0.5090181 -1.4176253  76
7   0.141225120 -0.4113927 -1.1846568 137
8   0.049490487 -0.3558761 -1.0188776 117
9   0.028574398 -0.3229660 -0.8276416  25
10  0.203508959  0.1707856  0.9895349  32
11  0.261663522 -0.6723601 -1.5502538  12
12  0.030061810 -0.3229879 -0.9357601 173
13  0.042502318 -0.3415056 -0.9876702 165
14  0.431707696 -0.6736314 -1.7160876  24
15  0.352487858 -0.5989592 -1.5394197  26
16  0.455059867 -0.6420579 -1.6752021  29
17  0.000000000 -0.1475976 -0.4342914 369
18  0.575610261 -0.5034393 -1.4658103 209
19  0.004094922 -0.2291998 -0.6668161 189
20  0.747739663 -0.5705450 -1.6571513 178
21  0.000000000 -0.2284278 -0.6746122 468
22  0.037927147 -0.3348857 -0.9643867 136
23           NA  0.1784147         NA  82
24  0.000000000 -0.2145194 -0.6323083 393
25  0.898671232 -0.6194226 -1.7960410 175
26  0.033235931 -0.3278788 -0.9539052 189
27  0.005233221 -0.2664259 -0.7827907 318
28  0.008423594 -0.1901730 -0.5098212  41
29           NA  0.1765935         NA 136
30  0.195789002  0.2048287  0.8581899  16
⋮   ⋮           ⋮          ⋮          ⋮
562 0.003232439 -0.2316442 -0.6749939 212
563 0.013718352 -0.2841030 -0.8245233 177
564 0.009782498 -0.2721305 -0.7906485 182
565          NA  0.1091450         NA 116
566 0.014687435 -0.2909368 -0.8502723 236
567 0.013170214 -0.3003066 -0.8874263 486
568 0.047353425 -0.3551963 -1.0105732 107
569          NA  0.1336772         NA 128
570 0.000000000 -0.1454257 -0.4229622 187
571 0.037770500 -0.3802703 -0.8374722  10
572 0.008554694 -0.2360845 -0.6650929  90
573          NA  0.1546169         NA 100
574 0.030775260 -0.3281331 -0.8823513  43
575 0.119348441 -0.4602481 -1.2530009  51
576 0.380730401 -0.5421445 -1.4831885  54
577 0.538434096 -0.4793130 -1.4038691 265
578 0.000000000 -0.1847610 -0.5387405 224
579 0.043103683 -0.3926188 -0.9692589  19
580 0.130777138 -0.6103717 -1.3442263  10
581 0.003828521 -0.1981136 -0.5659060 113
582 0.191892240 -0.4325031 -1.2420057 125
583 0.002501325 -0.2092103 -0.6081315 185
584 0.000000000 -0.1290491 -0.3780225 257
585 0.159646702 -0.5486784 -1.3810600  21
586 0.165656695 -0.6420186 -1.4139224  10
587          NA  0.1918280         NA 123
588          NA  0.0813922         NA 167
589 0.160801401 -0.5868496 -1.4070887  15
590 0.150169802 -0.5313518 -1.3476860  23
591 0.093444922 -0.5332077 -1.2442362  13
    leadingEdge
1   LCN2,SCT,CAPN9,FGFR1,PSMB8,CD24,ALCAM,NMI,FBP1,CXorf56,JUNB,BCL3,IRF1,TAPBP
2   LCN2,TEAD2,TUBA1A,CAP2,IGFLR1,C12orf57,IRX3,PEA15,PFDN6,C8orf33,RPS21,COX7A2,CRY1,WIPI1,FOXQ1,IRAK1,MRPS21,COX6A1,EIF3J,ZMPSTE24,DDX21,TBC1D2,CES1,PSME3,EXOSC5,NDUFA7,PPIC,GRN,RNASEH2A,NHP2,ZMAT3,MRPS18C,C1orf53,PHPT1,NDUFB3,DOLK,NAA10,DYNLRB1,RPS25,PAK1IP1,SCNM1,DDX46,CDK5,MRPL36,UQCRB,NUP62,RRP36,MRPL33,TESK1,NDUFB6,RPP21,RRP15,NDUFAF2,TUBB4B,SCAMP3,CCDC167,MAN2B1,TRIM27,LAGE3,LSG1,ARSA,RPL35A,DHX16,MRPS17,SUV39H1,GNG5,EPHX1,SLC38A9,RPS13,SATB2,CD59,VPS25,HPS6,VPS28,ANKRD49,ADAT1,ZMYND19,PIP4K2C,YIPF1,EIF2B1,CDR2,TMEM199,UFC1,RRS1,MUC13,VAMP5,RPS15A,MAP1S,PDCD5,ATP6V0C,NOP10,TUSC2,SDF2L1,RPL26,LLPH,GPAA1,HS1BP3,NAT9,SRXN1,FRAT2,TCHP,FKBP5,CLN3,POGK,ETF1,GHDC,MEA1,WDR55,C1orf131,PSMD2,SAP30L,TIGD5,ITGAV,MMGT1,HIGD1A,MCTS1,PIGM,IFRD2,TIMM8A,RPS27A,NDST1,LSM10,SLC35B1,RPL30,DDAH2,KIFAP3,NEDD8,TMEM147,RPL36AL,RUVBL2,DCTPP1,CDC42EP4,CORO1B,SNRPF,DNMT1,C12orf45,RFX5,HIST2H2AC,DHX29,SUPT4H1,S100A10,GTPBP4,MCM5,KLF13,ESF1,DTYMK,AARS2,PPL,ERLEC1,TFDP1,AHCY,APEX2,CTCF,ABHD5,C1orf35,ZNF7,CHCHD1,MRPS18B,RPL23A,RANBP6,NDUFA12,UBLCP1,POLR2J3,DENND5B,TMEM183A,MAGOH,NUDT1,FADD,SET,SFXN2,NANS,SH3PXD2A,LYAR,ZMAT2,NR2C2AP,COPE,KIAA0556,MAP2K2,SRSF2,UCK2,C5orf51,SF3B4,MAPRE1,DAD1,ATG3,SURF1,CNPY3,DVL3
3   BLOC1S1,ZNF593,CACNB3,VDR,ORMDL2,RARG,SNRPD3,SMPD2,MFSD5,E2F2,POLR2F,KITLG,SLC48A1,ZBTB24,MAK16,LYPLA2,AMDHD2,HECA,ATP6V0C,QRSL1,DDX23,KCTD17,PRPF31,MTAP,SRRM1,ASCC2,PRKAG1,PFDN5,BCR,RPS6KA1,HMGN2,MECR,RANBP6,YWHAH,SCAF11,THOC5,XPC,AMD1,C12orf10,YTHDF2,SMAGP,DEPDC5,PPP5C,SGSM3,TOMM22,PISD,LSM3,TXNL4A
4   ID1,PLEKHA4,DOCK4,EXOSC4,NDUFS6,OPLAH,SIX5,GRWD1,CD3EAP,NMT1,IRF3,RPS21,DGAT1,NAPA,PSME3,TSTA3,GRN,NR1H2,NOSIP,ARFRP1,NFKBIB,BRD9,ZNHIT1,LRRC59,PRPF6,ZGPAT,NUP62,PLOD3,SPATA20,G6PC3,EPN1,MBOAT7,RCN3,ANXA13,DMPK,OPA3,STRN4,ORAI2,TLN1,ZNF444,GSDMD,ZC3H3,VPS28,SHARPIN,MRPS12,PAF1,RSAD1,NKIRAS2,ZNF580,SNRPD2,PPP2R5D,GPAA1,ASL,SLC39A4,BAX,NUCB1,U2AF2,CYHR1,AARSD1,PDK2,NME1,TPD52L2,MLX,SLC35B1,INTS1,AP4M1,UPF3A,RUVBL2,CRCP,MYL6,EIF3K,DDT,MTAP,ATXN7L1,FIS1,UCKL1,SCRIB,SARS2,ZNF787,PON2,AP2S1,ZDHHC24,MICALL2,PSMA7,PRKD2,TTF2,CREB3,NUDC
5   PHGR1,TNNC2,PROM1,HPGD,NR4A3,TYMP,GSDMA,CAP2,ERF,SLC18A1,IL13RA1,RPS6KB2,RTKN,SNHG6,AMPD2,RNF25,SLCO3A1,MAZ,BCS1L
6   CXCL1,EDN1,KRT23,CDKN2B,TMCC3,HLA-DQB1,DUSP10,CPE,KCNQ1,RASD1,CD55,DUSP1,GIPC1,ATF3,MVP,PARM1,CTNS,NFKB2,JUNB,TPRN,KLF6,GCH1,MAN2B2,ANXA13,NOL12
7   ID3,EMP1,SMPD1,RBP1,LY6E,CSRP1,DUSP2,MME,PLEC,CLCN7,SYNGR2,TOMM40,NOP56,ABCF2,VCL,DDX21,MVP,SURF2,PDCD11,CDX1,TCOF1,IMPDH1,ITGA7,SDC1,GPR143,NBL1,IRF1,CLCN2,FARSA,PPP1R15A,MGLL,CD59,RRP12,HS3ST1,EIF2B1,AATF,MYCBP,FYN,TTLL12,AFAP1,ATP8A1,TRIP6,TCF19,LTBP1,GNAI2,SLC20A1,FKBP4,PAFAH1B3,DNAJC11
8   EMP1,COX6B1,TUBA1A,UBL5,CDKN1A,SEMA5A,ATP6V0D1,TIMM10,RPS10,AKT1S1,HSPA8,TP53I3,RCBTB2,HSPB1,COX8A,NDUFB11,NHP2,DHRS11,NDUFB3,PRDX5
9   VSNL1,DDX46,TCOF1,SLCO3A1
10  CCNG1,TCEA1,UBXN7,TUBB,MTRR,YARS,VEZF1,H3F3B,LRPPRC,SLC25A6,ATRX,PHF8,FADS1,HNRNPH1,TLN2,PDCD6,RPL24,TSPAN3,TUBGCP4,CS,CCT5,CAD,PTTG1IP,SFPQ,SRSF2,SMPDL3A,FZD7,SUPT6H,CDC42EP1,ZNF124,ATP8A1,TRIM28
11  MT2A,MT1X,TPM1,MT1A,SEMA3A
12  FOLR1,LCN2,TFPI,NCALD,TSPAN1,EGR1,PRUNE2,CD55,MAFF,HES1,SULT1C2,TMC5,NAV1,RPL37,MBOAT2,RPL31,PARP8,JUNB,DUSP5,SEZ6L2,SPATA20,IER2,TP53INP1,RBMXL1,HECW2,BICD1,TM7SF2,NAA38,SLC1A1,ALDH1A2,FOS
13  MT1G,MT2A,SMAD7,POLR2L,MT1X,THBS1,MT1F,TUBA1A,CCND3,FLNA,FGFBP1,NDUFS6,TUBB2A,TNFRSF21,SFN,TUFT1,IRAK1,WWC1,DHRS11,AREG,TPM4,RUSC1,EHD4,COMMD4,MYO19,RHOD,NFKBIA,TUBB4B,ARPC5L,CDA,PLCB4,PINK1,RBM19,CYTH3,S100A11,RRS1,GLRX2,EPHA2,ANXA3,RANGAP1,DDX39A
14  HPGD,EMP1,ID1,SH3BGRL3,S100A14,SFN,HSPB1,DUSP1,JUNB,DAPL1,SDC1
15  EMP1,RBP1,FGFR1,IRF3,COX7A2,SEMA3C,CD24,MSX2,AREG,MBOAT7
16  ISG15,ID3,ID1,TFF1,CACNB3,CPE,NMT1,CTSD,NMI,PITX1,TFF3,EGR3
17  SH3GL2,TUBA1A,TUBB2A,ZNF593,NMB,HSPA8,CTSD,PTMS,CD24,NFIC,ZNHIT2,CNN2,HRAS,VCL,WDR62,ACAP3,ABCC2,FLAD1,TFF3,ZNFX1,TRMT2A,CLSPN,RPS25,PAK1IP1,INPP5K,CDH24,ZCCHC10,MEPCE,KLF6,SDC1,PKMYT1,RRP1,TUBB4B,ZBTB7A,CAPS,RECQL4,BRD8,RCAN1,VPS25,GRK6,TROAP,SRF,CDR2,FYN,AP3D1,TIMP1,CYTH3,AFAP1,ZSCAN5A,CDC25B,ABCA7,SMARCD1,BAIAP2,RANGAP1,KANK2,CIC,BRD7,LARP7,CDC42EP1,NLRP2,DNAJB1,E2F1,MZF1,REEP1,SLC44A2,ZNF587,HMGB3,MID1,CYTH2,FKBP1A,CDC42EP4,CCNE2,NFE2L2,DHX8,RPL27A,CCNE1,TNPO2,TUBD1,SAP30BP,ASF1B,MNT,TULP4,CRK,MCM5,APEX2,NCOA5,CTCF,CADM1,MRPS18B,YWHAH,CHAF1A,TTF2,SMTN,DKC1,TMEM138,CENPM,SEC62,HAUS5,CHML,FADD,KIAA1586,MRI1
18  MT1H,COL4A5,KCNMA1,HES2,ATOH1,DIO3,NRCAM,ANKRD18A,PRICKLE1,MT1X,MAGI2,TBX2,NR4A3,ELAVL2,POLR2I,GJB2,ATAD3B,UQCR10,FRMD3,NDUFA13,PLEC,IRX3,SIX5,CFTR,SHROOM1,KCNQ1,BCL2,VDR,CTSD,FOXQ1,MESP1,PARP12,GALNT10,JUN,C1orf122,ABTB2,HNRNPM,BTG2,HIST1H2AH,PXMP2,MSX2,PLEKHJ1,ATF3,PARM1,PITX1,MKX,FBP1,TBL3,SGPP2,GDA,SHISA6,HOXB13,HIST1H2AL,EGR3,PLXNA2,TRIM36,FZD10,CYP1B1,DNAJC22,MT1A,FUT4,ZBTB7A,PRKG1,LHFPL3,FARSA,PRKCE,FOS
19  ROBO1,VSNL1,PROM1,FGFR1,HSPA8,PODXL,AEN,HNRNPAB,NOP56,DDX18,NOP16,CD24,DDX21,BOP1,EXOSC5,PAK1IP1,DNMT3A,MYO19,RRP15,TEAD4,TUBB4B,KRT8,MGST1,MAK16,TTLL12,LRP8,SCNN1A,LARP7,FRAT2,FKBP5,CEBPZ,PITPNC1,NOC3L,MAD2L2,HMGB3,POLR3G,SLC6A8,AKIRIN1,GNPTAB,ZNF195,CNTNAP2,SERBP1,PUS1,NOLC1,HSPA4,MFGE8,NDUFAF4,FZD7
20  MT1H,HES5,COL4A5,CWH43,KCNMA1,HES2,SH3GL2,ATOH1,DIO3,PADI2,ANKRD18A,MT3,CRIP1,TBX2,NR4A3,NOXO1,ELAVL2,GJB2,LEF1,NPAS2,NOTUM,FRMD3,CACNB3,PLEC,IRX3,TNFRSF1B,PRUNE2,KCNQ1,BCL2,VDR,FOXQ1,MESP1,PHLDB1,JUN,NFIC,ABTB2,BTG2,PXMP2,MSX2,TMEM54,RNPEPL1,ATF3,PARM1,PITX1,PARP8,MKX,FBP1,SGPP2,SHISA6,HOXB13,EGR3,PLXNA2,TRIM36,CDX1,TACR1,IMPDH1,FZD10,DNAJC22,MT1A,MXRA7,FUT4,ZBTB7A,PRKG1,PRKAG2,NBL1,SLCO3A1,TRIM28,LHFPL3,PRKCE,ADAM22,PARD3B,SATB2,SLC35G1
21  ZNF274,SPIB,MT2A,MT3,RPS26,NDUFB2,TIMM8B,NDUFA1,NDUFS6,ZNF593,UQCR10,NDUFA2,TNFRSF21,NDUFB1,IRF3,RPS21,NDUFA6,COX7C,PTOV1,MAFF,CYBA,TRMT6,RPL35,RPL37,ZMPSTE24,METTL1,PA2G4,PSME3,RPS27L,RPL31,SNRPD3,ARFRP1,NFKBIB,NDUFB3,FKBP2,RPS25,RPS19,ZNF142,DDX5,PRDX5,POLE3,SLC5A6,NUP62,PLOD3,NDUFB6,TRIB1,WDR46,IER2,NUBP2,HSPE1,RRP9,MYBBP1A,DPM2,SCAMP3,ARPC4,NAA38,PLA2G15,NDUFB4,FTSJ1,PNO1,CLCN2,LAGE3,TP53,SCAND1,ADAM22,RPS13,ZFPL1,PSMD14,MYCBP,MTOR,KPNA3,CDC25B,MMP15,NAGPA,DMAP1,SDF2L1,UXT,SQSTM1,ELOVL1,RPLP1,PTDSS1,CNDP2,CUTA,IDH3B,TRIM44,CXXC1,CLN3,CEBPZ,ETF1,CDK16,SMC1A,PDK2,NME1,TUBG1,SIGMAR1,TYK2,COIL,RPS27A,RPS20,POLR3G,MLX,RPS29,USP4,TIMM23B,PSMC5,AP4M1,MRTO4,CYTH2,NUBP1,SYK,PMVK,DDX10,STUB1,RPL32,PTPN6,STYXL1,TSC2,TRAPPC3,PPT2,NUFIP1,EIF3K,RFX5,RPL27A,WDR4,KHK,RRAS,KEAP1,RXRB,PRKAG1,NCL,PRKCSH,HIST1H2BH,SLC25A11,RAB8A,MCM5
22  HSD11B2,SMAD7,ID3,SURF6,ARSB,HSPA8,FOSL1,SYNGR2,IRF3,BCL2,SRM,HES1,JUN,RPS15,RPL36A,CEBPA,JUNB,NOP2,RHOG,RPS19,EGR3,AMPD2,BCL3,STAT6,UBA52,MAN2A2,MGST1,SLC19A1,MTHFR,UROD,POLB,SQSTM1,ASCL2,SLC4A2,BAX,E2F1,NME1,SIGMAR1,IFRD2,AP4M1,TSC2,RPL27A,POLR3D,RXRB,RBM3,NCL,HSP90AA1,POLD2,HMGN2,AKAP1,RPL23A
23  LBR,MND1,CDK1,NDC80,ANLN,DCUN1D5,STMN1,RAD54L,NDUFB5,C1orf112,RANBP1,CNIH4,PCNA,PFDN2,RACGAP1,TYMS,CDKN3,NCAPG,CENPE,ASPM,SPAG5
24  ID1,OLFML3,TEAD2,ELAVL2,RPS26,FGFR2,TIMM8B,UQCR10,AKT1S1,NDUFA2,FGFR1,NDUFA11,ARMC6,TMSB10,B3GALT4,ALCAM,ABTB2,ABCF2,DDX21,ATF3,EXOSC5,RPL36A,SNRPD3,PHF23,ZNF428,THOP1,SGTA,FAM98A,AVEN,SCAF1,PIN4,SCNM1,DDX5,TMEM160,EGR3,POLE3,MRPS11,SSR4,NOL6,FZD10,PIP5K1C,TMEM109,TBC1D17,AP2A1,MED25,URM1,FARSA,TARBP2,LSG1,ICMT,MPND,PPP1R15A,GRK6,RAB4B,PRPF19,KPNA3,COMMD7,RRS1,KLHL5,RFX1,TPM3,ACOT8,TSTD2,TBC1D10B,STAT3,RPLP1,DDX39A,MUS81,SKIL,SCNN1A,LARP7,FRAT2,GSK3A,CLN3,NIP7,DCAKD,NOC3L,CDK16,PIK3R3,PER2,STAP2,MAP3K11,TUBG1,MCTS1,ZNF668,DPP3,POLR3G,UBQLN4,RPS29,ACTR1A,TIMM23B,RPL30,STXBP2,AKIRIN1,GNPTAB,RNF31
25  MT1H,CXCL1,PTCHD1,IL1RAPL1,CDH13,COL4A5,PYCARD,CWH43,KCNMA1,HES2,ATOH1,DIO3,NRCAM,ANKRD18A,PCDH11X,PRICKLE1,MT1X,CRIP1,TBX2,NR4A3,NOXO1,RARRES1,GJB2,LEF1,NPAS2,NKD1,FRMD3,LAMA3,PLEC,IRX3,SIX5,SRPX2,TNFRSF1B,CFTR,BCL2,VDR,MESP1,PHLDB1,JUN,NFIC,C1orf122,ABTB2,BTG2,PXMP2,TMEM54,ATF3,PARM1,PITX1,MKX,FBP1,E2F4,SGPP2,GDA,SHISA6,HOXB13,EGR3,PLXNA2,TRIM36,TACR1,IMPDH1,FZD10,CYP1B1,DNAJC22,MT1A,ELF4,FUT4,PRKG1,NBL1
26  COL4A5,TCF4,MT2A,ID3,ELAVL2,CX3CL1,ATF5,FGFR2,ATP6V0D1,ID4,CSRP1,CTSA,TP53INP2,FGFR1,VDR,NDUFA6,PTOV1,CD24,GRN,YPEL3,CLN6,MXD4,DCTN2,CYP1B1,MT1A,S100A13,TAPBP,MAPRE3,ARSA,TMEM150A,HCFC1R1,VPS28,FN1,GRINA,CHMP2A,NAGK,SPTBN1,NDUFV3,DNAJB2,THRA,STAT3,SQSTM1,PLD3,LYRM2,TSPYL4,GNAI2,HES6
27  CXCL1,THBS1,NGEF,CDKN1A,NR4A1,GRWD1,PFDN6,NMT1,FOSL1,TOMM40,DDX18,SRM,JUN,ALCAM,ABCF2,DUSP1,EIF3J,DDX21,BOP1,ACTN4,PA2G4,RNASEH2A,NHP2,FTSJ3,SNRPD3,LATS2,MRPL12,TBL3,FKBP2,COX17,NOP2,LRRC59,TNFAIP3,SPECC1,CD151,EIF6,RBMXL1,PPRC1,NFKBIA,SLCO3A1,NAA38,PNO1,RBM38,BYSL,TP53,TIMM23,RRP12,GRK6,MAK16,CDR2,CYCS,TIMP1,FAM136A,RRS1,IER3,EZR,EPHA2,ANXA3,DHRS7B,SNRPD2,TCF19,RANGAP1,FRAT2,FKBP4,C6orf136,BAX,ETF1,CYHR1,E2F1,NME1,TUBG1,PNPT1,HMGB3,HIGD1A,IFRD2,TIMM8A,WDR43,LRRC8C,MRTO4,TRAF3,RUVBL2,DCTPP1,PSMD13,RSL1D1,NUBP1,MYBL2,GAR1,DNMT1,HSPA4,ACOT7,NDUFAF4,ASF1B,PTPRE,EBNA1BP2,MCM5,HSP90AA1,MRPS25,PON2,ESF1,DTYMK
28  PODXL,HNRNPAB,DDX21,KRT18,KRT8,MGST1
29  HNRNPH3,PATL1,EIF4A3,CDK1,MNS1,ECT2,CAND1,PTGES3,NAP1L1,TRA2B,CCDC15,NF1,NCBP2,SEC23A,RLIM,HBS1L,RACGAP1,TYMS,FSD1L,CKAP5,UBXN2B,AGAP1,KIF11,FBXO3,PSMD10,SEC24B,FANCI,RFC5,CEP57,PNMA1,SMC4,SMS
30  GSK3B,GATA4,TGFBR2,TGFBR3,MAP3K7
⋮   ⋮
562 MT2A,MT1X,THBS1,MB,ATF5,RPUSD1,SELENBP1,RPL38,ABTB2,FRMD8,GRN,TFF3,C19orf48,PDP1,PAQR8,C9orf16,CEBPA,NECAB3,RPL37A,SNHG12,MBNL3,UQCRB,MRPL33,NIPAL2,CD151,RBMXL1,S100A13,CROT,SRRT,DSTN,CDV3,RHOB,ZMIZ1,SPTBN1,RFX1,TCF3,USP36,AURKAIP1,LTBP1,PDRG1,CTDSP1,GFM1
563 LY6E,PELI2,DPH2,ATAD3B,EXOSC4,EGR1,HNRNPAB,NOP16,SNRPG,EXOSC5,FAM32A,NHP2,PREB,CLSPN,TNFAIP3,NOL6,HSPE1,TOE1,CD151,UTP15,E2F2,ALDH1B1,PKMYT1,PNO1,BYSL,LDLR,FOS,SUV39H1,RRP12,MRPS12,RRP7A,GEMIN4,FAM136A,SLC25A19,EZR,SDF2L1,TCF19,LRP8,PIGW,MIF,CCM2,FKBP4,NIP7,ARRB1,HMGB3,MRTO4,DCTPP1,MYBL2,CCNE2,GABPB2,WDR4,CCNE1,RFWD3,ASF1B,PTPRE,EBNA1BP2,MCM5,HSP90AA1,URB2,POLR3H,CHAF1A,KLHDC3,DNAJA1,DKC1,TFAM,PSMC3IP,CENPM,ACY1,LYAR,TSR1,B4GALT2,TAF4B,UMPS,E2F7,SLC9A3R1,MCM7,MCM10
564 CXCL1,CXCL2,DIO3,CXCL3,LY6E,COX7B,TNFRSF21,ATAD3A,PSMB8,PARP12,SRM,NOP16,SEMA3C,INPP4B,DENND2A,TPM1,ZNHIT1,EHD4,TRIB1,IL4R,CYP1B1,PLCB4,OSTM1,HS3ST1,DEF8,OAS3,DVL1,MTOR,POP7,PDLIM5,GLRX2,PDCD5,EPHA2,TSTD1,WWC3,SACS,DNAJC15,HIGD1A,MID1,POLR3G,PPIF,TM4SF1,SLC4A7,COX5A,CCNE2,GAR1,AIMP1,MTAP,HSPA4,CCNE1
565 RYK,CCNG1,VAPA,TCEA1,IVNS1ABP,PCNP,H1F0,SLC50A1,PEX19,PTGES3,ERGIC2,B2M,ESD,NUDT21,RLIM,CNBP,GSK3B,RACGAP1,DLG1,APLP2,TGFBR3,XDH,CSAD,WDFY1,KLHL9,TCF7L2,SSR1,ATF4
566 MT1E,NDUFB7,BLOC1S1,NDUFS6,S100A14,RPL28,HSPA8,RPS21,HNRNPAB,TMSB10,COX7A2,COX8A,EIF5B,RPL35,CNN2,ABCF1,VCL,RPL34,FAU,S100A6,TSTA3,RNASEH2A,NHP2,RPLP2,RPL21,DDX5,PRDX5,MPDU1,SSNA1,IER2,HSPE1,PMPCA,NFKBIA,TRIM28,ATP2A1,EIF2B3,RALBP1,SHROOM3,FN1,PC,PAF1,SPTBN1,RPS11,RPS15A,PPAN,EZR,SNRPD2,RALY,BRD7,ANXA2,FKBP4,ABCF3,BAG1,SMC1A,CRELD2,RDX,HIGD1A,DPP3,RPS29,DAB2,CAMK2G,RPL30,KIFAP3,NEDD8,SYK,RPL32,SERBP1,NFE2L2,AIMP1,HSPA4
567 FGB,KCNMA1,SH3GL2,HPGD,EMP1,ICAM3,SLC39A2,TIMM10,NDUFS6,ZNF593,NR4A1,MRPL41,CEACAM6,HSPA8,CD3EAP,NMT1,CCDC137,VDR,DDX18,SRM,TRMT1,NOP16,EIF5B,SLC25A10,IRAK1,NFIC,TRMT6,HNRNPM,ABCF2,MAP7D1,ZMPSTE24,HRAS,SLIRP,DDX21,ENDOD1,PA2G4,EVI5L,ATP10B,PSME3,FLAD1,DHX37,MRPS18C,DAPK3,CLN6,THOP1,NFKBIB,MRPS36,NDUFB3,DUSP5,DOLK,NOP2,DDX46,EPDR1,YDJC,NOP14,MRPL36,SLC25A20,POLE3,EHD4,BCL3,NETO2,TRIB1,PSMD1,CCHCR1,RRP9,PPRC1,SDC1,RRP15,TEAD4,POP1,POLR2F,ARPC5L,KITLG,PNO1,BYSL,SRFBP1,OSTM1,LSG1,EIF2B3,PGBD5,TMEM126B,GFOD1,CSK,MGST1,ZMYND19,HGS,PSMD14,DEF8,MRPS12,BID,TAF13,NDUFV3,POP7,GLRX2,SRPRB,MRPL27,TPM3,SCFD2,SRP19,GNL2,ZFP41,SDF2L1,LRP8,QRSL1,PTDSS1,C9orf78,PALM2-AKAP2,LLPH,KLHL18,ZBTB2,ANXA2,SRXN1,SLC20A1,FKBP4,GFM1,PSD4,CLN3,ETF1,TIMM50,RNASEH1,C1orf131,OGFOD1,SMC1A,RRP1B,PPM1G,PSMD2,WDR1,SVIP,OTUD6B,KPNA4,PNPT1,SIGMAR1,TRAFD1,TOMM5,CDC123,LSM10,DYNLL2,PPIF,USP5,SLC35B1,WDR43,DDX20,MRTO4,SLC25A39,DCTPP1,PSMD13,DNTTIP2,MPHOSPH10,DDX10,SERBP1,CCNE2,PUS1,SLC9A1,SNRPF,RIOK1,DNMT1,NOLC1,HSPA4,WDR4,CCNE1,PLLP,RFWD3,ZC3H18,NDUFAF4,RABEPK,IDE,C1orf109,NOX1,URB2,CHCHD4,ESF1,LARP4,IMP4,E2F3,GNPDA1,PGP,CHCHD1,AKAP1,CALR,YWHAH,STARD7,NSDHL,HAUS2,CHRNA5,DKC1,TFAM,TMEM138,SLC25A32,ATP6V0B,CHML,NOP58,ZC3H13,UPF2,CORO7,LYAR,EXOSC2,KIAA0556,TOR3A,CD58,AMD1,SFPQ,UCK2,B4GALT2,TAF4B,HMGB1,UMPS,MRPL15,MAPRE1,E2F7,SYMPK,DHX33,TM2D2,TTL,SCO1,TMEM97,MCM10,PMM2,CISD1,NUDT19,SMARCA4,MRPL14,LYN,AHSA1,ANKRD39,TMEM177,POLE4,EIF4G1,XIAP,ANAPC5,UBAP2L,CANT1,TXNDC9,DUS3L,PHB,CBFB,HNRNPU,POLR3K,PHF5A,POP4,MCM8,UXS1,TOP1,FASTKD2,PVR,NAA15,CCT6A,MRPS15,DCBLD2,HPS1,LDLRAD3,MAN1A2,WDR75,MAP2K3,HSPH1,EIF3B,GRB2,UHRF1,RAD51C

#### Save significant pthwys

In [96]:
#loop for saving all sig pathways

#store the filtered dataframes
filtered_dfs <- list()

#loop through each module and filter the dataframe
for (i in 0:11) {
    #dataframe for the current module
    fgsea_res <- fgseaResults[[paste0("fgseaRes_", i)]]
    gsea_df <- data.frame(fgsea_res)
    
    # Filter the dataframe based on conditions
    filtered_df <- gsea_df %>% dplyr::filter(abs(NES) > 1 & padj < 0.05)
    
    # Save the filtered dataframe as a variable
    assign(paste0("gsea_df_fgseaRes_", i, "_save"), filtered_df, envir = .GlobalEnv)
    
    # Add the filtered dataframe to the list
    filtered_dfs[[i + 1]] <- filtered_df
    
    # Define the file paths for saving
    txt_file <- sprintf("/data/chanjlab/CRC_ZFP36L2.092023/Patients.HTAN/output/organoid_ML/GSEA_local_corr_modules_DEGS/module_significant_pathways/GSEA_sig_pthwys_local_corr_module_%s.txt", i)
    csv_file <- sprintf("/data/chanjlab/CRC_ZFP36L2.092023/Patients.HTAN/output/organoid_ML/GSEA_local_corr_modules_DEGS/module_significant_pathways/GSEA_sig_pthwys_local_corr_module_%s.csv", i)
    
    # Save the filtered dataframe as text and CSV files
    write.table(filtered_df, file = txt_file, sep = "\t", quote = FALSE, row.names = FALSE)
    write.csv(filtered_df, file = csv_file, quote = FALSE, row.names = FALSE)
}

# Optionally, you can access the saved dataframes using gsea_df_fgseaRes_#_save

In [105]:
gsea_df_fgseaRes_5_save

   pathway                                          pval         padj
1  BENPORATH_EED_TARGETS                            1.575756e-04 0.0086666556
2  BENPORATH_ES_WITH_H3K27ME3                       1.035101e-05 0.0011386106
3  BENPORATH_SUZ12_TARGETS                          4.320543e-06 0.0007920995
4  EED_TARGETS_BENPORATH                            1.349032e-04 0.0082440867
5  GO_POSITIVE_REGULATION_OF_NEURON_DIFFERENTIATION 4.349771e-05 0.0039872898
6  GO_REGULATION_OF_NEURON_DIFFERENTIATION          7.006538e-04 0.0321132986
7  H3K27_BOUND_BENPORATH                            2.699958e-06 0.0007424883
8  HOLLEMAN_ASPARAGINASE_RESISTANCE_B_ALL_UP        7.978772e-05 0.0058553627
9  HotSpotModule_3.LIPID_METABOLISM                 1.494485e-06 0.0007424883
10 MEISSNER_BRAIN_HCP_WITH_H3K4ME3_AND_H3K27ME3     8.516891e-05 0.0058553627
11 PRC2_TARGETS_BENPORATH                           5.266381e-04 0.0263319043
12 SUZ12_TARGETS_BENPORATH                          5.979601e-06 0.0008221951
   log2err   ES         NES       size
1  0.5188481 -0.6383356 -1.610327 156
2  0.5933255 -0.7137064 -1.784994 117
3  0.6105269 -0.6955469 -1.750085 134
4  0.5188481 -0.6614579 -1.664505 144
5  0.5573322 -0.7404586 -1.844364  77
6  0.4772708 -0.6311270 -1.589002 138
7  0.6272567 -0.7309848 -1.829518 109
8  0.5384341  0.6673830  2.808364  12
9  0.6435518 -0.9120829 -2.135753  23
10 0.5384341 -0.6085148 -1.545600 233
11 0.4772708 -0.7410602 -1.815863  57
12 0.6105269 -0.7109354 -1.782134 125
   leadingEdge
1  HOXD3,ATOH1,SLC22A3,MAGI2,RIN3,HOXA13,PGM5,PRKG1,BMPR1B,SIDT1,ITPKA,EML5,CYP1B1,DOCK11,TRIM9,CXCL16,GDA,FBP1,COL27A1,FOXD2,MSX2,PIP5K1B,REPS2,NPNT,PXMP2,PPM1E,SOX5,CA3
2  HOXD3,ATOH1,SLC22A3,HOXA13,CRIP1,AMN,C1orf115,PGM5,RAMP1,TLE2,PRKD1,PRKG1,NBL1,SIDT1,ITPKA,PRKAG2,TRIM9,SLC40A1,CXCL16,ABCC3,FBP1,XYLT1,BLVRB,COL27A1,FOXD2,MSX2,PIP5K1B,REPS2,NPNT,PXMP2,PPM1E
3  HOXD3,ATOH1,RIN3,PTCHD1,RASEF,CRIP1,AMN,GIPC2,C1orf115,GNAS,PGM5,ST3GAL6,PRKG1,NBL1,SIDT1,LAMA3,ITPKA,EML5,CYP1B1,TRIM9,SLC40A1,CXCL16,GDA,FBP1,XYLT1,FOXA1,COL27A1,FOXD2,PIP5K1B,REPS2,NPNT,PXMP2,PPM1E,PCDH11X,CA3,MGLL,ACSS1,NDRG1,RARRES1,MT1X,IHH,NHS,OSR2,DDAH1,TET2,MNX1,TMEM30B,DNAJC22,CAMK2N1
4  HOXD3,ATOH1,SLC22A3,MAGI2,RIN3,HOXA13,PGM5,PRKG1,BMPR1B,SIDT1,ITPKA,EML5,CYP1B1,DOCK11,TRIM9,CXCL16,GDA,FBP1,COL27A1,FOXD2,MSX2,PIP5K1B,REPS2,NPNT,PXMP2,PPM1E,SOX5,CA3
5  HOXD3,ATOH1,MAGI2,ROBO2,RIMS2,CNR1,SERPINE2,RARB,PRKD1,NBL1,ITPKA,AKAP5
6  HOXD3,ATOH1,MAGI2,ROBO2,RIMS2,CNR1,SERPINE2,RARB,PRKD1,BCL11B,NBL1,ITPKA,SLC6A4,ID1,NOTCH3,AKAP5,XK,FOXA1,TGIF2,DLL1
7  HOXD3,ATOH1,SLC22A3,HOXA13,CRIP1,AMN,PGM5,RAMP1,TLE2,PRKD1,PRKG1,NBL1,SIDT1,ITPKA,PRKAG2,TRIM9,SLC40A1,CXCL16,ABCC3,FBP1,XYLT1,BLVRB,COL27A1,FOXD2,MSX2,PIP5K1B,REPS2,NPNT,PXMP2,PPM1E
8  TPM4,EIF3L,FBL,RPL4,RPL3,EEF1G,EIF3K,EIF3D,RPL7A,RPS3
9  ADH1C,HPGD,AKR1B10,ZG16,FABP2,APOA1,TM4SF20,RAMP1,SLC51B,MEP1A,ALDH1A1,ANXA13,SDCBP2,SLC40A1
10 SLC22A3,RIN3,SLC7A2,VSTM2B,RASEF,ROR1,SERPINE2,IRF8,CREB3L1,GIPC2,TRPM6,C1orf115,GNAS,PGM5,C4orf19,ID3,PRKG1,SMOC1,NBL1,ARHGAP10,SIDT1,ITPKA,CDKN2A,MOB3B,FLVCR2,NFATC2,PDE3A,TMEM98,CXCL16,MTUS1,NDRG2,TRNP1,SMO,TC2N,FGFR3,FZD7,AGPAT2,TMEM37,COL27A1,FOXD1,MSX2,DOCK8,KCNK6,NPNT,PPP1R14A,EPB41L1,DAB2,ASS1,DDAH2,F3,UTRN,NDRG1,MLKL,VAV2,PKIB,GAB1,CPNE7,OSR2,ARHGEF26,RBPMS,IL4R,TES
11 HOXD3,ATOH1,PGM5,PRKG1,SIDT1,ITPKA,TRIM9,CXCL16,FBP1,COL27A1,FOXD2,PIP5K1B,REPS2,NPNT,PXMP2,PPM1E
12 HOXD3,ATOH1,RIN3,PTCHD1,RASEF,CRIP1,AMN,GIPC2,GNAS,PGM5,ST3GAL6,PRKG1,NBL1,SIDT1,LAMA3,ITPKA,EML5,CYP1B1,TRIM9,SLC40A1,CXCL16,GDA,FBP1,XYLT1,FOXA1,COL27A1,FOXD2,PIP5K1B,REPS2,NPNT,PXMP2,PPM1E,PCDH11X,CA3,MGLL,ACSS1,NDRG1,RARRES1,MT1X,IHH,NHS,OSR2

In [101]:
read_module_0 = read.table("/data/chanjlab/CRC_ZFP36L2.092023/Patients.HTAN/output/organoid_ML/GSEA_local_corr_modules_DEGS/module_significant_pathways/GSEA_sig_pthwys_local_corr_module_0.txt", header = TRUE, sep = '\t')

In [102]:
read_module_0

   pathway
1  BENPORATH_EED_TARGETS
2  BENPORATH_ES_WITH_H3K27ME3
3  BENPORATH_SUZ12_TARGETS
4  CREIGHTON_ENDOCRINE_THERAPY_RESISTANCE_2
5  EED_TARGETS_BENPORATH
6  GO_AXON
7  GO_AXONEME_ASSEMBLY
8  GO_AXON_PART
9  GO_CELL_CELL_ADHESION
10 GO_CELL_MORPHOGENESIS_INVOLVED_IN_NEURON_DIFFERENTIATION
11 GO_CENTRAL_NERVOUS_SYSTEM_NEURON_DEVELOPMENT
12 GO_CENTRAL_NERVOUS_SYSTEM_NEURON_DIFFERENTIATION
13 GO_FOREBRAIN_GENERATION_OF_NEURONS
14 GO_FOREBRAIN_NEURON_DEVELOPMENT
15 GO_NEUROGENESIS
16 GO_NEUROLOGICAL_SYSTEM_PROCESS
17 GO_NEUROMUSCULAR_JUNCTION
18 GO_NEUROMUSCULAR_JUNCTION_DEVELOPMENT
19 GO_NEURON_DEVELOPMENT
20 GO_NEURON_DIFFERENTIATION
21 GO_NEURON_MIGRATION
22 GO_NEURON_PART
23 GO_NEURON_PROJECTION
24 GO_NEURON_PROJECTION_DEVELOPMENT
25 GO_NEURON_PROJECTION_GUIDANCE
26 GO_NEURON_PROJECTION_MORPHOGENESIS
27 GO_NEURON_PROJECTION_TERMINUS
28 GO_NEURON_RECOGNITION
29 GO_NEUROTRANSMITTER_TRANSPORT
30 GO_NEUROTROPHIN_SIGNALING_PATHWAY
⋮  ⋮
54 KEGG_CELL_ADHESION_MOLECULES_CAMS
55 LECTINpos_KRT5pos_BASAL
56 MASSARWEH_TAMOXIFEN_RESISTANCE_DN
57 MEISSNER_BRAIN_HCP_WITH_H3K4ME3_AND_H3K27ME3
58 MOOTHA_VOXPHOS
59 NABA_MATRISOME
60 NABA_MATRISOME_ASSOCIATED
61 NABA_MATRISOME_ASSOCIATED
62 NAKAMURA_TUMOR_ZONE_PERIPHERAL_VS_CENTRAL_DN
63 PEREZ_TP53_TARGETS
64 PID_HIF1_TFPATHWAY
65 PID_INTEGRIN1_PATHWAY
66 PRC2_TARGETS_BENPORATH
67 REACTOME_APC_C_CDC20_MEDIATED_DEGRADATION_OF_MITOTIC_PROTEINS
68 REACTOME_APC_C_CDH1_MEDIATED_DEGRADATION_OF_CDC20_AND_OTHER_APC_C_CDH1_TARGETED_PROTEINS_IN_LATE_MITOSIS_EARLY_G1
69 REACTOME_AUTODEGRADATION_OF_CDH1_BY_CDH1_APC_C
70 REACTOME_AUTODEGRADATION_OF_THE_E3_UBIQUITIN_LIGASE_COP1
71 REACTOME_CELL_CELL_JUNCTION_ORGANIZATION
72 REACTOME_INTRINSIC_PATHWAY_FOR_APOPTOSIS
73 REACTOME_REGULATION_OF_APOPTOSIS
74 REACTOME_REGULATION_OF_MITOTIC_CELL_CYCLE
75 REACTOME_RESPIRATORY_ELECTRON_TRANSPORT
76 REACTOME_RESPIRATORY_ELECTRON_TRANSPORT_ATP_SYNTHESIS_BY_CHEMIOSMOTIC_COUPLING_AND_HEAT_PRODUCTION_BY_UNCOUPLING_PROTEINS_
77 SCLC-Y
78 SCLC_CCLE
79 SMID_BREAST_CANCER_BASAL_UP
80 SUZ12_TARGETS_BENPORATH
81 WONG_ADULT_TISSUE_STEM_MODULE
82 axonogenesis_Yang_etal
83 hESC_PRIMED_SMITH_CELL2018
   pval         padj         log2err   ES         NES       size
1  5.303902e-05 9.185600e-04 0.5573322 -0.5377383 -1.460445 189
2  4.946945e-10 6.406294e-08 0.8012156 -0.6363499 -1.727339 155
3  1.617145e-06 5.767586e-05 0.6435518 -0.5864793 -1.588826 151
4  2.478207e-07 1.426346e-05 0.6749629 -0.5946224 -1.610288 165
5  6.937626e-05 1.063341e-03 0.5384341 -0.5444007 -1.478530 179
6  1.507739e-04 1.952521e-03 0.5188481 -0.5496478 -1.482773 141
7  6.524115e-03 4.224364e-02 0.4070179 -0.7592426 -1.633731  11
8  6.749961e-03 4.316642e-02 0.4070179 -0.5560626 -1.459647  69
9  3.274336e-03 2.458124e-02 0.4317077 -0.5026365 -1.360831 149
10 5.066030e-07 2.624204e-05 0.6594444 -0.6210615 -1.667065 120
11 1.214429e-06 5.242284e-05 0.6435518 -0.8165079 -1.978458  23
12 2.306248e-04 2.654747e-03 0.5188481 -0.6707209 -1.729908  46
13 1.897565e-04 2.233952e-03 0.5188481 -0.7998024 -1.843421  16
14 8.568606e-05 1.241717e-03 0.5384341 -0.8568148 -1.843686  11
15 2.097162e-07 1.357912e-05 0.6901325 -0.5017211 -1.382730 476
16 3.339517e-05 7.075671e-04 0.5573322 -0.5338468 -1.450211 187
17 7.541436e-03 4.706583e-02 0.4070179 -0.7030712 -1.652518  18
18 2.421877e-03 2.023439e-02 0.4317077 -0.7816543 -1.713621  12
19 1.281016e-04 1.746227e-03 0.5188481 -0.5220405 -1.422105 225
20 1.600032e-06 5.767586e-05 0.6435518 -0.5230967 -1.430609 289
21 3.086554e-04 3.475728e-03 0.4984931 -0.6991195 -1.757886  32
22 3.283392e-05 7.075671e-04 0.5573322 -0.4791196 -1.318164 431
23 1.445043e-03 1.313215e-02 0.4550599 -0.4695961 -1.286717 324
24 3.732393e-05 7.436076e-04 0.5573322 -0.5400195 -1.466149 182
25 5.319845e-05 9.185600e-04 0.5573322 -0.6498447 -1.697384  63
26 2.803139e-06 8.960532e-05 0.6272567 -0.5943136 -1.600249 132
27 1.086703e-03 1.062099e-02 0.4550599 -0.6508711 -1.650031  37
28 1.053098e-04 1.474337e-03 0.5384341 -0.8719499 -1.846935  10
29 5.497323e-05 9.185850e-04 0.5573322 -0.7162875 -1.817465  35
30 1.701751e-03 1.519840e-02 0.4550599 -0.7960867 -1.713012  11
⋮  ⋮            ⋮            ⋮         ⋮          ⋮         ⋮
54 1.828817e-03 1.605639e-02 0.4550599 -0.7138467 -1.715459  22
55 1.670151e-06 5.767586e-05 0.6435518 -0.6168819 -1.653110 118
56 2.830363e-03 2.221406e-02 0.4317077 -0.5342633 -1.426135 103
57 7.262798e-11 1.881065e-08 0.8390889 -0.5854320 -1.599871 280
58 1.636426e-04 2.067485e-03 0.5188481  0.4807068  2.403211  30
59 1.846164e-11 9.563131e-09 0.8634154 -0.6733770 -1.813700 129
60 2.169813e-08 1.873271e-06 0.7337620 -0.6745704 -1.792012  92
61 2.169813e-08 1.873271e-06 0.7337620 -0.6745704 -1.792012  92
62 2.608377e-03 2.144666e-02 0.4317077 -0.4622331 -1.265747 305
63 3.274336e-03 2.458124e-02 0.4317077 -0.4575787 -1.256936 369
64 9.168007e-04 9.132745e-03 0.4772708 -0.6565920 -1.666560  36
65 7.142856e-03 4.512194e-02 0.4070179 -0.7322354 -1.665970  15
66 1.718658e-04 2.070383e-03 0.5188481 -0.6256576 -1.637129  67
67 2.153849e-03 1.829007e-02 0.4317077  0.3787525  1.983357  37
68 2.801275e-03 2.221406e-02 0.4317077  0.3981099  2.034732  35
69 4.398530e-04 4.847742e-03 0.4984931  0.4521818  2.309749  32
70 5.096046e-03 3.475800e-02 0.4070179  0.4250668  1.914905  23
71 8.548153e-04 8.682242e-03 0.4772708 -0.7458928 -1.759334  19
72 5.099629e-03 3.475800e-02 0.4070179  0.5196062  2.149839  18
73 2.049728e-03 1.769599e-02 0.4317077  0.4239423  1.954444  28
74 4.557127e-03 3.189989e-02 0.4070179  0.3367848  1.947262  44
75 3.814101e-03 2.782682e-02 0.4317077  0.3985814  2.007336  31
76 4.372210e-03 3.102472e-02 0.4070179  0.3892273  1.988177  32
77 6.223903e-03 4.080990e-02 0.4070179 -0.7364142 -1.675477  15
78 3.414899e-05 7.075671e-04 0.5573322 -0.7678228 -1.891197  27
79 2.080424e-05 5.131713e-04 0.5756103 -0.5347281 -1.455639 222
80 2.940715e-06 8.960532e-05 0.6272567 -0.5883015 -1.590359 144
81 1.148708e-07 8.500439e-06 0.7049757 -0.5520098 -1.505771 264
82 6.173454e-05 9.993278e-04 0.5384341 -0.7747408 -1.890843  24
83 6.830501e-04 7.220816e-03 0.4772708 -0.7719593 -1.792920  17
   leadingEdge
1  FZD10,PLXND1,COL4A5,MKX,SHISA6,ANKRD18A,MAGI2,FOXQ1,PPM1E,RASSF5,NRCAM,INHBB,STC2,SLCO4A1,TMOD2,ADM,SLC22A3,NEUROD1,KCNQ1,SOX21,EPHB3,PGM5,FOXA2,PCSK1N,CD44,GAD1,SETD7,GABRA2,ELAVL2,DPY19L2,HOXA3,GADD45G,SGPP2,BAIAP2,DMRT2,DUSP4,RIMKLA,DLL4,SLC1A4,MT1A,NFIX,HLA-A,CSNK1E,NAV2,HOXB3,SIM2,TUBA4A,KIAA1324,IL20RA,EFNA3,GRK5,CASZ1,PIR,LGR5,ABTB2,TBCB,EGR3,HHLA3,GALNT10,STK17A,B4GALT6,RGS10,ATF3,SOX5,HYOU1,PPP1R10,ZNF503,IER5L,INTU
2  FZD10,SMOC2,COL4A5,MKX,EPHA4,SHISA6,ANKRD18A,PTPRN2,NOTUM,NPAS2,FOXQ1,PPM1E,SLC25A27,RASSF5,MLXIPL,STC2,GRB10,SEMA4F,TMOD2,DUSP6,SLC22A3,ADAMTS17,NEUROD1,KCNQ1,LEF1,PRUNE2,EPHB3,PGM5,FOXA2,CYP39A1,DTNB,PARP8,GABRA2,ELAVL2,RAPGEF4,DPY19L2,HOXA3,SLCO3A1,SGPP2,DMRT2,ADAM15,DUSP4,RIMKLA,DLL4,SLC1A4,MT1A,NFIX,HLA-A,SKAP1,NAV2,HOXB3,TTLL7,SYT7,DUSP8,SIM2,CBX4,TNFRSF1B,LAMB1,RPS6KA2,DYNC1I1,KIAA1324,OSBP2,EFNA3,GRK5,CASZ1,PIR,LGR5,ABTB2
3  FZD10,COL4A5,MKX,EPHA4,SHISA6,ANKRD18A,NPAS2,PPM1E,RASSF5,NRCAM,CDH13,BHMT,TLL2,SEMA4F,SLCO4A1,TMOD2,ADM,DUSP6,NEUROD1,SOX21,LEF1,GRIN2B,NKD1,EPHB3,PGM5,FOXA2,PCSK1N,CD44,PYCARD,SETD7,GABRA2,RAPGEF4,DPY19L2,GADD45G,SGPP2,DMRT2,MGLL,DUSP4,RIMKLA,DLL4,SLC1A4,MT1A,NFIX,LRRC8C,NAV2,HOXB3,SIM2,NHS,TNFRSF1B,TUBA4A,KIAA1324,EFNA3,CASZ1,PIR,LGR5,EFNB1,ABTB2
4  C4orf47,MKX,ARMC4,NPHP1,DNALI1,CCDC40,JAZF1,PPM1E,DNAH6,SPATA6,TMEM231,TMEM67,LRP2BP,DNAH7,CEP112,PPIL6,WDR66,TSPAN2,DNAH11,ABLIM2,ARL6,IQCH,RSPH1,C5AR1,KIF3A,HES6,C3orf67,SLC41A1,DPCD,C16orf46,APOLD1,EML6,FANK1,FAM149A,EML1,CCNO,WDR78,LRRC10B,TTC12,IFT81,NGEF,WDR63,NPHP4,MAK,EFHC1,KLHDC9,TRIM73,MOK,PCSK6,CCDC30,SRGAP3,PHTF1,LRRC49,NEK2,KIF9,FSD1L,CDKL3,CCP110,LRRC23,TTC26,LRWD1,RPGRIP1L,DNAH12,IQCG,IQCK,ODF2,CRY1,SEC61A2,CLUAP1,TMCC1,MORN2,NETO2,DNAL4,AKNA,COG7,ARMC2,REEP1
5  FZD10,PLXND1,COL4A5,MKX,ANKRD18A,MAGI2,FOXQ1,PPM1E,RASSF5,NRCAM,INHBB,STC2,SLCO4A1,TMOD2,ADM,SLC22A3,NEUROD1,KCNQ1,SOX21,EPHB3,PGM5,FOXA2,PCSK1N,CD44,GAD1,SETD7,GABRA2,ELAVL2,DPY19L2,HOXA3,GADD45G,SGPP2,BAIAP2,DMRT2,DUSP4,DLL4,SLC1A4,MT1A,NFIX,HLA-A,CSNK1E,NAV2,HOXB3,SIM2,TUBA4A,KIAA1324,IL20RA,EFNA3,GRK5,CASZ1,PIR,LGR5,ABTB2,TBCB,EGR3,HHLA3,GALNT10,STK17A,B4GALT6,RGS10,ATF3,SOX5,HYOU1,PPP1R10,ZNF503,IER5L,INTU
6  ROBO1,CADM2,TUBB3,CORO1A,ADRA2C,DRD2,EPHA4,PTPRN2,STXBP1,MME,RAB3A,NFASC,ALCAM,GABBR1,NRCAM,PTPRO,UCHL1,DISC1,DNM3,AVIL,SEMA3A,GABRA2,SACS,TIAM1,SCN8A,SYT7,TNFRSF1B,LRP8,SRCIN1,NCS1,HOMER1,LMTK3,KATNB1,GARS,GRIK2,PALLD,CHRM3
7  ARMC4,CCDC40,DNAH7,RSPH1,TTLL1,SPAG1,LRRC6
8  ADRA2C,DRD2,EPHA4,PTPRN2,STXBP1,RAB3A,NFASC,GABBR1,NRCAM,UCHL1
9  ROBO1,CADM2,NPHP1,CD74,CADM1,STXBP1,CLDN18,NFASC,ALCAM,NRCAM,CDH13,SLC7A11,SDK1,JAG2,LEF1,CD44,RORA,FGFRL1,NRXN3,CEACAM1,DLL4,MMP24,NPHP4,PODXL2,DPP4,FYN,ANXA9,LAMB1,LIG4,CELSR1
10 MAP1B,ROBO1,PLXND1,TUBB3,DRD2,EPHA4,ETV4,STXBP1,RAB3A,PDZD7,VLDLR,NFASC,ALCAM,KIF5C,NRCAM,PTPRO,FMOD,UCHL1,SEMA4F,TCTN1,LRP4,EPHB3,SEMA3A,NRXN3,ARTN,BAIAP2,LAMA2,CHN1
11 ROBO1,DRD2,EPHA4,FGFR1,DISC1,TCTN1,EPHB3,SEMA3A,SLC4A10
12 ROBO1,DRD2,EPHA4,FGFR1,DISC1,TCTN1,LEF1,EPHB3,SEMA3A,SLC4A10,RORA,DYNC2H1,PROX1,DLL4,PHLDA1
13 ROBO1,DRD2,FGFR1,DISC1,LEF1,SEMA3A,SLC4A10
14 ROBO1,DRD2,FGFR1,DISC1,SEMA3A,SLC4A10
15 FZD10,APCDD1,CXCR4,MAP1B,ETV5,ROBO1,PLXND1,TUBB3,KEL,ADRA2C,TUBB2B,DRD2,TCF4,F2,EPHA4,ETV4,STXBP1,RAB3A,DUSP10,PDZD7,MAGI2,NTF3,VLDLR,NFASC,ALCAM,KIF5C,FGFR1,NRCAM,PTPRO,FMOD,PROM1,METRN,SDK1,JAG2,UCHL1,DISC1,DDIT4,DNM3,NAB2,SEMA4F,ADM,PTPRR,NEUROD1,TCTN1,LEF1,BMP4,LGALS1,AVIL,NKD1,LRP4,TSPAN2,EPHB3,VCAN,CHAC1,CCDC88A,SEMA3A,FOXA2,SLC4A10,RORA,DYNC2H1,KIF3A,AREG,TIMP2,SERPINE2,PROX1,NRXN3,ARTN,BAIAP2,HDAC11,EML1,LAMA2,HS6ST1,SYT17,DLL4,FRY,CHN1,MMP24,NGEF,CAPRIN2,NPHP4,TIAM1,PHLDA1,IFT140,CSNK1E,SOX2,SEMA4B,HOXB3,PRDM16,CDON,PTK7,FYN,LRP8,ARHGEF10,SRCIN1,NCS1,LAMB1,LIG4,WDR62,FBXW8,TTL,CELSR1,SEMA3F,KATNB1,EFNA3,MAP2K1,FBXO31,FARP1,ARL3,MEGF8,PBX3,EFNB1,ARHGEF2,TGFB1,MYEF2,ENAH,DLL1,SUFU,KIF26B,DMD,SIAH2,AHI1,CEBPB,SLC4A7,XBP1,LIMK1,ALS2,CRTC1,CALU,SOX5,RDH13,AGTPBP1,RUNX1,STRN,EIF2B3,ULK4
16 CST1,RGS16,DRD2,COL18A1,CHRNA7,MME,RAB3A,GPR155,PDZD7,VLDLR,NFASC,KCNMB4,TSPEAR,FGFR1,AZGP1,NRCAM,UCHL1,PRNP,TMOD2,KCNQ1,LEF1,GRIN2B,GNAL,TGFBI,ARL6,C5AR1,TNNI3,WDR19,SHC3,SERPINE2,NRXN3,SHROOM4,SPRY2,SCNN1B,CRYM,DLL4,NQO2,SLC1A4,MMP24,FOSL1,TIMP3,SCN8A,UNC119,NAV2,ABCA7,FYN,SOBP,RABGGTB,RPS6KA2,GRIK2,PBX3,ST3GAL4,EYS,GPI,CEBPB,PDE6D,GAA,LRIG1,CRTC1,ITGA2,AGTPBP1
17 COL4A5,EPHA4,PDZRN3,LRP4,SERPINE2
18 ETV5,COL4A5,PDZRN3,LRP4
19 CXCR4,MAP1B,ROBO1,PLXND1,TUBB3,DRD2,EPHA4,ETV4,STXBP1,RAB3A,PDZD7,NTF3,VLDLR,NFASC,ALCAM,KIF5C,FGFR1,NRCAM,PTPRO,FMOD,UCHL1,DISC1,SEMA4F,ADM,NEUROD1,TCTN1,LRP4,TSPAN2,EPHB3,SEMA3A,SLC4A10,AREG,NRXN3,ARTN,BAIAP2,LAMA2,HS6ST1,FRY,CHN1,NPHP4,TIAM1
20 FZD10,CXCR4,MAP1B,ROBO1,PLXND1,TUBB3,DRD2,EPHA4,ETV4,STXBP1,RAB3A,PDZD7,NTF3,VLDLR,NFASC,ALCAM,KIF5C,FGFR1,NRCAM,PTPRO,FMOD,PROM1,JAG2,UCHL1,DISC1,DDIT4,SEMA4F,ADM,PTPRR,NEUROD1,TCTN1,LEF1,BMP4,NKD1,LRP4,TSPAN2,EPHB3,SEMA3A,FOXA2,SLC4A10,RORA,DYNC2H1,AREG,PROX1,NRXN3,ARTN,BAIAP2,LAMA2,HS6ST1,DLL4,FRY,CHN1,NPHP4,TIAM1,PHLDA1,IFT140,CSNK1E
21 CXCR4,TUBB2B,DRD2,FGFR1,NRCAM,DISC1,DDIT4,SEMA3A
22 MAP1B,ROBO1,CADM2,RAB39B,TUBB3,CORO1A,ADRA2C,DRD2,EPHA4,SYN2,BNIP3,PPFIA4,PTPRN2,STXBP1,MME,RAB3A,RAB3B,STX19,PDZD7,MAGI2,NFASC,ENO2,ALCAM,SLC18A1,KIF5C,TSPEAR,GABBR1,NRCAM,CDH13,PTPRO,CTTNBP2,ANK2,PROM1,UCHL1,DISC1,DNM3,TMOD2,CADPS,CPE,AVIL,GRIN2B,GAL,SGCE,LRP4,EPHB3,SEMA3A,SLC4A10,GAD1,GABRA2,PTPN13,SACS,TIMP2,PLK3,SERPINE2,NRXN3,RGS2,BAIAP2,DMXL2,LAMA2,SYT17,PAM,SLC1A4,GNB5,NGEF,FOSL1,TIAM1,MAK,SCN8A,IFT140,PCLO,EFHC1,GPHN,DNAJC6,TTLL7,SYT7,ARHGAP44,TNFRSF1B,LRP8,MYRIP,SRCIN1,NCS1,HOMER1,LMTK3,PSEN2,MPP1,OSBP2,KATNB1,GARS,GRIK2,PALLD,FBXO31,CHRM3,FARP1,ARHGEF2,TGFB1,MTHFR,BAG3,STX2,CSNK1D,GPI,GOT1,DMD,SIAH2,POLG
23 MAP1B,ROBO1,CADM2,RAB39B,TUBB3,CORO1A,ADRA2C,DRD2,EPHA4,BNIP3,PTPRN2,STXBP1,MME,RAB3A,MAGI2,NFASC,ALCAM,KIF5C,GABBR1,NRCAM,CDH13,PTPRO,CTTNBP2,ANK2,UCHL1,DISC1,DNM3,TMOD2,AVIL,GRIN2B,SGCE,LRP4,EPHB3,SEMA3A,SLC4A10,GABRA2,PTPN13,SACS,TIMP2,PLK3,RGS2,BAIAP2,LAMA2,PAM,SLC1A4,NGEF,FOSL1,TIAM1,SCN8A,GPHN,TTLL7,SYT7,ARHGAP44,TNFRSF1B,LRP8,SRCIN1,NCS1,HOMER1,LMTK3,OSBP2,KATNB1,GARS,GRIK2,PALLD,CHRM3,FARP1,ARHGEF2,TGFB1,MTHFR,BAG3,CSNK1D,GPI,GOT1,DMD,SIAH2,POLG
24 MAP1B,ROBO1,PLXND1,TUBB3,DRD2,EPHA4,ETV4,STXBP1,RAB3A,NTF3,VLDLR,NFASC,ALCAM,KIF5C,FGFR1,NRCAM,PTPRO,FMOD,UCHL1,SEMA4F,ADM,TCTN1,LRP4,TSPAN2,EPHB3,SEMA3A,AREG,NRXN3,ARTN,BAIAP2,LAMA2,FRY,CHN1,TIAM1
25 ROBO1,PLXND1,TUBB3,EPHA4,ETV4,NFASC,ALCAM,KIF5C,NRCAM,PTPRO,FMOD,SEMA4F,EPHB3,SEMA3A,NRXN3,ARTN,LAMA2,CHN1,FYN,SEMA3F,EFNA3,EFNB1,ENAH,KIF26B,SIAH2
26 MAP1B,ROBO1,PLXND1,TUBB3,DRD2,EPHA4,ETV4,STXBP1,RAB3A,NTF3,VLDLR,NFASC,ALCAM,KIF5C,NRCAM,PTPRO,FMOD,UCHL1,SEMA4F,TCTN1,LRP4,EPHB3,SEMA3A,NRXN3,ARTN,BAIAP2,LAMA2,CHN1,TIAM1
27 ADRA2C,DRD2,EPHA4,PTPRN2,STXBP1,MME,RAB3A,UCHL1
28 CXCR4,ROBO1,EPHA4,NRCAM,EPHB3,SEMA3A
29 SYN2,PPFIA4,PTPRN2,STXBP1,RAB3A,SLC6A8,STX19,SLC18A1,SLC22A3,CADPS,GAD1,GABRA2,NRXN3,SYT17,PCLO,SYT7
30 CORO1A,MAGI2,DDIT4
⋮  ⋮
54 CADM1,CLDN18,NFASC,ALCAM,NRCAM,VCAN
55 APCDD1,COL18A1,VSNL1,ETV4,MME,SLC6A8,NTF3,AMPD3,NRCAM,CDH13,JAG2,ABCG1,EMP3,CPE,PDLIM7,LRP4,TGFBI,CCDC88A,HUNK,PROM2,HIP1,PDGFC,ARHGAP25,SLCO3A1,ELOVL6,ARTN,FOXO1,ST3GAL2,CRYM,TUBB6,FKBP10,CHSY1,FOSL1,SHMT2,PTPRE,PITPNC1,CDON,SPRY1,CDC42EP3,DEPDC7,TTL,EFNA3,PTPN14,PROCR,PKD2,TGFB1,FADS1,DLL1,EGR3,WIPF1,RGS10
56 COL4A5,TUBB2B,CADM1,IRS1,SUSD3,ADAMTS19,NRCAM,NAB2,H19,RNF183,CPE,PNPLA3,CD44,PYCARD,FGFRL1,HIP1,AREG,KDM4B,PRSS23,TUBB6,MYBL1,SLC1A4,DUSP2,TIAM1,KAZN
57 FZD10,SMOC2,TESC,FBLN2,MKX,ADRA2C,TUBB2B,DRD2,COL18A1,KCNC3,SHISA6,RAB3B,DUSP10,NTF3,ADAMTS19,NOTUM,SNAI1,FOXQ1,TRNP1,KCNH2,CDH13,MLXIPL,PTPRO,INHBB,SMOC1,PROM1,METRN,SP5,PDZRN3,GALNT14,TLL2,DISC1,PHLDA2,SNED1,SLC22A3,ADAMTS17,NEUROD1,SOX21,LEF1,GNAL,DNAH11,PGM5,GADD45B,GAD1,ZBTB7C,KLF2,EGLN3,SLC16A3,AREG,SPRY4,HAS3,KCNH8,SERPINE2,PROX1,GLDC,DMRT2,SEC31B,CGNL1,DUSP4,CCNO,PRSS23,TUBB6,DLL4,RASSF10,FOSL1,FAM110C,PODXL,NES,NFIX,ANTXR2,SOX2,MFSD2A,PRDM16,CD83,FRMD4B,PTPRB,NFE2L3,ARHGAP29,SFI1,KANK4,LAMB1,PMAIP1,SASH1,GXYLT2,SEMA3F,BCL2L11,C6orf141,CASZ1,PTPN14,PDE3A,LGR5,TGFB1,ABTB2,BAG3,CCND1,EGR3,CD302,CPNE2,KIF26B,RGS10,ARG2,CHRNA5,IGFBP2,WNK4,ATF3,LRP5,TGFBR2,CMTM7,ZNF503,RUNX1,EMP2,PLEKHA2,PTPN3,LFNG,ATP7B,DCXR
58 CYCS,CNOT7,COX5A,NDUFB8,CYB5A,COX11,SDHA,NDUFA8,NDUFS8,CYC1,BCL2L1,NDUFB5,SDHB,NDUFA9,NDUFS3,UQCRH,NDUFS2,NDUFA10,NDUFA7,UQCRFS1,SURF1,NDUFS1
59 ANGPT1,SMOC2,PLXND1,COL4A5,FBLN2,COL18A1,F2,FREM1,F13A1,NTF3,ADAMTS19,LOXL1,TSPEAR,INHBB,FMOD,SMOC1,SERPINI1,TLL2,PDGFB,SEMA4F,SNED1,ADAMTS17,BMP4,LGALS1,TIMP1,NID1,VCAN,TGFBI,SEMA3A,HBEGF,EGLN3,AREG,ADAMTS6,TIMP2,ANGPT2,PDGFC,P4HA1,SERPINE2,ARTN,ADAM15,LAMA2,MMP11,SERPINB9,ADAM32,F12,MMP24,ZP3,EREG,TIMP3,CLEC11A,SEMA4B,PCSK6,PLOD1,GDF15,ANXA9,LAMB1
60 ANGPT1,PLXND1,F2,FREM1,F13A1,NTF3,ADAMTS19,LOXL1,INHBB,SERPINI1,TLL2,PDGFB,SEMA4F,ADAMTS17,BMP4,LGALS1,TIMP1,SEMA3A,HBEGF,EGLN3,AREG,ADAMTS6,TIMP2,ANGPT2,PDGFC,P4HA1,SERPINE2,ARTN,ADAM15,MMP11,SERPINB9,ADAM32,F12,MMP24,EREG,TIMP3,CLEC11A,SEMA4B,PCSK6,PLOD1,GDF15,ANXA9
61 ANGPT1,PLXND1,F2,FREM1,F13A1,NTF3,ADAMTS19,LOXL1,INHBB,SERPINI1,TLL2,PDGFB,SEMA4F,ADAMTS17,BMP4,LGALS1,TIMP1,SEMA3A,HBEGF,EGLN3,AREG,ADAMTS6,TIMP2,ANGPT2,PDGFC,P4HA1,SERPINE2,ARTN,ADAM15,MMP11,SERPINB9,ADAM32,F12,MMP24,EREG,TIMP3,CLEC11A,SEMA4B,PCSK6,PLOD1,GDF15,ANXA9
62 FZD10,APCDD1,CA9,ROBO1,COL4A5,TESC,BNIP3,ANKRD37,SLC6A8,VLDLR,ENO2,ADARB1,PTPRO,STC2,JAG2,RRAGD,NAB2,H19,ORAI3,KRT23,SLCO4A1,ADM,CPE,TIMP1,ARNT2,RORA,EGLN3,P4HA1,HAS3,MIR210HG,SGPP2,WFDC2,CACHD1,KDM4B,MZF1,KDM3A,SYT17,TNFRSF10D,PAM,TFPI,PDK1,EREG,SHMT2,FAM110C,SEC24D,TTC28,SEMA4B,BNIP3L,PCSK6,FAM13A,CREB3L2,CBX4,ARRDC3,MOB3A
63 ANGPT1,APCDD1,C4orf47,COL18A1,CELF2,VSNL1,CADM1,SPNS2,GPR155,HOGA1,ENO2,LOXL1,TRAF5,JAG2,ABCG1,H19,KRT23,ADM,KCNQ1,CPE,EPHB3,VCAN,CHAC1,HUNK,HBEGF,ARNT2,ZCCHC24,FUT1,RORA,GAD1,AK1,HES6,HSPA12A,MYT1,FBXO41,GLDC,EML6,BAIAP2,ATP6V0E2,CGNL1,KDM4B,FAM149A,EML1,CEACAM1,HS6ST1,MMP11,RASSF10,FRY,ZNF215,GAMT,KAZN,UNC119,CEP164,SLC25A25,WDR47,GPT2,DNAJC6,EVPL,C12orf76,ARHGAP44,CREB3L2,ABCA7,SLC25A30,CBX4,SPRY1,FYN,USP6NL,GRAMD4,ANXA9,DEPDC7,SMAP2,TBCEL,GLCCI1,KIAA1324,CES1,BCL2L11,KIF9,GRK5,PHLDB3,KSR1,POLH,SH3TC1,ABTB2,DOCK9,MFHAS1,GPR157,STRADA,GALNT10,ARG2,ZNF71,LRPAP1,GAA,LRP5,ABCA1,FAM102A,ISG15,AGAP3,MAP3K14,TRAF3IP1,INTU,ZC3HAV1L,ALDH4A1,BBS1,REEP1,ZNF275,EXT2,ANXA13,MANBA,EEF2,ACVR1,MCF2L,TPST2,ZNF398,SH2B3,ZNF248,ZSWIM6,MYLIP,BACE1,SPATA2L,TSGA10,ZCCHC14,ZNF160,KIAA1549,CLN8,AGAP1,NEDD9,DOCK4,MAN1A1,PHF21A,GMCL1,RFK,MARK4,TMEM107,DFFA,DSTYK,IQSEC1,HAGH,MYO10,WDFY2,ZNF765,INPP4A,EDEM1,ZXDC,ARHGAP19
64 CXCR4,BNIP3,ADM,TERT,HK1,PFKFB3,BHLHE40,RORA,EGLN3
65 COL4A5,COL18A1,F13A1,NID1,TGFBI,LAMA2,IGSF8,CD81,LAMB1
66 FZD10,COL4A5,MKX,ANKRD18A,PPM1E,RASSF5,TMOD2,NEUROD1,EPHB3,PGM5,FOXA2,GABRA2,DPY19L2,SGPP2,DMRT2,DUSP4,DLL4,SLC1A4,MT1A,NFIX,NAV2,HOXB3,SIM2,KIAA1324,EFNA3,CASZ1,PIR,LGR5,ABTB2,EGR3,RGS10
67 PSMB6,CDC23,PSMD13,PSMA7,RPS27A,ANAPC5,PSMA4,PSMA2,ANAPC11,PSMD10,PSMA3,PSMC2,PSMB7,PSMC5,PSMD7,BUB3,PSMD9,PSMD2,PSMD12,ANAPC4,PSMB4,CDC26,UBE2D1,BUB1B
68 PSMB6,CDC23,PSMD13,PSMA7,RPS27A,ANAPC5,PSMA4,SKP2,PSMA2,ANAPC11,PSMD10,PSMA3,PSMC2,PSMB7,PSMC5,PSMD7,PSMD9,PSMD2,PSMD12,ANAPC4,PSMB4,CDC26,UBE2D1
69 PSMB6,CDC23,PSMD13,PSMA7,RPS27A,ANAPC5,PSMA4,PSMA2,ANAPC11,PSMD10,PSMA3,PSMC2,PSMB7,PSMC5,PSMD7,PSMD9,PSMD2,PSMD12,ANAPC4,PSMB4,UBA52,CDC26,UBE2D1
70 PSMB6,PSMD13,PSMA7,RPS27A,PSMA4,PSMA2,PSMD10,PSMA3,PSMC2,PSMB7,PSMC5,PSMD7,PSMD9,PSMD2
71 CADM2,CADM1,CLDN18,CDH13
72 CYCS,DYNLL1,BID,AKT1,CASP3,CASP8,BCL2L1,DYNLL2,TFDP1,APAF1,BAK1,BCL2
73 PSMB6,PSMD13,PSMA7,RPS27A,PSMA4,CASP3,PSMA2,MAGED1,PSMD10,PAK2,PSMA3,PSMC2,PSMB7,PSMC5,PSMD7,APPL1,PSMD9,PSMD2
74 PSMB6,CDC23,PSMD13,PSMA7,RPS27A,ANAPC5,PSMA4,SKP2,PSMA2,ANAPC11,PSMD10,CCNA2,PSMA3,PSMC2,PSMB7,PSMC5,PSMD7,BUB3,PSMD9,PSMD2,FBXO5,PSMD12,ANAPC4,PSMB4,CDC26,UBE2D1,BUB1B
75 CYCS,NDUFA12,COX5A,NDUFB10,NDUFB8,SDHA,NDUFA8,NDUFS8,CYC1,NDUFB5,NDUFV2,SDHB,NDUFA9,NDUFS3,UQCRH,NDUFS2,ETFA,NDUFV1,NDUFA10,NDUFA7,UQCRFS1,ETFB,NDUFS1
76 CYCS,NDUFA12,COX5A,NDUFB10,NDUFB8,SDHA,NDUFA8,NDUFS8,CYC1,NDUFB5,NDUFV2,SDHB,NDUFA9,NDUFS3,UQCRH,NDUFS2,ETFA,NDUFV1,NDUFA10,NDUFA7,UQCRFS1,ETFB,NDUFS1
77 ANGPT1,ADARB1,DUSP6,ZCCHC24,HOXA3,SPRY2,SPRY1,PPM1F
78 CXCR4,TUBB2B,PEX5L,XKR6,ST18,PPM1E,KIF5C,STXBP5L,HES6,PROX1,PGBD5
79 ANGPT1,CA9,TUBB2B,RBP1,COTL1,VLDLR,ISG20,PRAME,PPM1E,ASNS,PROM1,PFKP,GALNT14,UCHL1,RRAGD,DDIT4,DNM3,KRT23,NCALD,ADM,PEG10,GAL,EPHB3,PLEKHB1,CHAC1,CCDC88A,CYP39A1,HBEGF,PCSK1N,CD44,KHDRBS3,IL12RB2,MPP6,PART1,PSAT1,GLDC,ARTN,RGS2,UPP1,PGBD5,CEACAM1,MYBL1,FOSL1,PDK1,UBE2S,NES,CEP170,NFIX,PHLDA1,ODC1,DNAJC6,NFE2L3,SLC16A1,PTP4A3,PTK7,LRP8,EPB41L2,DYNC1I1,SLC7A5,NEK2,WARS,FBXO31,CHRM3,PTPN14
80 FZD10,COL4A5,MKX,EPHA4,ANKRD18A,NPAS2,PPM1E,RASSF5,NRCAM,CDH13,BHMT,TLL2,SEMA4F,SLCO4A1,TMOD2,ADM,DUSP6,NEUROD1,SOX21,LEF1,GRIN2B,NKD1,EPHB3,PGM5,FOXA2,PCSK1N,CD44,PYCARD,SETD7,GABRA2,RAPGEF4,DPY19L2,GADD45G,SGPP2,DMRT2,MGLL,DUSP4,DLL4,SLC1A4,MT1A,NFIX,LRRC8C,NAV2,HOXB3,SIM2,NHS,TNFRSF1B,TUBA4A,KIAA1324,EFNA3,CASZ1,PIR,LGR5,EFNB1,ABTB2,EGR3
81 ROBO1,SMOC2,FBLN2,TCF4,COL18A1,RBP1,CADM1,STXBP1,MAGI2,VLDLR,FOXQ1,ALCAM,GABBR1,AMPD3,ADARB1,NRCAM,INHBB,ABCG1,PHLDA2,DDIT4,NAB2,ADM,LRP2BP,LGALS1,NID1,SLC9B2,SGCE,LRP4,EPHB3,HBEGF,BHLHE40,KHDRBS3,AK1,LPIN1,IQCH,KLF2,SLC41A1,UBE2E2,HOXA3,HLA-DMA,GADD45G,SLCO3A1,ELOVL6,MGST1,RGS2,MYADM,HDAC11,SCG5,DUSP4,LAMA2,PRSS23,WDR78,TUBB6,DUSP2,SSBP2,NR2F1,GNB5,CAPRIN2,TP53BP1,TTC28,TIMP3,CEP170,NFIX,PHLDA1,ANTXR2,PCLO,DUSP8,CBX4,FYN,RASD1,ARHGEF10,LAMB1,SCD,SASH1,ALDOC,ACTR3B,PHLPP1,MSI2,ARL3,PROCR,PKD2,PBX3,LGR5,RHOQ,BAG3,ENAH,CCND1,SERTAD1,DDIT3,DMD,CEBPB,ZNF23
82 CXCR4,MAP1B,ROBO1,TUBB3,EPHA4,VLDLR,NFASC,ALCAM,SEMA4F,EPHB3,SEMA3A,TIAM1,SEMA4B,LRP8,SEMA3F,EFNA3,EFNB1
83 ANOS1,COL18A1,ADAMTS19,UCHL1,DUSP6,SEMA3A,SPRY4,FKBP10,PODXL,PHLDA1,FAM13A

### Lollipop Plots

In [88]:
gsea_df_fgseaRes_1 = data.frame(fgseaResults[["fgseaRes_1"]])

In [89]:
gsea_df_fgseaRes_1 = gsea_df_fgseaRes_1[!duplicated(gsea_df_fgseaRes_1$pathway),]

In [ ]:
gsea_df_